Implement map init and store for Int types
ballerina-platform/nballerina pull request #102
Opened 2021-02-17 08:35 UTC by ruvi-d

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: 

Addresses two sub tasks (Map init and store for Int member types only) listed under #89 

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-02-17 09:04 UTC, ruvi-d commented
Note that there is currently no codegen logic to deinit the Map object. Suggestions are welcome.

2021-02-19 07:31 UTC, KavinduZoysa commented on compiler/llvmFunctionGen.cpp
> +    return LLVMPointerType(LLVMInt64Type(), 0);
Shall we combine these 2 cases?

2021-02-19 08:24 UTC, ruvi-d commented on compiler/llvmFunctionGen.cpp
> +    return LLVMPointerType(LLVMInt64Type(), 0);
Will do

2021-02-19 14:35 UTC, KavinduZoysa commented on compiler/llvmFunctionGen.cpp
>      return LLVMPointerType(LLVMInt64Type(), 0);
@ruvi-d , just to know, what is the reason to set the i64* for map type? What is the theory behind that?

2021-02-19 16:36 UTC, ruvi-d commented on compiler/llvmFunctionGen.cpp
>      return LLVMPointerType(LLVMInt64Type(), 0);
I didn't have a good reason to pick that. Ideally, I would have liked to use something akin to a `void *` so that there is some protection against accidental de-referencing.

2021-02-19 17:24 UTC, KavinduZoysa commented on compiler/llvmFunctionGen.cpp
>      return LLVMPointerType(LLVMInt64Type(), 0);
Thanks @ruvi-d

2021-02-24 08:17 UTC, shubhamnarlawar commented
@ruvi-d - This PR looks fine to me!

2021-02-24 08:19 UTC, shubhamnarlawar commented
@ayonam - Can you please take quick look at this PR to give any suggestions if required?

2021-02-24 08:58 UTC, ramakotareddy commented
@ruvi-d  i have gone through Translation side code, Code looks good to me.
@ayonam Can you please give your comments.

2021-02-24 09:20 UTC, ruvi-d commented
@shubhamnarlawar and @ramakotareddy noted thanks. Please use the Github option "Review changes" and then select "Approve / Request changes" to complete your review

2021-02-24 09:25 UTC, shubhamnarlawar approved these changes
Good to merge!

2021-02-24 10:59 UTC, KavinduZoysa commented
`map<int> marks = {}`
@ruvi-d , I got the .ll file for above simple code and it is as followed.

```
define void @main() {
entry:
  %"%0" = alloca i32, align 4
  %"%1" = alloca i64*, align 8
  %"%2" = alloca i32, align 4
  br label %bb0

bb0:                                              ; preds = %entry
  %0 = call i64* @map_new_int()
  store i64* %0, i64** %"%1", align 8
  br label %bb2

bb1:                                              ; No predecessors!
  br label %bb2

bb2:                                              ; preds = %bb1, %bb0
  ret void
}
```

Here we assign the returned value to `%0`. I think it will be more clear if we can assign it to temp value like %1_temp and store it in %1, WDYT?

2021-02-24 13:12 UTC, ruvi-d commented
> Here we assign the returned value to `%0`. I think it will be more clear if we can assign it to temp value like %1_temp and store it in %1, WDYT?

I am a bit torn about that. You are right that it would improve readability, but it is a redundant step that would likely get optimized out when we add LLVM IR optimization passes later on. 

@ayonam : any thoughts?

2021-02-24 14:45 UTC, KavinduZoysa commented
> > Here we assign the returned value to `%0`. I think it will be more clear if we can assign it to temp value like %1_temp and store it in %1, WDYT?
> 
> I am a bit torn about that. You are right that it would improve readability, but it is a redundant step that would likely get optimized out when we add LLVM IR optimization passes later on.
> 
> @ayonam : any thoughts?

Yes, redundancy point of view, I agree with you.

2021-02-25 03:59 UTC, KavinduZoysa approved these changes

2021-02-25 07:20 UTC, ruvi-d commented
Summary of open question to @ayonam 

1. There is currently no codegen logic to deinit (free) the Map object. Is there a recommended approach to call deinit for the local variables at least?
2. To hold the map pointer returned from Rust side, is there a preference between using *i8 or *i64 on the codegen side? 
3. When we are generating LLVM IR code, is it better to use more temp variables and be verbose? or is it better to use as few as possible and assign directly to local variables?

2021-02-26 23:32 UTC, ayonam requested changes

2021-02-26 23:32 UTC, ayonam commented on compiler/llvmMap.cpp
> +  assert(lhsVar->getVarKind() == LOCAL_VAR_KIND);
Why is this assertion?  Can't the LHS var be a global variable?

2021-02-26 23:32 UTC, ayonam commented on compiler/llvmMap.cpp
> +  LLVMValueRef lhsOpTempRef = funcObj->getLocalToTempVar(getLhsOperand());
I think you should check the scope of LHS operand and then either call this getLocalToTempVar() if it is a local variable or else do something like a GEP (Global Element Pointer).

2021-02-26 23:32 UTC, ayonam commented on compiler/llvmMap.cpp
> +  LLVMValueRef keyRef = funcObj->getLocalToTempVar(keyOp);
Ditto for the RHS op and the KEY op.

2021-02-26 23:32 UTC, ayonam commented on compiler/llvmMap.cpp
> +  pkg->addArrayFunctionRef("map_store_int", addedFuncRef);
This is fine for now.  But going forward, as we add different kinds of Maps with different data types, should we be having polymorphic functions on the Rust side or do we have different names for each data type?  If it is the former, then what should this function return?  Probably it should return nothing.  It should simply setup the types of each of the polymorphic functions and return void.

2021-02-26 23:32 UTC, ayonam commented on compiler/llvmStructure.cpp
> +    lhsOpRef = pkgObj->getGlobalVarRefUsingId(lhsName);
Here you are checking for both local as well as global var refs.  You need to do like this everywhere.

2021-02-26 23:32 UTC, ayonam commented on compiler/llvmStructure.cpp
> +    assert(false);
You should call llvm_unreachable() instead of assert(false)

2021-02-26 23:32 UTC, ayonam commented on compiler/llvmStructure.cpp
> +}
Again the same comment here regarding polymorphic functions on the Rust side to handle initialization of maps of different data types.

2021-02-26 23:32 UTC, ayonam commented on test/map/mapBasic.bal
> +// CHECK: length=1
Shouldn't there also be a check to see if the marks["jon"] is indeed 60 or not?

2021-02-28 14:38 UTC, ruvi-d commented on compiler/BIR.h
> -  INSTRUCTION_KIND_NEW_MAP,
There is no "new map" instruction as per the BIR spec listed here: https://github.com/ballerina-platform/ballerina-lang/blob/bd8e12ac24a70079247d1b178de888cb0e76a96a/docs/bir-spec/src/main/resources/kaitai/bir.ksy#L988

We get `new struct` instruction with a LHS value of type Map for new Maps

2021-02-28 14:44 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +    int memeberType = typeShapeCp->getTypeTag();
Thanks for spotting it. Will fix.

2021-02-28 14:47 UTC, ruvi-d commented on compiler/llvmFunctionGen.cpp
>      return LLVMPointerType(LLVMInt64Type(), 0);
Please see this question regarding this topic: https://github.com/ballerina-platform/nballerina/pull/102#issuecomment-785677115
We were not sure whether it is best to use a int-8 or int-64 pointer to hold the address returned from the Rust runtime.

2021-02-28 14:54 UTC, ruvi-d commented on compiler/BIR.h
> -  VarDecl *getLocalVar(int i) { return localVars[i]; }
We are not using them anymore

2021-02-28 14:57 UTC, ruvi-d commented on compiler/BIR.h
> +  LLVMValueRef getNewMapIntDeclaration(LLVMModuleRef &modRef, BIRPackage *pkg);
The BIR for new Map is actually a `new structure` with a LHS of type Map. So I am having to handle the new map Code gen from the StrutureIsn class. Hope that makes sense?

2021-02-28 14:59 UTC, ruvi-d commented on compiler/BIR.h
> +  }
Yes makes sense. Fill fix.

2021-02-28 15:25 UTC, ruvi-d commented on compiler/llvmMap.cpp
> +// new Map Instruction and Codegen logic are in the llvmStructure.cpp
There is no `new map` BIR instruction. What we are getting is a `new structure` instruction withe the RHS that has a Map type. That is why I am handling the codegen for new map as part of the new structure instruction class

2021-02-28 15:28 UTC, ruvi-d commented on compiler/llvmMap.cpp
> +
You are only supposed to add inline method definitions to the header right?

2021-02-28 15:29 UTC, ruvi-d commented on compiler/llvmMap.cpp
> +  assert(lhsVar->getVarKind() == LOCAL_VAR_KIND);
will check for global variables and get back.

2021-02-28 15:30 UTC, ruvi-d commented on compiler/llvmMap.cpp
> +  LLVMValueRef lhsOpTempRef = funcObj->getLocalToTempVar(getLhsOperand());
noted. will check with global variables

2021-02-28 15:31 UTC, ruvi-d commented on compiler/llvmMap.cpp
> +  LLVMValueRef keyRef = funcObj->getLocalToTempVar(keyOp);
noted. thanks

2021-02-28 15:32 UTC, ruvi-d commented on compiler/llvmStructure.cpp
> +    lhsOpRef = pkgObj->getGlobalVarRefUsingId(lhsName);
noted. thanks

2021-02-28 15:40 UTC, ruvi-d commented on test/map/mapBasic.bal
> +// CHECK: length=1
That will be handled as par of #128

2021-03-01 08:13 UTC, ruvi-d commented on compiler/llvmFunctionGen.cpp
>      return LLVMPointerType(LLVMInt64Type(), 0);
I've pushed a change to use int8* instead of int64*

2021-03-01 08:22 UTC, ruvi-d commented
Addressed the review comments from Ayonam. The discussion about why the new map instruction is handled instead the new Structure instruction is unresolved.

2021-03-01 19:39 UTC, ayonam commented
@ruvi-d   @KavinduZoysa 

Please find my replies inlined below:

> Summary of open question to @ayonam
> 
>     1. There is currently no codegen logic to deinit (free) the Map object. Is there a recommended approach to call deinit for the local variables at least?
> 

Local variables that are created as part of LLVM generated code will automatically get deallocated once the current function returns and we need not do anything about it.  For those that are created by the Rust side of things through an explicit allocation on the heap, we need to deallocate them explicitly (or through a memory manager / garbage collector).  So although these are local variables from the programmer's perspective, they are actually allocated by Rust on the heap.  

>     2. To hold the map pointer returned from Rust side, is there a preference between using *i8 or *i64 on the codegen side?

Actually since we treat that pointer as an opaque pointer, it is equivalent to void* in the C/C++ paradigm.  Now in LLVM there is no concept of a void pointer.  A void pointer is represented as an i8*.  So I think we should treat such map pointers as i8*.

> 
>     3. When we are generating LLVM IR code, is it better to use more temp variables and be verbose? or is it better to use as few as possible and assign directly to local variables?

Don't bother about the temp variables.  The optimizer downstream is going to straighten them out.  Currently we are not turning on the optimizer (by passing -O0) and hence you still see all those temps in the LLVM dump.  We are doing so, so that we can debug things more easily.  Once we reach certain level of maturity in our codegen, we will turn on the optimizer and then you should see most of these temps going away.

2021-03-02 02:45 UTC, ruvi-d commented
Noted.. Thanks for the answers Ayonam

2021-03-02 13:17 UTC, KavinduZoysa approved these changes

2021-03-03 10:27 UTC, uthaiyashankar approved these changes

2021-03-03 10:46 UTC, ayonam commented
> Addressed the review comments from Ayonam. The discussion about why the new map instruction is handled instead the new Structure instruction is unresolved.

@Ruvi, Do we have a resolution to this one as yet?  If yes, then this should be good to approve.  If not, then I'd prefer if you can open a separate Issue about this and we can discuss it there.

2021-03-03 10:51 UTC, ruvi-d commented
> > Addressed the review comments from Ayonam. The discussion about why the new map instruction is handled instead the new Structure instruction is unresolved.
> 
> @ruvi, Do we have a resolution to this one as yet? If yes, then this should be good to approve. If not, then I'd prefer if you can open a separate Issue about this and we can discuss it there.

No resolution yet. I've started a slack thread on it too here: https://ballerina-platform.slack.com/archives/C01LNSAHK18/p1614654420035700
Let's close this PR and I will create an Github issue to track it separately.

2021-03-03 11:05 UTC, ayonam approved these changes

2021-03-03 11:48 UTC, merged