Add support for Array Type Checker
ballerina-platform/nballerina pull request #105
Opened 2021-02-17 18:25 UTC by shubhamnarlawar

## Purpose
Checks whether array typecast is possible from source type to destination type.

Related discussion - https://github.com/ballerina-platform/nballerina/discussions/50

2021-02-17 18:26 UTC, shubhamnarlawar commented
Please review and suggest changes - @ruvi-d @manuranga

2021-02-17 18:26 UTC, shubhamnarlawar commented
This PR addresses issue #86.

2021-02-17 18:38 UTC, shubhamnarlawar commented
From issue - #86 

`Write wrapper function for is_same_type() to check whether original types of source and destination can be type casted.`

The original types are available in smart pointers. The original types - for example - int, char, any, etc is supposed to be checked before callling `is_same_type()`.

As discussed earlier, wrapper function is supposed to be implemented in rust. `A` represents array in `is_same_type()`. Probably I should take `a` for any data type in wrapper function.

Is wrapper function suggested to be implemented in rust or llvm side?

2021-02-18 03:19 UTC, ruvi-d commented
> From issue - #86
> 
> `Write wrapper function for is_same_type() to check whether original types of source and destination can be type casted.`
> 
> The original types are available in smart pointers. The original types - for example - int, char, any, etc is supposed to be checked before callling `is_same_type()`.
> 
> As discussed earlier, wrapper function is supposed to be implemented in rust. `A` represents array in `is_same_type()`. Probably I should take `a` for any data type in wrapper function.
> 
> Is wrapper function suggested to be implemented in rust or llvm side?

IMO, such decisions should be based on whether the check is at compile time or runtime. If the check needs to happen at compile time, the implementation should be on the C++/LLVM side. If it's a runtime check, then it should happen on the Rust side.

2021-02-18 03:59 UTC, manuranga commented
Hi @shubhamnarlawar ,
Is it possible to directly call the rust function from generated code, without using a wrapper ?

2021-02-18 04:10 UTC, ruvi-d requested changes
Please see review comments

2021-02-18 04:10 UTC, ruvi-d commented on runtime/src/lib.rs
> +    match source.chars().nth(0) {
Define these magic numbers for bit positions as constants.

2021-02-18 04:10 UTC, ruvi-d commented on runtime/src/lib.rs
> +    let total_bits: i32 = bits.parse().unwrap();
Need to handle unbounded Array sizes

2021-02-18 04:13 UTC, ruvi-d commented
@shubhamnarlawar other general review comments:

1. Shall we move the logic out of lib.rs and into separate modules? Let's try to keep lib.rs as thin as possible

2. Add some Rust unit tests for the new functions

3. Do we need to handle unbounded size arrays? I believe that on the BIR side unbounded is handled with a `-1` size. How are we handling that?

2021-02-18 07:33 UTC, shubhamnarlawar commented
> > From issue - #86
> > `Write wrapper function for is_same_type() to check whether original types of source and destination can be type casted.`
> > The original types are available in smart pointers. The original types - for example - int, char, any, etc is supposed to be checked before callling `is_same_type()`.
> > As discussed earlier, wrapper function is supposed to be implemented in rust. `A` represents array in `is_same_type()`. Probably I should take `a` for any data type in wrapper function.
> > Is wrapper function suggested to be implemented in rust or llvm side?
> 
> IMO, such decisions should be based on whether the check is at compile time or runtime. If the check needs to happen at compile time, the implementation should be on the C++/LLVM side. If it's a runtime check, then it should happen on the Rust side.

Got it. Thanks for the clarification.

2021-02-18 07:37 UTC, shubhamnarlawar commented
> @shubhamnarlawar other general review comments:
> 
>     1. Shall we move the logic out of lib.rs and into separate modules? Let's try to keep lib.rs as thin as possible
> 
>     2. Add some Rust unit tests for the new functions
> 
>     3. Do we need to handle unbounded size arrays? I believe that on the BIR side unbounded is handled with a `-1` size. How are we handling that?

1. Yes. How about a new file `typeChecker.rs`?
2. Sure. I will add unit tests at last in this PR itself after pushing above review changes.
3. Let me check and get back to you on unbounded size arrays.

2021-02-18 07:38 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +    match source.chars().nth(0) {
Can you elaborate a bit more in this suggestion?

Do you mean to use below snippet instead -

 `   let constant = source.chars().nth(0);`
`    match constant {`

2021-02-18 07:40 UTC, ruvi-d commented
> > > From issue - #86
> > > `Write wrapper function for is_same_type() to check whether original types of source and destination can be type casted.`
> > > The original types are available in smart pointers. The original types - for example - int, char, any, etc is supposed to be checked before callling `is_same_type()`.
> > > As discussed earlier, wrapper function is supposed to be implemented in rust. `A` represents array in `is_same_type()`. Probably I should take `a` for any data type in wrapper function.
> > > Is wrapper function suggested to be implemented in rust or llvm side?
> > 
> > 
> > IMO, such decisions should be based on whether the check is at compile time or runtime. If the check needs to happen at compile time, the implementation should be on the C++/LLVM side. If it's a runtime check, then it should happen on the Rust side.
> 
> Got it. Thanks for the clarification.

Let us know if there is a good reason to use Rust logic for compile time checks and then maybe we can take it case by case.

2021-02-18 07:41 UTC, ruvi-d commented
> 1. Yes. How about a new file `typeChecker.rs`?

I think it should be `type_checker.rs` inline with Rust naming conversions.

2021-02-18 07:51 UTC, ruvi-d commented on runtime/src/lib.rs
> +    match source.chars().nth(0) {
no.. I mean define the string indexes as constants like:
```
const BASE_TYPE_INDX: u32 = 0;
const ARRAY_MEMBER_TYPE_INDX: u32 = 1;
const ARRAY_SIZE_LSB_INDX: u32 = 2;
const ARRAY_SIZE_MSB_INDX: u32 = 3;
...
// Then use these constants when accessing the chars
match source.chars().nth(BASE_TYPE_INDX)
```
Hope that makes sense?

2021-02-18 07:52 UTC, shubhamnarlawar commented
> > > > From issue - #86
> > > > `Write wrapper function for is_same_type() to check whether original types of source and destination can be type casted.`
> > > > The original types are available in smart pointers. The original types - for example - int, char, any, etc is supposed to be checked before callling `is_same_type()`.
> > > > As discussed earlier, wrapper function is supposed to be implemented in rust. `A` represents array in `is_same_type()`. Probably I should take `a` for any data type in wrapper function.
> > > > Is wrapper function suggested to be implemented in rust or llvm side?
> > > 
> > > 
> > > IMO, such decisions should be based on whether the check is at compile time or runtime. If the check needs to happen at compile time, the implementation should be on the C++/LLVM side. If it's a runtime check, then it should happen on the Rust side.
> > 
> > 
> > Got it. Thanks for the clarification.
> 
> Let us know if there is a good reason to use Rust logic for compile time checks and then maybe we can take it case by case.

Sure.

 At this point, there is no need to write wrapper function for calling 'is_same_type()'.

2021-02-18 08:37 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +    match source.chars().nth(0) {
Yes. Makes sense. I have used `usize` instead of `u32` as match expects a `usize`-

`pub const BASE_TYPE_INDX: usize = 0;`
`pub const ARRAY_MEMBER_TYPE_INDX: usize = 1;`
`pub const ARRAY_SIZE_LSB_INDX: usize = 2;`
`pub const ARRAY_SIZE_MSB_INDX: usize = 3;`

I will push this snippet along with other changes.

2021-02-18 08:40 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +        _ => println!("Unsupported type"),
How about this?

_ => panic!("Unsupported type in mangled string"),

2021-02-18 08:56 UTC, ruvi-d commented on runtime/src/lib.rs
> +        _ => println!("Unsupported type"),
I'd return a [std::result::Result](https://doc.rust-lang.org/std/result/enum.Result.html) from the function. The lib.rs side can check the return and panic if required.

2021-02-19 18:45 UTC, shubhamnarlawar commented
> @shubhamnarlawar other general review comments:
> 
>     1. Shall we move the logic out of lib.rs and into separate modules? Let's try to keep lib.rs as thin as possible
> 
>     2. Add some Rust unit tests for the new functions
> 
>     3. Do we need to handle unbounded size arrays? I believe that on the BIR side unbounded is handled with a `-1` size. How are we handling that?

For point 3, we have not planned handling unbounded size arrays in this sprint. We need to discuss it in Monday's meeting - 

Some quick thoughts to discuss - 
`What happens when one typecast such an array to a type that has a fixed length?  What happens if the fixed length array is larger than the current length of the variable length array?  What happens if it is smaller?`

2021-02-21 14:49 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +    let dest_cstr: &CStr = unsafe { CStr::from_ptr(dest_type) };
Done.

2021-02-21 14:50 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +        Some('A') => priority = 16,
Done. Please check it!

2021-02-21 14:50 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +        _ => println!("Unsupported data structure"),
Sure. Done.

2021-02-21 14:50 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +        _ => println!("Unsupported type"),
Done.

2021-02-22 06:14 UTC, manuranga commented on runtime/src/lib.rs
> +        Some('C') | Some('B') => {
this should be descriptive.

2021-02-23 15:01 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +        Some('C') | Some('B') => {
I have added comment at top of this function- 

`/*`
 `* Computes size of the type`
 `* Type Notations -`
 `* C represents character`
 `* B represents boolean`
 `* F represents float`
 `* I represents integer`
 `* S represents string`
 `* X represents any*/`

Is using a macro suggested here ? Like - 

`macro_rules! Char { () => {'C'}; }`

and In the match case, it will be - `Some(Char!())`

WDYT?

2021-02-23 15:04 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +        Some('C') | Some('B') => {
@manuranga - In yesterday's call, you suggested to use enum. But here at some places, two entities require same value - 

for example - `Some('C') | Some('B')` - here both characer and boolean requires a value of `1`.

Can you share example to make it more descriptive? You mentioned that you have known in other languages in C++ to make this match case more descriptive. Can you please share here?

2021-02-23 18:30 UTC, manuranga commented on runtime/src/lib.rs
> +        Some('C') | Some('B') => {
Hi looks like rust doesn't support this out of the box yet https://github.com/rust-lang/rfcs/pull/3040
But it seems like there is a common way to do this : https://stackoverflow.com/a/28029279
Please try to use this approach

2021-02-24 16:08 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +        Some('C') | Some('B') => {
From above link - I can write enum as below - 

`enum TYPE_SIZE {`
`    CHAR = 1,`
`    INT = 8,`
`    STRING = 12,`
`    ANY = 16,`
`}`
`and so on`

but for boolean data type with size `1 byte`, it also need `1`
similarly, float needs `8`. Here we have repetitive values. How would enum works in this case?

2021-02-24 16:24 UTC, manuranga commented on runtime/src/lib.rs
> +        Some('C') | Some('B') => {
Hi, I am suggesting not to have unnamed constants like `C` and `X`. This is the same reason we use constants instead inlined numbers https://stackoverflow.com/a/47902.

I was not suggesting to have priorities be encoded into to enum.

2021-02-24 17:23 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +        Some('C') | Some('B') => {
Got it. I misinterpreted it.

How about using below constants instead of just `C` and `X`? - 

`pub const CHARACTER: char = 'C';`
`pub const BOOLEAN: char = 'B';`
`pub const INTEGER: char = 'I';`
`pub const FLOAT: char = 'F';`
`pub const STRING: char = 'S';`
`pub const ANY: char = 'X';`
`pub const ARRAY: char = 'A';`

2021-02-24 18:23 UTC, manuranga commented on runtime/src/lib.rs
> +            {
is this line formatted using `rustfmt` ? brace seems to be on the wrong line.

2021-02-25 04:30 UTC, manuranga commented on runtime/src/lib.rs
> +    let mut dest_type_size: Result<i32, &'static str> = Ok(0);
In Rust, it's a best practice to use `mut` minimally. If you can avoid it, it's better.

2021-02-25 13:11 UTC, manuranga commented on runtime/src/lib.rs
> + * X represents any*/
@shubhamnarlawar Please read https://ballerina.io/spec/lang/draft/v2020-12-17/#section_5.1.4
these are the type we need to support. We can start by selected subset, but there is no type called character.

2021-02-25 13:46 UTC, manuranga commented on runtime/src/lib.rs
> +    match source.chars().nth(0) {
It took some time, but I was able to come up with following code. Please do the research on rust language best practices in the future.
```rust
extern crate num;
extern crate num_derive;

use num::FromPrimitive;
use num_derive::FromPrimitive;

const ARRAY_MEMBER_TYPE_INDEX: usize = 2;

#[derive(Debug, PartialEq, FromPrimitive)]
#[repr(u32)]
enum BalType {
    Nil = 'N' as u32,
    Boolean = 'B' as u32,
    Int = 'I' as u32,
    Float = 'F' as u32,
    Decimal = 'D' as u32,
    String = 'S' as u32,
    Array = 'A' as u32,
    Any = 'X' as u32,
}

pub fn type_size(type_string: &str) -> i32 {
    let type_char = type_string.chars().nth(ARRAY_MEMBER_TYPE_INDEX)
                                      .unwrap_or_else(|| panic!("illegle type discripor '{}', wrong length", type_string));
    let bal_type = FromPrimitive::from_u32(type_char as u32)
                                      .unwrap_or_else(|| panic!("illegle type tag '{}' in type discripor '{}'", type_char, type_string));
    match bal_type {
        BalType::Boolean => { 1 }
        BalType::Int | BalType::Float => { 8 }
        BalType::String => { 12 }
        BalType::Any => { 16 }
        _ => { unimplemented!("type_size for '{:?}'", bal_type) }
    }
}
```

Cargo.toml
```toml
[dependencies]
num = "0.3"
num-traits = "0.2"
num-derive = "0.3"
```

2021-02-28 17:12 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +            {
I am using `cargo-fmt`. I tried with `rustfmt` but getting same result. Let me reformat it once again!

2021-02-28 17:12 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +    let mut dest_type_size: Result<i32, &'static str> = Ok(0);
Got it! Sure

2021-02-28 17:15 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +    match source.chars().nth(0) {
Thank you for the snippet! Sure. I will follow it in next tasks!

Let me modify other functions to follow above points!

2021-02-28 17:17 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> + * X represents any*/
Got it. From the above enum you wrote, we can treat it as a subset!

2021-03-01 15:42 UTC, ruvi-d commented
@shubhamnarlawar remember to create a separate `type_checker.rs` file similar to how we created a new file for the map implementation.

2021-03-03 08:43 UTC, shubhamnarlawar commented
> @shubhamnarlawar remember to create a separate `type_checker.rs` file similar to how we created a new file for the map implementation.

I have moved all functions except `is_same_type()` and tests to `type_checker.rs`. Please check it!

2021-03-03 08:55 UTC, shubhamnarlawar commented
Is this PR ready to merge now?

2021-03-03 12:50 UTC, ruvi-d commented
> Is this PR ready to merge now?

You will have to fix the conflicts with master. When the PR is ready to review, you can mark my request for change complete and request for review again.

2021-03-03 14:35 UTC, shubhamnarlawar commented
> > Is this PR ready to merge now?
> 
> You will have to fix the conflicts with master. When the PR is ready to review, you can mark my request for change complete and request for review again.

I have resolved the conflict with master. No merge conflict now!
I have re-requested you for a review.

2021-03-04 08:15 UTC, shubhamnarlawar commented
@ruvi-d - Please give suggestions if any on latest changes pushed.

2021-03-04 08:23 UTC, ruvi-d requested changes
Much better now with the Rust unit tests.
Just one more suggestion. Move the is_same_type function to the type_checker module. Change it's input args to take Rust strings. On the lib.rs, only do the String construction and directly pass it to type_checker module. Similar to how the Map implementation has been done. 
The idea here is to keep lib.rs as thin as possible, doing only the data type conversions. The actual logic will be kept on a separate, reusable(independent) Rust module.

2021-03-04 09:55 UTC, shubhamnarlawar commented
> Much better now with the Rust unit tests.
> Just one more suggestion. Move the is_same_type function to the type_checker module. Change it's input args to take Rust strings. On the lib.rs, only do the String construction and directly pass it to type_checker module. Similar to how the Map implementation has been done.
> The idea here is to keep lib.rs as thin as possible, doing only the data type conversions. The actual logic will be kept on a separate, reusable(independent) Rust module.

Done. Please check it.

I have moved logic of `is_same_type()` into a separate function called `same_type()` in `type_checker.rs` Now, the code is much cleaner.

2021-03-04 12:08 UTC, ruvi-d approved these changes
I am OK to merge. Best if @manuranga can double check the Rust lang specific stuff.

2021-03-04 12:30 UTC, manuranga commented
Still little bit unsure about the algo, but we'll catch if there is any issues with lit tests later.

Looks good to merge.

2021-03-04 14:43 UTC, shubhamnarlawar commented
Sounds good. Can you mark it as review complete and approve?

2021-03-05 04:22 UTC, Kishanthan approved these changes

2021-03-05 04:23 UTC, merged

2021-06-21 13:30 UTC, manuranga commented
@gimantha please send a pr to nBallerina updating comments with issue numbers when done.