Integrate cells into table type
ballerina-platform/nballerina pull request #1097
Opened 2022-10-13 06:42 UTC by lochana-chathura

## Purpose
$subject.

Fixes #1095

2022-10-20 03:40 UTC, jclark requested changes
Can you please rebase this on top of the list one?

2022-10-20 03:41 UTC, jclark commented on compiler/modules/types/table.bal
> +    CellSemType cellType = cellContaining(env, listType);
Don't we want a cell inside a list not a list inside a cell?

2022-10-24 02:04 UTC, jclark requested changes

2022-10-24 02:04 UTC, jclark commented on compiler/modules/types/table.bal
> +    isEmpty: listSubtypeIsEmpty
I thought we decided this wouldn't work, because the TOP would be wrong.  We need it to be `map<any|error>[]` not `(any|error)[]`.

2022-10-24 07:04 UTC, lochana-chathura commented
@james PR is ready to review again.

2022-10-28 03:16 UTC, jclark approved these changes

2022-10-28 03:16 UTC, jclark commented on compiler/modules/types/cell.bal
>      SubtypeData subtypeData = bddSubtypeUnion(t1, t2);
No need to make this a local variable.

2022-10-28 03:16 UTC, merged