Add the nil type support
ballerina-platform/nballerina pull request #111
Opened 2021-02-18 17:49 UTC by KavinduZoysa

## Purpose
$subject

Fixes #94

For following basic program, [LLVM IR](https://github.com/KavinduZoysa/llvm/blob/assembly/main.ll) and [assembly file](https://github.com/KavinduZoysa/llvm/blob/assembly/assembly_file) are uploaded.

```
public function main() {
    () s = foo();
}

function foo() returns () {
    return ();
}
```

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
Create a global variable for nul value and change the places where constLoad, return, functionGen.
`@bal_nil_value = global i8* null, align 8`

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
ubuntu 16.04
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-02-19 05:54 UTC, ruvi-d requested changes
Please see rview comments

2021-02-19 05:54 UTC, ruvi-d commented on compiler/llvmFunctionGen.cpp
> +      return LLVMVoidType();
The special casing of `_bal_result` at line num:71-83, should move inside this block right? otherwise if there is a `_bal_result` defined all functions that return void will return int instead.

2021-02-19 05:54 UTC, ruvi-d commented on compiler/llvmConstantLoadInsn.cpp
> +      if (getFunction() -> getName() == "main" && lhsOp -> getVarDecl() -> getVarName() == "%0") {
make `main` a constexpr char just like `BAL_NIL_VALUE`.
also formatting (spacing) is off here .

2021-02-19 05:54 UTC, ruvi-d commented on compiler/llvmFunctionGen.cpp
> +    return LLVMPointerType(LLVMInt8Type(), 0);
let's use `getLLVMTypeRefOfType()` function to get the LLVMTypeRef instead of replicating the switch case here again

2021-02-19 05:54 UTC, ruvi-d commented on compiler/llvmConstantLoadInsn.cpp
> +      string tempName = BAL_NIL_VALUE + "_temp";
What if there are more than one nil type variables in the function? this would then create two constLoad instructions with the same tempName. lhsOp name + _temp would be better right?

2021-02-19 05:54 UTC, ruvi-d commented on compiler/llvmPackageGen.cpp
> +  globalVarRefs.insert({BAL_NIL_VALUE, globVarRef});
This might be a problem some time later when we are going link multiple translation units because of the `GlobalValue::ExternalLinkage` used here. Better change it to internal linkage.

2021-02-19 05:54 UTC, ruvi-d commented on compiler/llvmPackageGen.cpp
> +                                                                                                              birFunc->getName());
Update formatting

2021-02-19 05:54 UTC, ruvi-d commented on compiler/llvmReturnInsn.cpp
> -  if (funcObj->getName() == "main" && returnVarDecl) {
Prefer early exits pattern to prevent multiple nested if/else blocks. Ref: https://llvm.org/docs/CodingStandards.html#use-early-exits-and-continue-to-simplify-code

2021-02-19 05:54 UTC, ruvi-d commented on test/types/nil/nil.bal
> +}
Not using `foo()`?

2021-02-20 04:09 UTC, KavinduZoysa commented on compiler/llvmFunctionGen.cpp
> +      return LLVMVoidType();
If `_bal_result` is there, the logic at L71-L83 changes the target type to `int`. Therefore it returns the correct type.

2021-02-20 07:17 UTC, KavinduZoysa commented on compiler/BIR.h
> +
After changing this I got an error when the string is concatenated as `BAL_NIL_VALUE + "_temp";`. Then I used `strcpy`, but still getting an error because it is a constexpr. Any suggestions to fix this?

2021-02-20 07:17 UTC, KavinduZoysa commented on compiler/llvmConstantLoadInsn.cpp
> +      if (getFunction() -> getName() == "main" && lhsOp -> getVarDecl() -> getVarName() == "%0") {
Fixed.

2021-02-20 07:17 UTC, KavinduZoysa commented on compiler/llvmFunctionGen.cpp
> +    return LLVMPointerType(LLVMInt8Type(), 0);
We need to make the `main` function a special case right? In `getLLVMTypeRefOfType()` we are not doing such a thing and default cases are different.

2021-02-20 07:17 UTC, KavinduZoysa commented on compiler/llvmConstantLoadInsn.cpp
> +      string tempName = BAL_NIL_VALUE + "_temp";
Yes, fixed

2021-02-20 07:17 UTC, KavinduZoysa commented on compiler/llvmPackageGen.cpp
> +  globalVarRefs.insert({BAL_NIL_VALUE, globVarRef});
Fixed

2021-02-20 07:17 UTC, KavinduZoysa commented on compiler/llvmReturnInsn.cpp
> -  if (funcObj->getName() == "main" && returnVarDecl) {
Fixed

2021-02-20 07:17 UTC, KavinduZoysa commented on test/types/nil/nil.bal
> +}
I did not get this comment.

2021-02-20 08:16 UTC, KavinduZoysa commented on compiler/llvmPackageGen.cpp
> +                                                                                                              birFunc->getName());
Fixed

2021-02-22 02:54 UTC, ruvi-d commented on compiler/BIR.h
> +
I'd create a new string from BAL_NIL_VALUE to concat, like `std::string bal_nil(BAL_NIL_VALUE); //bal_nil + "_temp"`

2021-02-22 06:27 UTC, manuranga commented on compiler/llvmPackageGen.cpp
> +  gVar->setAlignment(Align(8));
Please research and see if the alignment is needed, or can llvm figure it out automatically .

2021-02-22 09:54 UTC, ruvi-d commented on compiler/llvmFunctionGen.cpp
> +      return LLVMVoidType();
I mean for an example like this:
```
int _bal_result = 0;
public function main() {
  () nilVal = bar();
}

function foo() {
  () nilVal = ();
}
```
foo()'s return would incorrectly change to int type right?

2021-02-22 10:00 UTC, ruvi-d commented on compiler/llvmFunctionGen.cpp
> +    return LLVMPointerType(LLVMInt8Type(), 0);
I'd rather we use getLLVMTypeRefOfType() and only override with `(funcName == "main")` for `TYPE_TAG_NIL`. Otherwise we would be duplicating the logic and might miss to update one in the future.

2021-02-22 19:56 UTC, KavinduZoysa commented on compiler/llvmPackageGen.cpp
> +  gVar->setAlignment(Align(8));
I think we do not need that, please refer https://llvm.org/docs/LangRef.html#id1694

2021-02-22 20:01 UTC, KavinduZoysa commented on compiler/BIR.h
> +
Thank you, fixed it.

2021-02-22 20:01 UTC, KavinduZoysa commented on compiler/llvmFunctionGen.cpp
> +      return LLVMVoidType();
yes, fixed.

2021-02-22 20:09 UTC, KavinduZoysa commented on compiler/llvmFunctionGen.cpp
> +    return LLVMPointerType(LLVMInt8Type(), 0);
I am still confused about how to use`getLLVMTypeRefOfType`. 
Will it work in below case?
```public function main() {
  () nilVal = bar();
}```

Also in both methods, default cases are different.

2021-02-24 03:27 UTC, ruvi-d commented on compiler/llvmFunctionGen.cpp
> +    return LLVMPointerType(LLVMInt8Type(), 0);
how about some thing like this
```
  if(typeTag != TYPE_TAG_NIL)
    return getLLVMTypeRefOfType(vDecl->getTypeDecl());
  if (funcName == "main") {
    return LLVMVoidType();
  }
  return LLVMPointerType(LLVMInt8Type(), 0);
```
that is without the `_bal_result` logic

2021-02-24 03:31 UTC, ruvi-d commented on test/types/nil/nil.bal
> +}
sorry i missed your reply here.
I meant that you are defining the foo() function here, but because it is not being used. So the codegen might be incorrect but the test will still pass. Shall we at least call it from the main function?

2021-02-24 17:12 UTC, KavinduZoysa commented on test/types/nil/nil.bal
> +}
Yes, changed it.

2021-02-24 17:13 UTC, KavinduZoysa commented on compiler/llvmFunctionGen.cpp
> +    return LLVMPointerType(LLVMInt8Type(), 0);
I have changed it in a different way, could you please check.

2021-02-25 05:13 UTC, ruvi-d approved these changes
Good to merge

2021-02-25 23:12 UTC, ayonam requested changes

2021-02-25 23:12 UTC, ayonam commented on compiler/llvmFunctionGen.cpp
> +    }
Why would you want to return an i8* as the return type for any function that is not main but returns nil?  Why not the same as what we do for main, i.e., the global NIL value?  Do we expect to do anything with this nil value?  If not, then it shouldn't matter if multiple functions point to the same value as their return value, right?

@manuranga what do you think?

2021-02-28 15:37 UTC, KavinduZoysa commented on compiler/BIR.h
> +  LLVMTypeRef getLLVMFuncRetTypeRefOfType(VarDecl *vDecl, string funcName);
Yes Ayonam, we don't need that, fixed it.

2021-02-28 15:38 UTC, KavinduZoysa commented on compiler/llvmConstantLoadInsn.cpp
> +      constRef = LLVMBuildLoad(builder, constTempRef, tempName.c_str());
`constRef` is stored here, https://github.com/ballerina-platform/nballerina/blob/976d306f0dfac18f7a0497b7c88efea37eea831f/compiler/llvmConstantLoadInsn.cpp#L85

This is the thing that was meant in this comment?

2021-02-28 15:48 UTC, KavinduZoysa commented on compiler/llvmReturnInsn.cpp
> +      return;
That is correct Ayonam, this check is redundant, therefore removed it.

2021-03-01 04:00 UTC, KavinduZoysa commented on compiler/llvmFunctionGen.cpp
> +    }
[Ballerina spec](https://htmlpreview.github.io/?https://raw.githubusercontent.com/ballerina-platform/ballerina-spec/master/lang/spec.html) says `An empty return-type-descriptor is equivalent to returns ()`. Also we have discussed the same in GitHub issue https://github.com/ballerina-platform/nballerina/issues/94#issuecomment-781046163.

Therefore all functions(except main) which do not return, implemented as returning ().

2021-03-01 04:19 UTC, KavinduZoysa commented on test/types/nil/nil.bal
> +}
Added a new function

2021-03-01 04:31 UTC, KavinduZoysa commented on compiler/llvmReturnInsn.cpp
> +    builder, funcObj->getLocalVarRefUsingId("%0"), "retrun_temp");
We do not have proper documentation for that, but it is kind of a convention in the language. The return value is represented  using `%0`, in the .ll file it becomes `%"%0"`  @manuranga please correct me if I am wrong.

2021-03-01 08:41 UTC, ruvi-d commented on compiler/llvmConstantLoadInsn.cpp
> +      }
Kavindu, sounds like we will have to use a function like BIRFunction->getReturnVar() to get the return variable and compare it with your lhs. Instead of assuming that the return variable is %0.

2021-03-01 08:50 UTC, ruvi-d commented on compiler/llvmReturnInsn.cpp
> +    lhsRef = getPkgAddress()->getGlobalVarRefUsingId(returnVarDecl->getVarName());
We are setting the `lhsRef` from the `getLocalVarRefUsingId` function and then immediately reassigning it with the return from `getGlobalVarRefUsingId`? Are we missing a `if(lhsRef)` before line 43?

2021-03-03 06:24 UTC, KavinduZoysa commented on compiler/llvmConstantLoadInsn.cpp
> +      }
Changed

2021-03-03 06:24 UTC, KavinduZoysa commented on compiler/llvmReturnInsn.cpp
> +    lhsRef = getPkgAddress()->getGlobalVarRefUsingId(returnVarDecl->getVarName());
Yes, fixed.

2021-03-04 05:23 UTC, KavinduZoysa commented on compiler/llvmReturnInsn.cpp
> +    builder, funcObj->getLocalVarRefUsingId("%0"), "retrun_temp");
This is changed to use `getReturnVar()` instead of `%0`

2021-03-04 08:31 UTC, ruvi-d approved these changes
Good to merge

2021-03-04 09:49 UTC, ayonam commented on compiler/llvmConstantLoadInsn.cpp
> +      }
How do I see the changed code here?  I don't see any call to getReturnVar().

2021-03-04 09:50 UTC, ayonam commented on compiler/llvmConstantLoadInsn.cpp
> +      constRef = LLVMBuildLoad(builder, constTempRef, tempName.c_str());
Yes, this is fine.  Sorry, I missed that.

2021-03-04 09:52 UTC, ayonam commented on compiler/llvmReturnInsn.cpp
> +    builder, funcObj->getLocalVarRefUsingId("%0"), "retrun_temp");
Again I can't see the changes made.  Also, have we changed that "retrun_temp" to "return_temp"?  Or may be "return_val_temp" or "retval_temp" is a more apt name.

2021-03-04 15:02 UTC, KavinduZoysa commented on compiler/llvmReturnInsn.cpp
> +    builder, funcObj->getLocalVarRefUsingId("%0"), "retrun_temp");
@ayonam, please go to the list of `Files Changed` navigate to the file. The new change will not appear here.

2021-03-04 15:02 UTC, KavinduZoysa commented on compiler/llvmConstantLoadInsn.cpp
> +      }
@ayonam, please go to the list of `Files Changed` navigate to the file. The new change will not appear here.

2021-03-04 18:44 UTC, ayonam commented on compiler/llvmFunctionGen.cpp
> +    }
But for main() we are returning the global NIL value, right?  So we should do the same for these functions as well.  Why are we returning an i8*?

2021-03-04 18:47 UTC, ayonam commented on compiler/llvmConstantLoadInsn.cpp
> +      }
Okay.  Got it.  Thanks.

2021-03-04 19:08 UTC, KavinduZoysa commented on compiler/llvmFunctionGen.cpp
> +    }
In the main function, we are returning void, because we have to wrap ballerina main with native main https://github.com/ballerina-platform/nballerina/issues/94#issuecomment-781080663. Here we are returning the type of global nil value which is i8*. @ayonam, as I understood you are asking the reason to return nil for all functions except main right?

2021-03-04 20:09 UTC, ayonam commented on compiler/llvmFunctionGen.cpp
> +    }
Okay, I got it, but still this code does not handle the case where a user wants to return a value from main() through the _bal_result global variable.  I think the logic of the deleted lines 72 to 81 needs to be implemented here.

2021-03-04 20:13 UTC, ayonam commented on compiler/llvmFunctionGen.cpp
> +    }
Sorry, didn't notice. That code is there right below this comment.

2021-03-04 20:15 UTC, ayonam approved these changes

2021-03-05 04:27 UTC, Kishanthan reviewed
The sources (both Ballerina and cpp) aren't formatted according to the convention

2021-03-05 11:14 UTC, Kishanthan approved these changes

2021-03-05 11:14 UTC, merged