Make `Field` type representation more obvious
ballerina-platform/nballerina pull request #1155
Opened 2023-01-18 05:21 UTC by lochana-chathura

## Purpose
$subject.

Fixes #1154

2023-01-19 02:45 UTC, jclark requested changes

2023-01-19 02:45 UTC, jclark commented on compiler/modules/types/mapping.bal
> +    SemType fieldTy;
It's not `fieldName` so why is it `fieldTy`? Just `ty` is enough.

2023-01-26 04:34 UTC, manuranga commented on compiler/modules/types/mapping.bal
> +    CellField[] cellFields = from Field f in fields select [f.name, cellContaining(env, f.ty, f.ro ? CELL_MUT_NONE : mut)];
you may
```suggestion
    CellField[] cellFields = from var { name, ty, ro } in fields select [name, cellContaining(env, ty, ro ? CELL_MUT_NONE : mut)];
```

2023-01-26 05:04 UTC, jclark requested changes

2023-01-26 05:04 UTC, jclark commented on compiler/tests/propositionGenerator.bal
> +        subFields.push({ name:label, index:subtypes[i] });
Space after colon

2023-02-02 05:07 UTC, jclark approved these changes

2023-02-02 05:07 UTC, merged