Port ./test/functions LIT tests to make use of runtime functions
ballerina-platform/nballerina pull request #120
Opened 2021-02-24 17:46 UTC by shubhamnarlawar

## Purpose
The PR ports current LIT unit tests to make use of runtime functions.

2021-02-24 17:56 UTC, shubhamnarlawar commented
This PR resolve issues - #60 and #65

2021-02-24 17:58 UTC, shubhamnarlawar commented
Ported ./test/functions tests successfully to use runtime functions.

To port remaining tests -
1. casting
2. control_flow
3. operations
4. string
5. array

2021-02-25 08:17 UTC, ruvi-d requested changes
All non ported tests are failing. Please address them.

2021-02-25 08:17 UTC, ruvi-d commented on test/testRunScript.sh
> +echo RETVAL=$(./$filename.out)
This breaks all the non ported tests. `echo RETVAL=$(./$filename.out)` returns only `RETVAL=` for test bals that use `_bal_result`. All tests must pass for PRs since we have enabled the checks in Github.

2021-02-25 08:17 UTC, ruvi-d commented on test/testRunScript.sh
> -fi
Without deleting this block, lets comment it out and say that we are ignoring Ballerina compiler errors due to the use of undefined external functions for print routines.

2021-03-01 05:14 UTC, shubhamnarlawar commented on test/testRunScript.sh
> -fi
Got it.

2021-03-01 05:15 UTC, shubhamnarlawar commented on test/testRunScript.sh
> +echo RETVAL=$(./$filename.out)
Yes. The PR is not yet complete. Some tests are remaining to port.

2021-03-01 05:15 UTC, shubhamnarlawar commented on compiler/BIR.h
> +
I will push this chanhe along with other changes!

2021-03-03 14:39 UTC, shubhamnarlawar commented
Some of non ported tests are failing with below message - 

`nballerinacc: /home/s/last/nballerina/compiler/BIRReader.cpp:133: bool` `ConstantPoolSet::getBooleanCp(uint32_t): Assertion `poolEntry->getTag() ==` `ConstantPoolEntry::tagEnum::TAG_ENUM_CP_ENTRY_BOOLEAN' failed.`
`Aborted (core dumped)`

I am getting `String` type tag for a boolean. I will create an issue for this!

2021-03-03 15:38 UTC, ruvi-d commented
> Some of non ported tests are failing with below message -
> 
> `nballerinacc: /home/s/last/nballerina/compiler/BIRReader.cpp:133: bool` `ConstantPoolSet::getBooleanCp(uint32_t): Assertion `poolEntry->getTag() ==` `ConstantPoolEntry::tagEnum::TAG_ENUM_CP_ENTRY_BOOLEAN' failed.` `Aborted (core dumped)`
> 
> I am getting `String` type tag for a boolean. I will create an issue for this!

Are these tests ones that used to pass before this PR?

2021-03-03 16:56 UTC, shubhamnarlawar commented
> > Some of non ported tests are failing with below message -
> > `nballerinacc: /home/s/last/nballerina/compiler/BIRReader.cpp:133: bool` `ConstantPoolSet::getBooleanCp(uint32_t): Assertion `poolEntry->getTag() ==` `ConstantPoolEntry::tagEnum::TAG_ENUM_CP_ENTRY_BOOLEAN' failed.` `Aborted (core dumped)`
> > I am getting `String` type tag for a boolean. I will create an issue for this!
> 
> Are these tests ones that used to pass before this PR?

Yes.

2021-03-04 02:38 UTC, ruvi-d commented
> > > Some of non ported tests are failing with below message -
> > > `nballerinacc: /home/s/last/nballerina/compiler/BIRReader.cpp:133: bool` `ConstantPoolSet::getBooleanCp(uint32_t): Assertion `poolEntry->getTag() ==` `ConstantPoolEntry::tagEnum::TAG_ENUM_CP_ENTRY_BOOLEAN' failed.` `Aborted (core dumped)`I am getting`String` type tag for a boolean. I will create an issue for this!
> > 
> > 
> > Are these tests ones that used to pass before this PR?
> 
> Yes.

Sounds like a regression. I don't think it's a good idea to introduce a regression with a new PR and then create a new issue to fix old functionality that was broken. 
That is unless you have a good reason?

2021-03-04 05:05 UTC, shubhamnarlawar commented
> > > > Some of non ported tests are failing with below message -
> > > > `nballerinacc: /home/s/last/nballerina/compiler/BIRReader.cpp:133: bool` `ConstantPoolSet::getBooleanCp(uint32_t): Assertion `poolEntry->getTag() ==` `ConstantPoolEntry::tagEnum::TAG_ENUM_CP_ENTRY_BOOLEAN' failed.` `Aborted (core dumped)`I am getting`String` type tag for a boolean. I will create an issue for this!
> > > 
> > > 
> > > Are these tests ones that used to pass before this PR?
> > 
> > 
> > Yes.
> 
> Sounds like a regression. I don't think it's a good idea to introduce a regression with a new PR and then create a new issue to fix old functionality that was broken.
> That is unless you have a good reason?

Correct. Let me nail down the cause of issue. This seems something introduced by this PR.

2021-03-05 13:34 UTC, shubhamnarlawar commented
This PR causes a regression. Hence, I have opened a new PR #150 to address the same functionality.

2021-03-05 13:35 UTC, shubhamnarlawar commented
Closing this PR.

2021-03-05 13:35 UTC, closed without merging