Added support for Create type strings for array/boolean/int/float types.
ballerina-platform/nballerina pull request #132
Opened 2021-02-28 16:18 UTC by ramakotareddy

## Purpose
-> Added support for Create type strings for array/boolean/int/float types #87 .
-> Changed related to Migrate array cast to use generated type string #88 . 

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-03-01 16:57 UTC, ruvi-d requested changes
Please respond to the review comments as soon as possible

2021-03-01 16:57 UTC, ruvi-d commented on compiler/llvmArrayTypeInsn.cpp
>      lhsOpRef = pkgObj->getGlobalVarRefUsingId(lhsName);
The lhs generated type is `i32` for arrays. as in 
```
%"%0" = alloca i32, align 4
 %0 = call i32 @new_int_array(i32 %"%3_temp")
```
Shouldn't %0 be of type `i8*` to capture the opaque pointer returned from the Rust runtime?

2021-03-01 16:57 UTC, ruvi-d commented on compiler/llvmTypeCastInsn.cpp
> +                                               BIRFunction *funcObj) {
`funcObj` is not required?

2021-03-01 16:57 UTC, ruvi-d commented on compiler/llvmTypeCastInsn.cpp
> +  switch (typeTag) {
Can you point to the tests that cover these switch cases?

2021-03-01 16:57 UTC, ruvi-d commented on compiler/llvmTypeCastInsn.cpp
> +char const *TypeCastInsn::typeStringMangleName(LLVMValueRef typeVal,
Isn't it dangerous to return a pointer from within a function stack?

2021-03-02 05:43 UTC, ramakotareddy commented
Thanks for your comments Ruvi. I will fix.

2021-03-02 06:29 UTC, ramakotareddy commented on compiler/BIR.h
> +                LLVMModuleRef &modRef);
Fixed

2021-03-02 06:29 UTC, ramakotareddy commented on compiler/BIR.h
> +                                BIRFunction *funcObj);
Fixed

2021-03-02 06:30 UTC, ramakotareddy commented on compiler/llvmFunctionGen.cpp
> +  ;
Fixed

2021-03-02 06:32 UTC, ramakotareddy commented on compiler/llvmFunctionGen.cpp
> +  // In IfBB we are doing casing and from ElseBB Aborting.
Splitted this logic into separate function.

2021-03-02 09:16 UTC, ramakotareddy commented on compiler/llvmFunctionGen.cpp
> +  LLVMValueRef addedFuncRef = pkgObj->getFunctionRefBasedOnName("abort");
@ruvi-d , here 'abort' string we are using to get the FunctionRef from Map like "getFunctionRefBasedOnName("new_int_array")"  and "getFunctionRefBasedOnName("map_store_int")".
Can you please give more details on magic string here.

2021-03-02 09:16 UTC, ramakotareddy commented on compiler/llvmFunctionGen.cpp
> +  }
Fixed

2021-03-02 09:21 UTC, ramakotareddy commented on compiler/llvmTypeCastInsn.cpp
> +  switch (typeTag) {
anyTypeParam.bal
 boolToAnyTypeCast.bal
 floatTypecast.bal.skip
 multipleAnyTypeParams.bal
 stringTypeCast.bal

Above tests (inside test/casting dir) will cover these switch cases.

2021-03-02 10:01 UTC, ramakotareddy commented on compiler/llvmTypeCastInsn.cpp
> +                                               BIRFunction *funcObj) {
Removed funcObj

2021-03-02 10:02 UTC, ramakotareddy commented on compiler/llvmTypeCastInsn.cpp
> +                                               BIRFunction *funcObj) {
Fixed

2021-03-02 12:21 UTC, ruvi-d commented on compiler/llvmFunctionGen.cpp
> +  LLVMValueRef addedFuncRef = pkgObj->getFunctionRefBasedOnName("abort");
Please refer this: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-magic

2021-03-02 16:29 UTC, ramakotareddy commented on compiler/llvmPackageGen.cpp
> +      *unwrap(modRef), unwrap(charPtrType), false, GlobalValue::ExternalLinkage,
Changed to InternalLinkage.

2021-03-03 03:23 UTC, KavinduZoysa commented on compiler/BIR.h
> +  LLVMValueRef getIsSameTypeDeclaration (LLVMModuleRef &modRef,
There is a space between function name and (. Please check other places too.

2021-03-03 03:30 UTC, KavinduZoysa commented on test/array/simpleArrayDeclaration.bal
> +// CHECK: RETVAL=1
Shall we add an example like this, 
```
public function main() {
	int[] a = [5];
	any x = 2;
	a[0] = <int>x;
}
```

2021-03-03 03:34 UTC, KavinduZoysa commented on compiler/llvmTypeCastInsn.cpp
> +          LLVMBuildSExt(builder, lastTypeLoad, LLVMInt64Type(), "");
@ramakotareddy , could you please explain the reason to do this, just for my knowledge.

2021-03-03 03:34 UTC, KavinduZoysa commented on compiler/llvmTypeCastInsn.cpp
> +          LLVMBuildSExt(builder, lastTypeLoad, LLVMInt64Type(), "");
@ramakotareddy , could you please explain the reason to do this, just for my knowledge.

2021-03-03 05:22 UTC, ramakotareddy commented on test/array/simpleArrayDeclaration.bal
> +// CHECK: RETVAL=1
Added inside test/array directory. test case name is "anyTypeVarAssignToArray.bal".

2021-03-03 05:25 UTC, ramakotareddy commented on compiler/BIR.h
> +  LLVMValueRef getIsSameTypeDeclaration (LLVMModuleRef &modRef,
Fixed

2021-03-04 05:49 UTC, Kishanthan commented on compiler/llvmFunctionGen.cpp
> +      if (callInst) {
Inverse this if and continue ?

2021-03-04 05:51 UTC, Kishanthan commented on test/array/anyTypeVarAssignToArray.bal
> +// RUN: JAVA_HOME=%java_path %testRunScript %s %nballerinacc | filecheck %s
Format all the Ballerina source files.

2021-03-04 05:53 UTC, Kishanthan commented on compiler/llvmTypeCastInsn.cpp
> +LLVMValueRef TypeCastInsn::getIsSameTypeDeclaration(LLVMModuleRef &modRef,
All new additions in cpp files have to be formatted properly.

2021-03-04 16:31 UTC, ramakotareddy commented on compiler/llvmFunctionGen.cpp
> +  LLVMValueRef addedFuncRef = pkgObj->getFunctionRefBasedOnName("abort");
Fixed

2021-03-04 16:32 UTC, ramakotareddy commented on compiler/llvmFunctionGen.cpp
> +          unwrap(elseLLVMBB)
Fixed

2021-03-04 16:32 UTC, ramakotareddy commented on compiler/llvmPackageGen.cpp
> +  string charName = "__string_table_ptr";
Fixed

2021-03-05 04:41 UTC, ramakotareddy commented on compiler/llvmArrayTypeInsn.cpp
>      lhsOpRef = pkgObj->getGlobalVarRefUsingId(lhsName);
Fixed

2021-03-06 00:44 UTC, ramakotareddy commented on compiler/llvmTypeCastInsn.cpp
> +LLVMValueRef TypeCastInsn::getIsSameTypeDeclaration(LLVMModuleRef &modRef,
Fixed

2021-03-06 00:44 UTC, ramakotareddy commented on compiler/llvmFunctionGen.cpp
> +      if (callInst) {
Fixed

2021-03-06 00:44 UTC, ramakotareddy commented on compiler/llvmTypeCastInsn.cpp
> +char const *TypeCastInsn::typeStringMangleName(LLVMValueRef typeVal,
Fixed

2021-03-07 15:42 UTC, ramakotareddy commented on test/array/anyTypeVarAssignToArray.bal
> +// RUN: JAVA_HOME=%java_path %testRunScript %s %nballerinacc | filecheck %s
Formatted.

2021-03-08 05:47 UTC, Kishanthan reviewed
Please check the git commit guide we follow - https://chris.beams.io/posts/git-commit/

Please update the commit messages accordingly and squash related commits together.

2021-03-08 16:21 UTC, ramakotareddy commented
Opened new PR #159

2021-03-08 16:21 UTC, closed without merging