Add union-type support
ballerina-platform/nballerina pull request #133
Opened 2021-03-01 05:14 UTC by KavinduZoysa

## Purpose
$subject

Fixes #112 

## Goals
Adding union-type support.

## Approach
The approach is discussed in https://github.com/ballerina-platform/nballerina/discussions/113.
As a summary,
if we have `int|string a = 5;`, we create a struct as follows and assign it to `a`
```
{
   inherentType : int, (should be mangled name)
   valueRef : reference to 5
}
```

## Automation tests
 - Unit tests 
   Added unit tests

2021-03-01 05:40 UTC, Kishanthan commented on test/types/union/unionTypeReturn.bal
> +  return 221;
Please fix the formatting issues in all the bal file here.

2021-03-01 06:18 UTC, KavinduZoysa commented on test/types/union/unionTypeReturn.bal
> +  return 221;
Fixed.

2021-03-01 10:03 UTC, ruvi-d requested changes
There are some issues with the codegen when there are both `any` and `union` together.

Please verify with the following two examples:
```
int _bal_result = 0;
public function main() 
{
    any var1 = 42;
    int result1 = <int>var1;
    int | string var2 = 7;
    int result2 = <int>var2;
    _bal_result = result2;
}
```
&
```
int _bal_result = 0;
public function main() 
{
    int | string var1 = 42;
    any result1 = <any>var1;
    _bal_result = <int>result1;
}
```

2021-03-01 10:08 UTC, KavinduZoysa commented on compiler/llvmTypeCastInsn.cpp
> +  lhsOpRef = funcObj->getLocalVarRefUsingId(lhsOpName);
ACK. will check and get back

2021-03-04 04:39 UTC, KavinduZoysa commented on compiler/llvmTypeCastInsn.cpp
> +  lhsOpRef = funcObj->getLocalVarRefUsingId(lhsOpName);
Fixed this.

2021-03-04 08:54 UTC, ruvi-d requested changes
Shall we add a test case to cover set and get from Global Any and Union type variables?

2021-03-04 20:46 UTC, ayonam requested changes

2021-03-04 20:46 UTC, ayonam commented on compiler/llvmTypeCastInsn.cpp
> +        LLVMBuildStore(builder, rhsVarOpRef, lhsOpRef);
How can you do this store if it is a TYPE_TAG_UNION?  You need to perform a runtime check if the last assigned type of the RHS is a part of the UNION that the LHS holds.

2021-03-04 20:46 UTC, ayonam commented on compiler/llvmTypeCastInsn.cpp
> +        LLVMValueRef rhsVarOpRef = getFunction()->getLocalToTempVar(rhsOp);
Why are we doing this here?  Haven't we already got the RHS OpRef somewhere above?  And if we want to do this here, then if RHS Op is not a local, what do we do?

2021-03-04 20:46 UTC, ayonam commented on compiler/llvmTypeCastInsn.cpp
> +    LLVMValueRef castLoad = LLVMBuildLoad(builder, castResult, "");
Why do you need this load here?  The Cast Result should already contain the result of the cast operation and you should be able to store that into the LHS Op.

2021-03-04 20:46 UTC, ayonam commented on compiler/llvmTypeCastInsn.cpp
> +        funcObj->getLocalVarRefUsingId(getLhsOperand()->name());
Again why are we doing this here?  The code at lines 32-38 is already getting the LHS Op Ref, isn't it?  Here, if the LHS is a global variable, the the call to getLocalVarRefUsingId() could return NULL.

2021-03-05 08:01 UTC, ruvi-d commented on compiler/llvmFunctionGen.cpp
> +    return wrap(getPkgAddress()->getStructType());
we will address that under #144

2021-03-05 08:03 UTC, ruvi-d commented on compiler/llvmFunctionGen.cpp
> +    localVarRefs.insert({localVarName, localVarRef});
The call to `getLLVMTypeRefOfType()` handles ANY type and returns the correct type to the smart pointer type.

2021-03-05 08:08 UTC, ruvi-d commented on test/casting/anyTypeReturn.bal
> +// RUN: JAVA_HOME=%java_path %testRunScript %s %nballerinacc | filecheck %s
I believe that we have have to wait till #132 (mangled type string support) to support `is type` checks and failing tests.

2021-03-05 08:13 UTC, ayonam commented on compiler/llvmFunctionGen.cpp
> +    return wrap(getPkgAddress()->getStructType());
Fine.  Thanks.

2021-03-05 08:15 UTC, ayonam commented on test/casting/anyTypeReturn.bal
> +// RUN: JAVA_HOME=%java_path %testRunScript %s %nballerinacc | filecheck %s
Okay.  That's fine.  But then can we please add this requirement as a new issue and mark #132 as a dependency for the same?

2021-03-05 09:48 UTC, KavinduZoysa commented on compiler/llvmFunctionGen.cpp
> +    localVarRefs.insert({localVarName, localVarRef});
Yes, as @ruvi-d mentioned, I have done a refactoring here, still, the functionality is same.

2021-03-05 10:32 UTC, KavinduZoysa commented on compiler/llvmPackageGen.cpp
> +      paramTypes[i] = birFunc->getLLVMTypeRefOfType(
What we discussed was, to assign the struct type only for the union types variables. Since we are already doing the same thing for any type, with this change, we assign struct type for both union and any. If you look at the `getLLVMTypeRefOfType()` method, you will see I have handled any and union types together.

Do we need to assign struct type for simple types such as int, string, bool etc? I think we did not discussed such a thing.

2021-03-05 10:34 UTC, KavinduZoysa commented on test/union/simpleUnionAssignment3.bal
> +    string s = <string>u;
@ruvi-d, can we check value assigned for string variable?

2021-03-05 10:34 UTC, KavinduZoysa commented on test/union/simpleUnionAssignment3.bal
> +    string s = <string>u;
@ruvi-d, can we check value assigned for string variable?

2021-03-05 10:44 UTC, KavinduZoysa commented on test/union/simpleUnionAssignment3.bal
> +    string s = <string>u;
or we can do somthing like this right? `_bal_result = s == "test string"`

2021-03-05 10:50 UTC, ruvi-d commented on test/union/simpleUnionAssignment3.bal
> +    string s = <string>u;
not yet.. we need #120. We can revamp the tests when it get merged.

2021-03-05 16:59 UTC, ayonam commented on test/union/simpleUnionAssignment3.bal
> +    string s = <string>u;
@ruvi-d @KavinduZoysa 
Please mark this requirement against #120 and then resolve this conversation.  If it requires me to resolve this, then let me know.  I will do the needful.

2021-03-05 17:00 UTC, ayonam commented on test/casting/anyTypeReturn.bal
> +// RUN: JAVA_HOME=%java_path %testRunScript %s %nballerinacc | filecheck %s
@ruvi-d Have you marked this dependency on #132 ?  If yes, then please resolve this conversation.

2021-03-05 17:08 UTC, KavinduZoysa commented on compiler/llvmTypeCastInsn.cpp
> +    LLVMValueRef castLoad = LLVMBuildLoad(builder, castResult, "");
To get the value we need to do a load here.
```
  %"%43" = bitcast i8* %1 to i32*
  %2 = load i32, i32* %"%43", align 4
  store i32 %2, i32* %"%4", align 4
```

2021-03-05 17:21 UTC, KavinduZoysa commented on compiler/llvmTypeCastInsn.cpp
> +        LLVMBuildStore(builder, rhsVarOpRef, lhsOpRef);
In this, if block (L:52), we know both lhs and rhs parts are either union or any. That's why I simply assign the struct to lhs. If we have to do any runtime check we can do it on #147

2021-03-05 17:22 UTC, KavinduZoysa commented on compiler/llvmTypeCastInsn.cpp
> +        funcObj->getLocalVarRefUsingId(getLhsOperand()->name());
Fixed.

2021-03-05 17:22 UTC, KavinduZoysa commented on test/union/simpleUnionAssignment4.bal
> +    int result1 = <int>var1;
changed the test case

2021-03-05 17:32 UTC, KavinduZoysa commented on compiler/llvmTypeCastInsn.cpp
> +        LLVMValueRef rhsVarOpRef = getFunction()->getLocalToTempVar(rhsOp);
Here I have used the `getLocalToTempVar` method to create a temp variable from rhs. If rhsOp is global, it is handling Inside the `getLocalToTempVar` method

2021-03-05 17:40 UTC, KavinduZoysa commented on test/casting/anyTypeReturn.bal
> +// RUN: JAVA_HOME=%java_path %testRunScript %s %nballerinacc | filecheck %s
created an issue to track this https://github.com/ballerina-platform/nballerina/issues/152

2021-03-05 17:41 UTC, KavinduZoysa commented on test/union/simpleUnionAssignment3.bal
> +    string s = <string>u;
created an issue to track this https://github.com/ballerina-platform/nballerina/issues/152

2021-03-07 03:22 UTC, ruvi-d commented
> Shall we add a test case to cover set and get from Global Any and Union type variables?

Reminder to add a test case for Global Any and Union type variables

2021-03-07 07:50 UTC, KavinduZoysa commented
> > Shall we add a test case to cover set and get from Global Any and Union type variables?
> 
> Reminder to add a test case for Global Any and Union type variables

I checked it, I think we have to wait until we fix this issue https://github.com/ballerina-platform/nballerina/issues/149, because union/any types are initialized inside `.<init>` function. 

```
public ..<init> function() -> error{map<anydata | readonly>} | () {
    %0(RETURN) error | ();
    %0(RETURN) error | ();
    %1(TEMP) typeDesc<any | error>;
    %5(TEMP) int;

    bb0 {
;
        $annotation_data = NewMap %1;
        _bal_result = ConstLoad 20;
        %5 = ConstLoad 7;
        u = <int | string> %5;
        %0 = ConstLoad 0;
        GOTO bb2;
    }
    bb1 {
        GOTO bb2;
    }
    bb2 {
        return;
    }
}
```


If we generate the .ll file, struct is not initialized.

`@u = global %struct.smtPtr zeroinitializer, align 4`

2021-03-11 03:49 UTC, KavinduZoysa commented
> > Shall we add a test case to cover set and get from Global Any and Union type variables?
> 
> Reminder to add a test case for Global Any and Union type variables

Added tests related to global vars

2021-03-11 05:42 UTC, ruvi-d approved these changes
Good to merge. Just one test file missing an EoF

2021-03-11 05:42 UTC, ruvi-d commented on test/casting/any_global.bal
> +// CHECK: RETVAL=23
No new line at end of file

2021-03-11 14:31 UTC, KavinduZoysa commented on test/casting/any_global.bal
> +// CHECK: RETVAL=23
Added

2021-03-11 14:32 UTC, KavinduZoysa commented
@ayonam, could you please check this PR? I have addressed the suggestions.

2021-03-11 23:53 UTC, ayonam commented
> @ayonam, could you please check this PR? I have addressed the suggestions.

@KavinduZoysa I could figure out one of the comments above which I could resolve.  But for the rest I'm thoroughly confused.  Sorry about that.  Old age is catching up :-)

Will it be possible for you to open a fresh PR with your latest changes please?  I can review it then and you can merge that one instead.  Thanks.

2021-03-12 04:01 UTC, KavinduZoysa commented
> > @ayonam, could you please check this PR? I have addressed the suggestions.
> 
> @KavinduZoysa I could figure out one of the comments above which I could resolve. But for the rest I'm thoroughly confused. Sorry about that. Old age is catching up :-)
> 
> Will it be possible for you to open a fresh PR with your latest changes please? I can review it then and you can merge that one instead. Thanks.

@ayonam, this is the new PR https://github.com/ballerina-platform/nballerina/pull/167

2021-03-12 05:05 UTC, ayonam commented
> > > @ayonam, could you please check this PR? I have addressed the suggestions.
> > 
> > 
> > @KavinduZoysa I could figure out one of the comments above which I could resolve. But for the rest I'm thoroughly confused. Sorry about that. Old age is catching up :-)
> > Will it be possible for you to open a fresh PR with your latest changes please? I can review it then and you can merge that one instead. Thanks.
> 
> @ayonam, this is the new PR #167

Thanks @KavinduZoysa.  I will review 167 and give my comments.

2021-03-12 05:41 UTC, closed without merging