Port LIT tests to use runtime functions
ballerina-platform/nballerina pull request #150
Opened 2021-03-05 10:38 UTC by shubhamnarlawar

## Purpose
Port existing LIT unit tests to use runtime functions.

2021-03-05 13:36 UTC, shubhamnarlawar commented
Resolves #60 
Resolves #65

2021-03-05 13:38 UTC, shubhamnarlawar commented
@KavinduZoysa - In nil.bal testcase, the RETVAL is 0. Hence, at the end of `main()` - I am printing `printu32(0)` to pass the testcase. Is it fine?

2021-03-05 15:01 UTC, KavinduZoysa commented
> @KavinduZoysa - In nil.bal testcase, the RETVAL is 0. Hence, at the end of `main()` - I am printing `printu32(0)` to pass the testcase. Is it fine?

Ideally we have to do a type test. @ayonam what do you think?

2021-03-05 16:51 UTC, ayonam commented
> > @KavinduZoysa - In nil.bal testcase, the RETVAL is 0. Hence, at the end of `main()` - I am printing `printu32(0)` to pass the testcase. Is it fine?
> 
> Ideally we have to do a type test. @ayonam what do you think?

Yes, we should check if the type 

> > @KavinduZoysa - In nil.bal testcase, the RETVAL is 0. Hence, at the end of `main()` - I am printing `printu32(0)` to pass the testcase. Is it fine?
> 
> Ideally we have to do a type test. @ayonam what do you think?

Yes, we should check if the type of the value assigned to () n is actually a NIL type or not and only then print the zero.

2021-03-05 18:10 UTC, shubhamnarlawar commented
> > > @KavinduZoysa - In nil.bal testcase, the RETVAL is 0. Hence, at the end of `main()` - I am printing `printu32(0)` to pass the testcase. Is it fine?
> > 
> > 
> > Ideally we have to do a type test. @ayonam what do you think?
> 
> Yes, we should check if the type of the value assigned to () n is actually a NIL type or not and only then print the zero.

Got it. I will add a if block as below - 

  `  if (n == ()) {`
 `     printu32(0);`
`    }`

at the end of `main()` function.

2021-03-06 17:47 UTC, shubhamnarlawar commented
> > > > @KavinduZoysa - In nil.bal testcase, the RETVAL is 0. Hence, at the end of `main()` - I am printing `printu32(0)` to pass the testcase. Is it fine?
> > > 
> > > 
> > > Ideally we have to do a type test. @ayonam what do you think?
> > 
> > 
> > Yes, we should check if the type of the value assigned to () n is actually a NIL type or not and only then print the zero.
> 
> Got it. I will add a if block as below -
> 
> ` if (n == ()) {`
> ` printu32(0);`
> ` }`
> 
> at the end of `main()` function.

Done.

2021-03-07 04:09 UTC, ruvi-d requested changes
Please see the review comments

2021-03-07 13:51 UTC, shubhamnarlawar commented on compiler/llvmFunctionCallInsn.cpp
> +    if (callResult && lhsRef && !unwrap(callResult)->getType()->isVoidTy()) {
For void functions, there should not be a string paramater `"call"` in `LLVMBuildCall()`. It is throwing error. Hence, void functions need to be handled using above check.

2021-03-07 13:56 UTC, shubhamnarlawar commented on test/testRunScript.sh
> +echo RETVAL=$(./$filename.out)
Can you elaborate more? I am not clear on what you mean by removing `RETVAL`?

In testcases, we have - `// CHECK: RETVAL=128` as last line. In the script, `testRunScript.sh` we are assigning the value printed by `./a.out` to `RETVAL` which is checked by LIT infrastructure on whether both values are same or not.

2021-03-07 13:59 UTC, shubhamnarlawar commented on test/string/string.bal
> +    printu32(1);
Created an issue - #153

2021-03-07 14:00 UTC, shubhamnarlawar commented on test/casting/stringTypeCast.bal
> +    printu32(1);
Created an issue - #153

2021-03-07 14:07 UTC, shubhamnarlawar commented on compiler/llvmPackageGen.cpp
> +    if ((birFunc->getFlags() & NATIVE) == NATIVE)
Done. Changed it to `unsigned int`.

2021-03-07 14:30 UTC, shubhamnarlawar commented
This PR resolves #153

2021-03-09 03:46 UTC, ruvi-d commented on compiler/llvmFunctionCallInsn.cpp
> +    if (callResult && lhsRef && !unwrap(callResult)->getType()->isVoidTy()) {
We don't have void functions in Ballerina. Since #94, all functions (except main) with empty return type is returning NIL.
Why are we having to handle Void return types? 
Is it because of the Rust print functions? if that is the case it needs to be fix. They should be handled as having NIL return types, or change them to any other valid type like int types.

2021-03-09 13:20 UTC, shubhamnarlawar commented
@ruvi-d - I have recently ported all the tests to use runtime functions. All the tests were passing.

I have merged changes from master to current branch and all the tests are failing with below error - 

`$file-bir-dump.ll:16:1: error: expected instruction opcode`
`}`
`^`
`1 error generated.`

2021-03-09 13:22 UTC, shubhamnarlawar commented
> @ruvi-d - I have recently ported all the tests to use runtime functions. All the tests were passing.
> 
> I have merged changes from master to current branch and all the tests are failing with below error -
> 
> `$file-bir-dump.ll:16:1: error: expected instruction opcode`
> `}`
> `^`
> `1 error generated.`

I have reverted the merge. Let me re-analyze the conflict!

2021-03-09 13:53 UTC, shubhamnarlawar commented on compiler/llvmFunctionCallInsn.cpp
> +    if (callResult && lhsRef && !unwrap(callResult)->getType()->isVoidTy()) {
Regarding this point, discussion is going on in PR #159!

2021-03-10 10:26 UTC, shubhamnarlawar commented on compiler/llvmFunctionCallInsn.cpp
> +    if (callResult && lhsRef && !unwrap(callResult)->getType()->isVoidTy()) {
The above check is not required anymore. #139 resolves above issue and hence, the above check is not required anymore!

2021-03-10 10:59 UTC, shubhamnarlawar commented
PR #159 causes massive code changes and directory structure. Hence, the conflicts from this PR could not be resolved.

I have manually cherry-picked commits from this PR and have opened a new PR consisting same commits - #163.

Hence, closing this PR.

2021-03-10 10:59 UTC, closed without merging