Added support for Create type strings for array/boolean/int/float types.
ballerina-platform/nballerina pull request #159
Opened 2021-03-08 16:16 UTC by ramakotareddy

## Purpose
-> Added support for Create type strings for array/boolean/int/float types #87 .
-> Changes related to Migrate array cast to use generated type string #88 .

Resolves #87
Resolves #88

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-03-08 17:04 UTC, KavinduZoysa commented on compiler/llvmArrayStoreInsn.cpp
> +    paramTypes[2] = int32PtrType;
The same pattern can be seen in several places, please check

2021-03-08 17:04 UTC, KavinduZoysa commented on compiler/llvmFunctionGen.cpp
> +            } else {
We do not need `else` here. The pattern should be something like this
```
for() {
    if (!callInst) {
          continue;
    } 
    // do something
}
```

2021-03-08 17:07 UTC, KavinduZoysa commented on compiler/llvmPackageGen.cpp
> +            }
```
            if (funcParam && funcParam->typeTag() == TYPE_TAG_ANY) {
                paramTypes[i] = wrap(structType);
                continue;
            } 
            paramTypes[i] = birFunc->getLLVMTypeRefOfType(funcParam->getVarDecl()->getTypeDecl());
```

2021-03-09 05:25 UTC, ruvi-d requested changes

2021-03-09 05:25 UTC, ruvi-d commented on test/array/anyTypeVarAssignToArray.bal
> +// RUN: JAVA_HOME=%java_path %testRunScript %s %nballerinacc | filecheck %s
Shall we add a test case to cover cast failure? we can print an error on the Rust side and test it from LIT.

2021-03-09 05:25 UTC, ruvi-d commented on compiler/llvmTypeCastInsn.cpp
> +            finalString = "__A";
Why are there `__` prefix? 
This is are the index defined in the runtime
```
pub const BASE_TYPE_INDEX: usize = 0;
pub const ARRAY_MEMBER_TYPE_INDEX: usize = 1;
pub const ARRAY_SIZE_LSB_INDEX: usize = 2;
pub const ARRAY_SIZE_MSB_INDEX: usize = 3;
```

2021-03-09 05:25 UTC, ruvi-d commented on test/array/anyTypeVarAssignToArray.bal
> +    a[0] = <int>x;
I added a line in the Rust side to to print the strings that are getting passed to Runtime lib (`println!("{} is {}", source, destination);` to line 113 in type_checker.rs). The two strings appear to be empty.  
Type strings are being passed to the for the tests in the casting folder, but not for this cast. Please check.

2021-03-09 05:25 UTC, ruvi-d commented on compiler/llvmTypeCastInsn.cpp
> +        // TODO Need to add Size of the array.
Create task to track the todo and link it in the PR

2021-03-09 09:20 UTC, ramakotareddy commented on compiler/llvmFunctionGen.cpp
> +            } else {
@KavinduZoysa , I am using this type of c++ style code. Every if block i am adding else block. 
Is there any drawback with this type of code? Please suggest.

2021-03-09 09:20 UTC, ramakotareddy commented on compiler/llvmArrayStoreInsn.cpp
> +    paramTypes[2] = int32PtrType;
Fixed

2021-03-09 09:26 UTC, ramakotareddy commented on compiler/llvmFunctionCallInsn.cpp
> +    if (callResult && lhsRef && !unwrap(callResult)->getType()->isVoidTy()) {
@ruvi-d, Are you talking about "!unwrap(callResult)->getType()->isVoidTy())" this line of code? if yes, 
these are LLVM Api's. In llvm there is no NIL type, have only Void type. Here i am checking LLVMCall instruction  return type is Void type or not.  (getType() and isVoidTy() are LLVM Api's)

2021-03-09 10:08 UTC, ruvi-d commented on compiler/llvmFunctionCallInsn.cpp
> +    if (callResult && lhsRef && !unwrap(callResult)->getType()->isVoidTy()) {
Since #94 we handling returning NIL type via pointer. So there is no need to check for void return types, because we shouldn't be generating any functions that have void types.
@KavinduZoysa : please confirm

2021-03-09 11:23 UTC, ramakotareddy commented on compiler/llvmTypeCastInsn.cpp
> +            finalString = "__A";
@ruvi-d , Normal strings(e.g: "hello world") also will go to string builder table. For differentiate between normal strings and typestrings, we are adding prefix "'__'.

2021-03-09 12:21 UTC, ruvi-d commented on compiler/llvmFunctionGen.cpp
> +            } else {
Yes Ram, we prefer the early exit pattern as described here: https://llvm.org/docs/CodingStandards.html#use-early-exits-and-continue-to-simplify-code

2021-03-09 15:18 UTC, KavinduZoysa commented on compiler/llvmFunctionCallInsn.cpp
> +    if (callResult && lhsRef && !unwrap(callResult)->getType()->isVoidTy()) {
Yes, as @ruvi-d mentioned, we are returning void type only for the `main` function if `_bal_result` is not defined.

2021-03-09 23:56 UTC, ramakotareddy commented on compiler/llvmFunctionGen.cpp
> +                    // generate LLVMFunction call to Abort from elseLLVMBB(abortBB).
@ruvi-d , Abort will destruct the resources, no need to de initialization.

2021-03-10 03:03 UTC, ruvi-d commented on compiler/llvmFunctionGen.cpp
> +                    // generate LLVMFunction call to Abort from elseLLVMBB(abortBB).
Are you sure? I can only find evidence to the contrary : https://stackoverflow.com/questions/397075/what-is-the-difference-between-exit-and-abort/397081#397081

2021-03-11 14:48 UTC, KavinduZoysa commented on compiler/llvmArrayStoreInsn.cpp
> +    paramTypes[2] = int32PtrType;
It seems, still, it is not fixed, please check.

2021-03-12 05:33 UTC, ramakotareddy commented
Opened new PR #168

2021-03-12 05:33 UTC, closed without merging