Add support for generation of opaque pointer to rust strings.
ballerina-platform/nballerina pull request #161
Opened 2021-03-09 14:23 UTC by shubhamnarlawar

## Purpose
This PR adds support for generation of opaque pointer to rust strings.

2021-03-09 15:42 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn opaque_ptr_to_string(string: *const c_char, size: usize) -> &'static [i8] {
I think this is missing the point; at least my understanding of #125 as I detailed there.

The function name should be some this like `new_string`. The input is a c_string pointer and the output is an opaque pointer (void * like). That pointer should point to an instance of an Rust structure (or whatever the equivalent of a C++ class) that models Ballerina string type.

@manuranga WDYT?

2021-03-09 16:57 UTC, manuranga commented on runtime/src/lib.rs
> +pub extern "C" fn opaque_ptr_to_string(string: *const c_char, size: usize) -> &'static [i8] {
Yes. It should be a rust struct.
```rust
struct BString {
    value: String
}
```
But I think we have the option to return in by value or as a pointer. Because the rust string is already heap allocated, if we return it as a pointer, the ballerina string will become double pointers. It will have a small performance hit.

2021-03-11 17:35 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn opaque_ptr_to_string(string: *const c_char, size: usize) -> &'static [i8] {
From above structure, you mean the String has to be created in below way - 

```pub unsafe fn from_raw_parts(
    buf: *mut u8,
    length: usize,
    capacity: usize
) -> String```

i.e. ```String::from_raw_parts(buf, length, capacity)``` which will be a member of above structure.

2021-03-12 06:37 UTC, manuranga commented on runtime/src/lib.rs
> +pub extern "C" fn opaque_ptr_to_string(string: *const c_char, size: usize) -> &'static [i8] {
Seems rust needs a mutable pointer to create a string, Let's use a slice instead https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html
Then we should be able use `std::str::from_utf8` to convert it to `&str`.

```rust
struct BString {
    value: &str
}
```

2021-03-15 07:13 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn opaque_ptr_to_string(string: *const c_char, size: usize) -> &'static [i8] {
I tried below approach to return BString by value - 

'''pub struct BString {
    value: &'static str
}

#[no_mangle]
pub extern "C" fn new_string(bal_string: *const u8, size: usize) -> BString {
    let slice = unsafe { std::slice::from_raw_parts(bal_string, size) };
    let string = std::str::from_utf8(slice);
    let opaque = BString { value: string.unwrap() };
    return opaque;
}'''

2021-03-16 07:06 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn opaque_ptr_to_string(string: *const c_char, size: usize) -> &'static [i8] {
From today's discussion, pointer to above struct using Box approach is the correct way at present.

2021-03-16 07:15 UTC, manuranga commented on runtime/src/lib.rs
> +pub extern "C" fn opaque_ptr_to_string(string: *const c_char, size: usize) -> &'static [i8] {
Ya, that would be easier, otherwise we'll have to keep track of the size of BString size in the llvm side. Lets use `Box::into_raw(Box::new(...)))` and return as a pointer.

2021-03-16 16:46 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn opaque_ptr_to_string(string: *const c_char, size: usize) -> &'static [i8] {
Done. Now, I am returning a pointer to BString. Is it fine now?

```
pub struct BString {
    value: &'static str
}

#[no_mangle]
pub extern "C" fn new_string(bal_string: *const u8, size: usize) -> *mut BString {
    let slice = unsafe { std::slice::from_raw_parts(bal_string, size) };
    let string = std::str::from_utf8(slice);
    let opaque = BString { value: string.unwrap() };
    let opaque_ptr = Box::into_raw(Box::new(opaque));
    return opaque_ptr;
}
```

2021-03-17 02:52 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn opaque_ptr_to_string(string: *const c_char, size: usize) -> &'static [i8] {
Looks good. 
How about we also implementing a print_string method that accepts this BString pointer? Then we can write a small demo C++ app to call `new_string` and then `print_string` with the returned opaque pointer to confirm the end-to-end functionality.

2021-03-17 08:45 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn opaque_ptr_to_string(string: *const c_char, size: usize) -> &'static [i8] {
Done. Please check it.

2021-03-17 09:25 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn opaque_ptr_to_string(string: *const c_char, size: usize) -> &'static [i8] {
Good from my end! 
Just add a null check before using each pointer.

2021-03-17 10:00 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn opaque_ptr_to_string(string: *const c_char, size: usize) -> &'static [i8] {
Do you mean to add pointer null check in `runtime/interoptest/test.cpp`? Because in rust code, I am using `unsafe { }` while using pointer.

2021-03-17 10:38 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn opaque_ptr_to_string(string: *const c_char, size: usize) -> &'static [i8] {
On the rust side, like this https://github.com/ballerina-platform/nballerina/blob/master/runtime/src/lib.rs#L169

2021-03-17 12:24 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn opaque_ptr_to_string(string: *const c_char, size: usize) -> &'static [i8] {
Done.

2021-03-17 12:24 UTC, shubhamnarlawar commented
Is this PR find to merge now?
@ruvi-d and @manuranga - Please approve.

2021-03-17 12:35 UTC, ruvi-d commented
> Is this PR find to merge now?
> @ruvi-d and @manuranga - Please approve.

I don't think we need to commit the `runtime/interoptest/test.cpp` file. That was just to verify you proof of concept.
Also, to resolve #125, you need to update the codegen logic to use this BString.

2021-03-17 12:40 UTC, shubhamnarlawar commented
> > Is this PR find to merge now?
> > @ruvi-d and @manuranga - Please approve.
> 
> I don't think we need to commit the `runtime/interoptest/test.cpp` file. That was just to verify you proof of concept.
> Also, to resolve #125, you need to update the codegen logic to use this BString.

Got it. I will remove `runtime/interoptest/test.cpp`

Can you elaborate it bit more on what you mean to update the codegen logic?

2021-03-17 12:42 UTC, ruvi-d commented
> Can you elaborate it bit more on what you mean to update the codegen logic?

So the issue description says:
```
string s = "hello";
Above should call rust and get a pointer to the rust string. 
```
So instructions like the constLoad for strings need to be updated to use your Rust function.

2021-03-19 08:01 UTC, shubhamnarlawar commented
> > Can you elaborate it bit more on what you mean to update the codegen logic?
> 
> So the issue description says:
> 
> ```
> string s = "hello";
> Above should call rust and get a pointer to the rust string. 
> ```
> 
> So instructions like the constLoad for strings need to be updated to use your Rust function.

I have a small query here - 

If I move it to rust string in ConstLoadInsn, then how to get length of string to pass it to `StringRef()`?

https://github.com/ballerina-platform/nballerina/blob/37be97d5c8fbcb2cbf25ed7fad7594cd095bd323/compiler/codegen/ConstantLoadInsn.cpp#L91

At present, we are passing std::string stringValue as - 
`StringRef(stringValue.c_str(), stringValue.length())`

Now, we will call `new_string()` to get a pointer to structure consisting rust string i.e. `ptr` and will pass it as - 
`StringRef(&ptr, length)` but here how to get the length? Because now we have `const char*` here and not `std::string` as earlier.

2021-03-19 09:20 UTC, ruvi-d commented
> Now, we will call `new_string()` to get a pointer to structure consisting rust string i.e. `ptr` and will pass it as -
> `StringRef(&ptr, length)` but here how to get the length? Because now we have `const char*` here and not `std::string` as earlier.

^ this bit didn't make sense to me. We don't need to the opaque pointer returned from Rust to create a `llvm::ConstantDataArray` right?. 
We need to send `stringValue` to `new_string()` and store the returned pointer as lhs's LLVMValueRef.

2021-03-24 16:47 UTC, shubhamnarlawar commented
I am fixing merge conflict with the master.

2021-03-24 16:48 UTC, shubhamnarlawar commented
> > Now, we will call `new_string()` to get a pointer to structure consisting rust string i.e. `ptr` and will pass it as -
> > `StringRef(&ptr, length)` but here how to get the length? Because now we have `const char*` here and not `std::string` as earlier.
> 
> ^ this bit didn't make sense to me. We don't need to the opaque pointer returned from Rust to create a `llvm::ConstantDataArray` right?
> We need to send `stringValue` to `new_string()` and store the returned pointer as lhs's LLVMValueRef.

Yes.
Now, I am getting opaque pointer using `new_string()` and storing it as lhs's LLVMValueRef.

2021-03-26 08:47 UTC, shubhamnarlawar commented
I have resolved merge conflict with master.

@ruvi-d - Please review and suggest changes if any.

2021-03-26 08:56 UTC, ruvi-d commented
There are no tests that you the new Strings. Please remove the use of `print_str` in tests and use the new `print_string` function instead.

2021-03-26 09:07 UTC, ruvi-d requested changes

2021-03-26 09:08 UTC, shubhamnarlawar commented on compiler/include/ConstantLoad.h
> +    } val;
Yes. I have removed it. Actually, the snippet came while rebasing with master.

2021-03-26 09:09 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsn.cpp
> +    paramTypes[1] = LLVMInt32Type();
Got it. I will push this change.

2021-03-26 09:17 UTC, shubhamnarlawar commented
> There are no tests that you the new Strings. Please remove the use of `print_str` in tests and use the new `print_string` function instead.

`print_string` is internal function to be used from the llvm side. How we will use it in `.bal` testcase?
Do you want me to add rust tests for `print_string`?


public function main() {
    string str = "Hello World!";
    print_str("RESULT=");
    print_string(str);
}

2021-03-26 09:27 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsn.cpp
> +    paramTypes[1] = LLVMInt32Type();
Done. Thanks for the suggestion!

2021-03-26 10:00 UTC, ruvi-d commented
> > There are no tests that you the new Strings. Please remove the use of `print_str` in tests and use the new `print_string` function instead.
> 
> `print_string` is internal function to be used from the llvm side. How we will use it in `.bal` testcase?
> Do you want me to add rust tests for `print_string`?

you have `print_string` at https://github.com/ballerina-platform/nballerina/blob/15a49c0ad5cc28904950aa948861a743231e5e91/runtime/src/lib.rs#L51
We don't need `ptrint_str` at  https://github.com/ballerina-platform/nballerina/blob/15a49c0ad5cc28904950aa948861a743231e5e91/runtime/src/lib.rs#L132

2021-03-26 10:08 UTC, ruvi-d commented on compiler/include/ConstantLoad.h
> +    } val;
Please be more careful next time

2021-03-26 10:38 UTC, shubhamnarlawar commented
> > > There are no tests that you the new Strings. Please remove the use of `print_str` in tests and use the new `print_string` function instead.
> > 
> > 
> > `print_string` is internal function to be used from the llvm side. How we will use it in `.bal` testcase?
> > Do you want me to add rust tests for `print_string`?
> 
> you have `print_string` at
> 
> https://github.com/ballerina-platform/nballerina/blob/15a49c0ad5cc28904950aa948861a743231e5e91/runtime/src/lib.rs#L51
> 
> We don't need `ptrint_str` at
> 
> https://github.com/ballerina-platform/nballerina/blob/15a49c0ad5cc28904950aa948861a743231e5e91/runtime/src/lib.rs#L132

So, we need to use `print_string` in all the bal testcases instead of `print_str`, right?

I tried porting below testcase - `string.bal`

From -

public function print_str(string val) = external;

public function main() {
    string str = "Hello World!";
    print_str("RESULT=");
    print_str(str);
}


To - 

public function print_string(string val) = external;

public function main() {
    string str = "Hello World!";
    print_string("RESULT=");
    print_string(str);
}

I am getting segmentation fault using `print_string`.
Sample IR - 

https://github.com/shubhamnarlawar/LLVM-IR-samples/blob/c5ab78ec6e97c654e8e08dc951968650bdb8a1be/string-bir-dump.ll#L29

2021-03-26 10:45 UTC, ruvi-d commented
> public function print_string(string val) = external;
> 
> public function main() {
>     string str = "Hello World!";
>     print_string("RESULT=");
>     print_string(str);
> }

This is the most basic test to verify the functionality of this PR right? 
Please debug and fix the issue.

2021-03-26 10:47 UTC, shubhamnarlawar commented on compiler/include/ConstantLoad.h
> +    } val;
Sure.
Actually, the changes in this PR and merge changes from the master were on same file -ConstantLoad.h 

Hence, git merge fails when it is not able to automatically rebase. In that case, I have to manually resolve this merge conflict.
I will cross verify it from the next time!

2021-03-26 10:58 UTC, shubhamnarlawar commented
> public function print_string(string val) = external;
> 
> public function main() {
> string str = "Hello World!";
> print_string("RESULT=");
> print_string(str);
> }

More basic one would be - 

```
    public function print_string(string val) = external;

    public function main() {
    print_string("RESULT="););
    }
```
on which I am getting blank output instead of - `RESULT=`. I am debugging this one!

2021-03-26 11:21 UTC, shubhamnarlawar commented
> > public function print_string(string val) = external;
> > public function main() {
> > string str = "Hello World!";
> > print_string("RESULT=");
> > print_string(str);
> > }
> 
> This is the most basic test to verify the functionality of this PR right?
> Please debug and fix the issue.

I have found the fix for above issue. Now, I am porting all the testcases to use `print_string`.
I will send the changes.

Is there any other changes apart from this?

2021-03-26 12:40 UTC, ruvi-d commented
> Is there any other changes apart from this?

There is the Runtime side of the maps. They need to be updated to use BalString. Create a task for that if you are not going to handle it with this PR.

2021-03-26 12:46 UTC, ruvi-d commented
> I have found the fix for above issue.

What was the issue?

2021-03-26 12:52 UTC, shubhamnarlawar commented
> > I have found the fix for above issue.
> 
> What was the issue?

I was receiving opaque pointer using `i8**` which should be `i8*`.

2021-03-26 13:02 UTC, shubhamnarlawar commented
> > Is there any other changes apart from this?
> 
> There is the Runtime side of the maps. They need to be updated to use BalString. Create a task for that if you are not going to handle it with this PR.

Created an issue for this #216

2021-03-26 13:03 UTC, shubhamnarlawar commented
Is this PR ready to merge now?

2021-03-26 14:08 UTC, shubhamnarlawar commented
> > Is there any other changes apart from this?
> 
> There is the Runtime side of the maps. They need to be updated to use BalString. Create a task for that if you are not going to handle it with this PR.

In maps at rust side - 

https://github.com/ballerina-platform/nballerina/blob/a969374bf4ee1f76fc4a33de052c35646010b2e2/runtime/src/bal_map.rs#L5

From above, I can see a rust `String`. Can you please explain this scenario of BalMap?

2021-03-26 16:23 UTC, shubhamnarlawar commented
> Is this PR ready to merge now?

PING.

2021-03-26 16:40 UTC, ruvi-d requested changes

2021-03-26 16:40 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn print_string(opaque_ptr: *mut BString) {
Missing delete/deinit string function.
Delete the old print_str() function. 
With hindsight, look like it would have been easier to rename the new `print_string` function as print_str and not touch the test files. never mind though.

2021-03-26 16:40 UTC, ruvi-d commented on compiler/codegen/ConstantLoadInsn.cpp
> +        LLVMValueRef *sizeOpValueRef = new LLVMValueRef[2];
Again. No heap allocations pls.

2021-03-26 17:13 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsn.cpp
> +        LLVMValueRef *sizeOpValueRef = new LLVMValueRef[2];
Done.

2021-03-26 17:14 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn print_string(opaque_ptr: *mut BString) {
1. Added `delete_string` and `deinit_string` function for string.
2. Deleted `print_str` function

Is it fine now?

2021-03-28 12:22 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn print_string(opaque_ptr: *mut BString) {
> Missing delete/deinit string function.

^ I meant delete or deinit
let's go with only `string_deinit`. That will make the naming consistent with what we have for map's at the moment

2021-03-28 12:24 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn print_string(opaque_ptr: *mut BString) {
Please request review when done. Will approve PR then.

2021-03-28 16:49 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn print_string(opaque_ptr: *mut BString) {
Done. Requested review!

2021-03-29 03:24 UTC, ruvi-d approved these changes

2021-03-29 05:22 UTC, Kishanthan approved these changes

2021-03-29 05:23 UTC, merged