Port LIT tests to use runtime functions
ballerina-platform/nballerina pull request #163
Opened 2021-03-10 10:49 UTC by shubhamnarlawar

Port existing LIT unit tests to use runtime functions.

Resolves #60
Resolves #65
Resolves #153

2021-03-10 11:00 UTC, shubhamnarlawar commented
Is this PR ready to merge in master?

2021-03-11 02:56 UTC, ruvi-d requested changes

2021-03-11 02:56 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +    birFunction->setFlags(flags);
flags are being passed via the constructor in line 667. No need to set it again.
Just update the constructor to initialize flags.

2021-03-11 02:56 UTC, ruvi-d commented on compiler/codegen/Function.cpp
> +void Function::setFlags(unsigned int f) { flags = f; }
Flags setter not required

2021-03-11 02:56 UTC, ruvi-d commented on compiler/include/Function.h
> +
I'd suggest that you make these constants private to the Function class and expose it to Package class via a `isNatveFunction()`. You can do the `(function->getFlags() & NATIVE) == NATIVE` logic inside this function.

2021-03-11 02:56 UTC, ruvi-d commented on compiler/codegen/Package.cpp
> +            continue;
See other comment about using a `isNatveFunction()`

2021-03-11 02:57 UTC, ruvi-d commented
BTW, what happen to the check if return type is VOID from your previous PR?

2021-03-11 07:04 UTC, shubhamnarlawar commented
> BTW, what happen to the check if return type is VOID from your previous PR?

There is one comment by you on PR #159 -

`Since #94 we handling returning NIL type via pointer. So there is no need to check for void return types, because we shouldn't be generating any functions that have void types.`

Now, there are no void type function. Hence, that check from other PR is not required.

2021-03-11 07:53 UTC, shubhamnarlawar commented on compiler/codegen/Package.cpp
> +            continue;
Done

2021-03-11 07:53 UTC, shubhamnarlawar commented on compiler/include/Function.h
> +
Done

2021-03-11 07:53 UTC, shubhamnarlawar commented on compiler/codegen/Function.cpp
> +void Function::setFlags(unsigned int f) { flags = f; }
Removed

2021-03-11 07:53 UTC, shubhamnarlawar commented on compiler/BIRReader.cpp
> +    birFunction->setFlags(flags);
Done.

2021-03-11 07:55 UTC, shubhamnarlawar commented
@ruvi-d - I have addressed and pushed changes of above suggestions. Is it ready to merge now?

2021-03-11 08:07 UTC, ruvi-d approved these changes
Just one more minor thing. Good to merge afterwards.

2021-03-11 08:07 UTC, ruvi-d commented on compiler/codegen/Function.cpp
>  Function::Function(Package *_parentPackage, std::string name, std::string workerName, [[maybe_unused]] int flags,
Remove the `[[maybe_unused]]` in front of `int flags`

2021-03-11 08:59 UTC, shubhamnarlawar commented on compiler/codegen/Function.cpp
>  Function::Function(Package *_parentPackage, std::string name, std::string workerName, [[maybe_unused]] int flags,
Done

2021-03-11 09:08 UTC, shubhamnarlawar commented
Is it fine to merge now?

2021-03-12 06:17 UTC, Kishanthan approved these changes

2021-03-12 06:17 UTC, merged

2021-03-12 06:23 UTC, ruvi-d commented
Pending tasks: #170, #171

2021-03-12 19:02 UTC, ayonam commented
@shubhamnarlawar  The issue that you are facing is because of the compiler not finding the ballerina_rt library in the directory that you gave as the library search path.  In the command below, you provide only one path (../../../runtime/target/release) as the library search path.  

              clang -O0 -o $filename.out $filename-bir-dump.ll -L../../../runtime/target/release -lballerina_rt 2>err.log

Since it is a relative path, it may be possible that the directory from where you are running the failing test case, this path does not exist as a relative path and hence it is unable to find the library file  libballerina_rt.so.  So you should investigate one failing test case and check the directory from where it is invoked.  Then see if it the library file is reachable from there using this path.  If not, then you need to add the relevant path to the library search list using another -L option on the command line apart from the one that you already have.