Support for union type
ballerina-platform/nballerina pull request #167
Opened 2021-03-12 04:00 UTC by KavinduZoysa

## Purpose
$subject. 
Fixes #112

Please check PR https://github.com/ballerina-platform/nballerina/pull/133 for more information

2021-03-12 08:40 UTC, ayonam requested changes

2021-03-13 03:28 UTC, KavinduZoysa commented on test/casting/any_global.bal
> +    a = 23;
Yes, correct.

2021-03-13 03:28 UTC, KavinduZoysa commented on test/union/union_global.bal
> +    a = 24;
Yes, correct

2021-03-13 03:54 UTC, KavinduZoysa commented on compiler/codegen/TypeCastInsn.cpp
> +        LLVMValueRef lastTypeIdx __attribute__((unused)) = LLVMBuildStructGEP(builder, rhsOpRef, 0, "inherentTypeIdx");
At this moment we may not need to get the type. But for this issue https://github.com/ballerina-platform/nballerina/issues/147, we need the type. So shall we keep it?

2021-03-13 03:54 UTC, KavinduZoysa commented on compiler/codegen/TypeCastInsn.cpp
> +            LLVMValueRef rhsVarOpRef = getFunction()->getTempLocalVariable(rhsOp);
FIxed

2021-03-13 03:55 UTC, KavinduZoysa commented on test/union/simple_union_assignment3.bal
> +}
Create an issue to fix it https://github.com/ballerina-platform/nballerina/issues/152

2021-03-15 07:40 UTC, KavinduZoysa commented on test/union/simple_union_assignment3.bal
> +}
Checking the string now.

2021-03-15 07:50 UTC, shubhamnarlawar commented on test/union/simple_union_assignment1.bal
> +int _bal_result = 0;
Please remove _bal_result variable as we are using runtime functions for printing values.

2021-03-15 07:51 UTC, shubhamnarlawar commented on test/union/simple_union_assignment2.bal
> +boolean _bal_result = false;
Please remove _bal_result variable as we are using runtime functions for printing values.

2021-03-15 08:21 UTC, KavinduZoysa commented on test/union/simple_union_assignment1.bal
> +int _bal_result = 0;
Fixed.

2021-03-15 08:21 UTC, KavinduZoysa commented on test/union/simple_union_assignment2.bal
> +boolean _bal_result = false;
Fixed

2021-03-15 08:24 UTC, KavinduZoysa commented
@ayonam, please review the new changes.

2021-03-15 23:29 UTC, ayonam commented on compiler/codegen/TypeCastInsn.cpp
> +        LLVMValueRef lastTypeIdx __attribute__((unused)) = LLVMBuildStructGEP(builder, rhsOpRef, 0, "inherentTypeIdx");
Okay, you may just want to keep this.  Although, this is dead code.  :-)

2021-03-15 23:30 UTC, ayonam approved these changes

2021-03-22 14:59 UTC, manuranga commented on compiler/codegen/TypeCastInsn.cpp
> +        LLVMValueRef constValue = LLVMConstInt(LLVMInt32Type(), tempRandNum, 0);
Why a randome number is used?

2021-03-23 12:50 UTC, KavinduZoysa commented on compiler/codegen/TypeCastInsn.cpp
> +        LLVMValueRef constValue = LLVMConstInt(LLVMInt32Type(), tempRandNum, 0);
I followed what we have done previously. If we use a constant value instead of a random number, codegen is stuck at this line. https://github.com/ballerina-platform/nballerina/blob/47412e296861a2a4b8cee4cbd22e3753dc207852/compiler/codegen/Package.cpp#L221

@ramakotareddy, Do you have any idea on this?

2021-03-23 12:59 UTC, ruvi-d commented on compiler/codegen/TypeCastInsn.cpp
> +        LLVMValueRef constValue = LLVMConstInt(LLVMInt32Type(), tempRandNum, 0);
Guys, shall we create a discussion/issue to discuss this and merge this PR please? 
it's been almost 30 days since we started this PR :-)

2021-03-23 13:35 UTC, KavinduZoysa commented on compiler/codegen/TypeCastInsn.cpp
> +        LLVMValueRef constValue = LLVMConstInt(LLVMInt32Type(), tempRandNum, 0);
https://github.com/ballerina-platform/nballerina/issues/195 Created a new issue to track this.

2021-03-23 13:38 UTC, merged