Create type strings
ballerina-platform/nballerina pull request #168
Opened 2021-03-12 05:27 UTC by ramakotareddy

-> Added support for Create type strings for array/boolean/int/float types #87 .
-> Changes related to Migrate array cast to use generated type string #88 .

Resolves #87
Resolves #88

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-03-12 10:28 UTC, ruvi-d requested changes
Rust side still needs to be updated to handle the "__" prefix of the type string

2021-03-12 13:28 UTC, ruvi-d requested changes
This is part of my review. There is more that I need to check.

2021-03-12 13:28 UTC, ruvi-d commented on compiler/codegen/Function.cpp
> +            insnName = callInst->getOperand(totalOperands - 1)->getName().data();
make it 
```
size_t totalOperands = callInst->getNumOperands();
const char * insnName = callInst->getOperand(totalOperands - 1)->getName().data();
```

2021-03-12 13:28 UTC, ruvi-d commented on compiler/codegen/Function.cpp
> +            const char *isSameTypeChar = "is_same_type";
We don't have to initialize this constant every time this loop turns. Move it out to at least the function's root level.

2021-03-12 13:28 UTC, ruvi-d commented on compiler/codegen/Function.cpp
> +            LLVMInstructionRemoveFromParent(wrap(lastInsn));
Use the C++ API here instead. `void Instruction::removeFromParent`

2021-03-12 13:28 UTC, ruvi-d commented on compiler/codegen/Function.cpp
> +            newBBLastInsn = &*--SI;
Why are you doing the `if (SI == splitBB->begin())` check and setting `newBBLastInsn = nullptr;`; only to reassign it in the very next line `newBBLastInsn = &*--SI;`? line 258 and 259 seems redundant. 

Also does `--SI;` have any meaning if `SI == splitBB->begin()` ?

2021-03-12 13:28 UTC, ruvi-d commented on compiler/codegen/Package.cpp
> +using namespace llvm;
Again, if possible only use one

2021-03-12 13:28 UTC, ruvi-d commented on compiler/codegen/Package.cpp
> +            // break;
Delete without commenting unless you have a good reason

2021-03-15 00:52 UTC, ramakotareddy commented on compiler/codegen/Package.cpp
> +            // break;
Fixed

2021-03-15 00:52 UTC, ramakotareddy commented on compiler/codegen/Package.cpp
> +using namespace llvm;
Fixed

2021-03-15 00:53 UTC, ramakotareddy commented on compiler/codegen/Function.cpp
> +            newBBLastInsn = &*--SI;
Fixed

2021-03-15 00:53 UTC, ramakotareddy commented on compiler/codegen/Function.cpp
> +            LLVMInstructionRemoveFromParent(wrap(lastInsn));
Fixed

2021-03-15 00:53 UTC, ramakotareddy commented on compiler/codegen/Function.cpp
> +            const char *isSameTypeChar = "is_same_type";
Fixed

2021-03-15 00:53 UTC, ramakotareddy commented on compiler/codegen/Function.cpp
> +            insnName = callInst->getOperand(totalOperands - 1)->getName().data();
Fixed

2021-03-15 00:53 UTC, ramakotareddy commented on compiler/codegen/Function.cpp
> +using namespace llvm;
Fixed

2021-03-15 00:54 UTC, ramakotareddy commented on compiler/BIRReader.cpp
> +    assert(poolEntry->getTag() == ConstantPoolEntry::tagEnum::TAG_ENUM_CP_ENTRY_FLOAT);
Fixed

2021-03-15 05:13 UTC, ruvi-d requested changes
Any type casts for global variables is broken

2021-03-15 05:13 UTC, ruvi-d commented on compiler/codegen/TypeCastInsn.cpp
> +        break;
Return here instead of break to force Return value optimization. https://en.cppreference.com/w/cpp/language/copy_elision
Also, this might be a good place to return std::string_view instead of const char*.
Otherwise under certain compiler conditions the returned `char const *` will point to invalid stack memory.

2021-03-15 05:13 UTC, ruvi-d commented on compiler/codegen/TypeCastInsn.cpp
> +char const *TypeCastInsn::typeStringMangleName(LLVMTypeRef valType, TypeTag typeTag) {
You are mixing const conventions here. Everywhere else we have been using `west const`.
https://isocpp.org/wiki/faq/const-correctness
This should be `const char *` inline with our conventions. Also note that `char const *` is not equal to `char * const`.

2021-03-15 05:15 UTC, ruvi-d commented
@ramakotareddy : where are the tests to cover the array casts mentioned in #88 ?

2021-03-15 05:53 UTC, ramakotareddy commented on compiler/codegen/Package.cpp
> +    char *charPtr = (char *)concatString;
@ruvi-d, here, we need to increase the pointer by one (charPtr++;) to store NULL character after each string(type name).

2021-03-15 06:11 UTC, ramakotareddy commented on compiler/codegen/TypeCastInsn.cpp
> +        LLVMValueRef strTblPtr = pkgObj->getGlobalLLVMVar(strTblPtrChar);
@Ruvi, From here we are not accessing String Builder Table Pointer, this is just Global pointer will contain the String Table address. We have one Function inside Package ("getStrTableBuilder()") class to access String Table.
I can add seperate function inside Package class to access this string table global pointer if required. Please suggest.

2021-03-15 06:14 UTC, ramakotareddy commented on compiler/codegen/TypeCastInsn.cpp
> +char const *TypeCastInsn::typeStringMangleName(LLVMTypeRef valType, TypeTag typeTag) {
Sorry typing mistake. i will fix

2021-03-15 07:23 UTC, ramakotareddy commented on compiler/codegen/Function.cpp
> +    const char *abortFuncName = "abort";
@Ruvi, i have gone through link(you have shared) and you are right Abort will not de init automatically. 
I have created the issue for this one "Destruct resources from Abort() function #178".

2021-03-15 11:54 UTC, ramakotareddy commented on compiler/codegen/TypeCastInsn.cpp
> +char const *TypeCastInsn::typeStringMangleName(LLVMTypeRef valType, TypeTag typeTag) {
Fixed

2021-03-15 11:54 UTC, ramakotareddy commented on compiler/codegen/TypeCastInsn.cpp
> +        break;
Changed to string_view from const char *.

2021-03-15 11:54 UTC, ramakotareddy commented on compiler/codegen/TypeCastInsn.cpp
> +        LLVMValueRef brCondition __attribute__((unused)) = LLVMBuildIsNotNull(builder, sameTypeResult, "");
Fixed

2021-03-15 11:55 UTC, ramakotareddy commented on compiler/codegen/TypeCastInsn.cpp
> +        pkgObj->getGlobalLLVMVar(lhsOpName);
Fixed

2021-03-15 11:55 UTC, ramakotareddy commented on compiler/codegen/Package.cpp
>          return LLVMPointerType(LLVMInt8Type(), 0);
Fixed

2021-03-15 11:55 UTC, ramakotareddy commented on compiler/codegen/Function.cpp
> +            llvm::Instruction *lastInsn = (&*--ILoc);
Fixed

2021-03-15 11:55 UTC, ramakotareddy commented on compiler/codegen/Function.cpp
> +            assert(newBBLastInsn);
Fixed

2021-03-15 11:58 UTC, ramakotareddy commented on compiler/codegen/TypeCastInsn.cpp
> +        pkgObj->getGlobalLLVMVar(lhsOpName);
Added test case "casting/anyTypeGlobalParam.bal" with global any type variables.

2021-03-15 12:01 UTC, ramakotareddy commented on compiler/codegen/Function.cpp
> +            assert(newBBLastInsn);
Fixed

2021-03-15 12:02 UTC, ramakotareddy commented on compiler/codegen/Package.cpp
> +    LLVMTypeRef charPtrType = LLVMPointerType(LLVMInt8Type(), 0);
Fixed

2021-03-15 12:04 UTC, ramakotareddy commented
Added test case for int arrat typecast(array/arrayAnyTypeCast.bal). I will add more type cast test cases with Array generic changes(float, bool and string).

2021-03-15 15:13 UTC, ruvi-d commented on compiler/codegen/Package.cpp
> +    char *charPtr = (char *)concatString;
I think you can add null character to string with `\0`. I am just looking for a way to avoid the multiple casts that is being done here.

2021-03-15 15:15 UTC, ruvi-d commented on compiler/codegen/TypeCastInsn.cpp
> +        LLVMValueRef strTblPtr = pkgObj->getGlobalLLVMVar(strTblPtrChar);
> I can add seperate function inside Package class to access this string table global pointer if required.

That sounds good

2021-03-15 15:22 UTC, ramakotareddy commented on compiler/codegen/Package.cpp
> +    char *charPtr = (char *)concatString;
@ruvi-d , Initially we tried to add null character but after concat removing all the null values and getting as a one big string (with all the type strings). So we have decided to use like this.

2021-03-15 15:24 UTC, ruvi-d requested changes
Missing the abort test:
```
int[] i = 3;
any ix = i;
float[] j = (float[]) ix;
```
Are you planning to handle it with the generic array support task? If so, let's create an issue to track it

2021-03-15 16:05 UTC, ramakotareddy commented on compiler/codegen/TypeCastInsn.cpp
> +        LLVMValueRef strTblPtr = pkgObj->getGlobalLLVMVar(strTblPtrChar);
Added new API.

2021-03-16 02:51 UTC, ruvi-d commented on compiler/include/Package.h
> +    void setStringBuilderTableGlobalPointer(LLVMValueRef strTblPtr);
make it private

2021-03-16 02:57 UTC, ramakotareddy commented on compiler/include/Package.h
> +    void setStringBuilderTableGlobalPointer(LLVMValueRef strTblPtr);
Fixed

2021-03-16 03:05 UTC, ruvi-d approved these changes

2021-03-16 04:13 UTC, shubhamnarlawar approved these changes

2021-03-16 06:12 UTC, merged