Fix memory leaks
ballerina-platform/nballerina pull request #180
Opened 2021-03-15 14:27 UTC by ruvi-d

## Purpose
Refactor all classes to use pointers more judiciously. 

Resolves #115 
Not in scope : #158  

## Approach
* Avoid using pointers for class member
* Return object references instead of pointers when it can't be nullptr
* Use of const keyword to indicate and enforce immutability 
* Use of unique or shared pointers instead of raw pointers

2021-03-17 12:48 UTC, ruvi-d commented
@ayonam kind reminder to review this PR

2021-03-18 21:51 UTC, ayonam requested changes

2021-03-18 21:51 UTC, ayonam commented on compiler/include/BasicBlock.h
> +class BasicBlock : public Debuggable, public Translatable {
Why do we no longer derive from PackageNode?

2021-03-18 21:51 UTC, ayonam commented on compiler/include/ConstantLoad.h
> -    } val;
Since only one value can be active at a time, why not have this as a union?  The different constructors for different value types can still be there and they could invoke the relevant constructor for value().

2021-03-18 21:51 UTC, ayonam commented on compiler/include/Function.h
> +class Function : public Debuggable, public Translatable {
Again here we don't derive from PackageNode. Shouldn't we be having the Package information with the Function?  We may need to access it for various reasons.  Just my thoughts.

2021-03-18 21:51 UTC, ayonam commented on compiler/include/FunctionCallInsn.h
> +    FunctionCallInsn(std::string _funcName, int argNumber, std::shared_ptr<BasicBlock> nextBB, const Operand &lhs,
What was the relevance of funcVirtual earlier?  Why have we dropped it?  These were added to these classes basis the fields in the BIR.  So unless they are no longer relevant in the BIR, we should not be dropping them.

2021-03-18 21:51 UTC, ayonam commented on compiler/include/FunctionParam.h
> +    FunctionParam(Operand paramOp, Type type) : Operand(std::move(paramOp)), type(std::move(type)) {}
I'm assuming that the name of the operand has been captured while creating the paramOp.

2021-03-18 21:51 UTC, ayonam commented on compiler/include/Location.h
> +    int sLine;
Shouldn't these be const here?  We don't expect them to change, do we?  Besides there are no set methods either.

2021-03-18 21:51 UTC, ayonam commented on compiler/include/Package.h
> -    std::vector<Function *> functions;
I'm assuming that the pointers to the Function objects are being stored in the functionLookUp map and hence this vector is redundant.

2021-03-18 21:51 UTC, ayonam commented on compiler/include/Package.h
> -    inline static const std::string BAL_NIL_VALUE = "bal_nil_value";
Are we now storing the NIL value elsewhere?

2021-03-18 21:51 UTC, ayonam commented on compiler/include/RestParam.h
> -
Don't the RestParams have a name anymore?  I thought the BIR sent a name here.

2021-03-18 21:51 UTC, ayonam commented on compiler/include/TypeCastInsn.h
> -                                          LLVMValueRef rhsRef);
In this function, are we not using the Package anymore?

2021-03-18 21:51 UTC, ayonam commented on compiler/include/Types.h
> +    int flags;
Do we expect to change the flags here?  These are directly obtained from the BIR.  So I don't think we will be changing them once they are set.  Shouldn't this should remain a const?

2021-03-18 21:51 UTC, ayonam commented on compiler/include/interfaces/AbstractInstruction.h
> +class AbstractInstruction : public Debuggable {
Again, why is the Package not made accessible to these classes?  There are times, when we may need it for the LLVM code generation.  I thought Package was the BIR synonym the LLVM Module.

2021-03-19 03:13 UTC, ruvi-d commented on compiler/codegen/InvokableType.cpp
> -} // namespace nballerina
Renamed the class from `InvokableType` to `InvocableType`

2021-03-19 03:21 UTC, ruvi-d commented on compiler/codegen/Types.cpp
> -
Moved the one extra class member supported by MapTypeDecl (memberType) to the Type base class as an optional member. The overhead of introducing MapTypeDecl just to support one additional trivial member seemed unnecessary. If we had used MapTypeDecl, then we would have had to use heap allocated pointers to deal with Type objects and then incur extra overhead for the de-referencing.

2021-03-19 03:35 UTC, ruvi-d commented on compiler/include/BasicBlock.h
> +class BasicBlock : public Debuggable, public Translatable {
The PackageNode interface only had a getPackage() method and that method implementation was moved to the respective classes. It was only used as a private method by their respective classes. Exposing this method as a interface's public method didn't net any benefit.

2021-03-19 03:36 UTC, ruvi-d commented on compiler/include/ConstantLoad.h
> -    } val;
Yes, actually a std::variant (type safe version of union) would make sense here. Will update.

2021-03-19 03:37 UTC, ruvi-d commented on compiler/include/Function.h
> +class Function : public Debuggable, public Translatable {
Commented here: https://github.com/ballerina-platform/nballerina/pull/180#discussion_r597385022

2021-03-19 03:43 UTC, ruvi-d commented on compiler/include/FunctionCallInsn.h
> +    FunctionCallInsn(std::string _funcName, int argNumber, std::shared_ptr<BasicBlock> nextBB, const Operand &lhs,
Currently when we are parsing BIR fields, we are leaving some unused and passing others to the CodeGen class constructors. But some of these fields were being unused in the CodeGen classes as well. So, to make things consistent and easily understand for future developers, I've removed all the unused params from class constructors and marked them as `unused` in the BIRReader. Then by looking at the BIRReader code you know exactly which fields are being used or ignored currently.

2021-03-19 03:45 UTC, ruvi-d commented on compiler/include/FunctionParam.h
> +    FunctionParam(Operand paramOp, Type type) : Operand(std::move(paramOp)), type(std::move(type)) {}
That's right

2021-03-19 03:45 UTC, ruvi-d commented on compiler/include/Package.h
> -    std::vector<Function *> functions;
Yes

2021-03-19 03:52 UTC, ruvi-d commented on compiler/include/Location.h
> +    int sLine;
Using const member variables is discouraged since it makes it non trivial to copy and thus has adverse side effects like preventing moves. The recommendation I've seen is to keep member variables non-const and remove the setter methods instead.
https://www.reddit.com/r/cpp/comments/8wbeom/coding_guideline_avoid_const_member_variables/

2021-03-19 03:54 UTC, ruvi-d commented on compiler/include/Package.h
> -    inline static const std::string BAL_NIL_VALUE = "bal_nil_value";
It's just been moved a few lines above. The diff isn't showing that.

2021-03-19 03:56 UTC, ruvi-d commented on compiler/include/RestParam.h
> -
This change was also done for the same reason as mentioned previously about removing unused fields. 
https://github.com/ballerina-platform/nballerina/pull/180#discussion_r597387522

2021-03-19 03:58 UTC, ruvi-d commented on compiler/include/TypeCastInsn.h
> -                                          LLVMValueRef rhsRef);
A reference to the parent package is already available to this class object. So unless we make this method Static, there was no need to pass a redundant package pointer

2021-03-19 03:59 UTC, ruvi-d commented on compiler/include/Types.h
> +    int flags;
I am following the previously mentioned guidelines about const member variables
https://github.com/ballerina-platform/nballerina/pull/180#discussion_r597389997

2021-03-19 04:01 UTC, ruvi-d commented on compiler/include/interfaces/AbstractInstruction.h
> +class AbstractInstruction : public Debuggable {
Answered in https://github.com/ballerina-platform/nballerina/pull/180#discussion_r597385022

2021-03-19 04:41 UTC, ruvi-d commented on compiler/include/ConstantLoad.h
> -    } val;
Push an update addressing this

2021-03-19 04:43 UTC, ruvi-d commented
@ayonam I've replied to your comments. Please check.

2021-03-22 08:13 UTC, ruvi-d commented
Rebased with master

2021-03-23 18:23 UTC, ayonam commented on compiler/codegen/Types.cpp
> -
Okay.  Got it.  That's fine.

2021-03-23 18:23 UTC, ayonam commented on compiler/include/BasicBlock.h
> +class BasicBlock : public Debuggable, public Translatable {
Accepted.

2021-03-23 18:25 UTC, ayonam commented on compiler/include/FunctionCallInsn.h
> +    FunctionCallInsn(std::string _funcName, int argNumber, std::shared_ptr<BasicBlock> nextBB, const Operand &lhs,
That sounds reasonable.

2021-03-23 18:25 UTC, ayonam commented on compiler/include/RestParam.h
> -
Got it.  Thanks,

2021-03-23 18:26 UTC, ayonam approved these changes

2021-03-24 03:25 UTC, KavinduZoysa approved these changes

2021-03-24 03:27 UTC, merged