Generic Type Array support
ballerina-platform/nballerina pull request #182
Opened 2021-03-15 16:50 UTC by ramakotareddy

Generic type array support (int, float, boolean and String).

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-03-15 19:06 UTC, shubhamnarlawar commented
Please investigate two failing LIT tests in this PR workflow run - 

```
Failed Tests (2):
  Ballerina codegen :: array/booleanArrayLoadAndStore.bal
  Ballerina codegen :: array/stringArrayLoadAndStore.bal
```

2021-03-16 13:19 UTC, ramakotareddy commented
print_str is not working properly with Array Strings. I am investigating.
meanwhile please go through the changes and give your comments.

2021-03-18 02:39 UTC, ramakotareddy commented
Fix the Array string Print issue. Now able to print array string using print_str() rust function.

2021-03-18 02:45 UTC, ramakotareddy commented
I will add float Array test after fix the float print issue.
I will add more tests related to Array's and Array typecast realted tests.

2021-03-18 02:55 UTC, ruvi-d commented
> I will add float Array test after fix the float print issue.
> I will add more tests related to Array's and Array typecast realted tests.

Please also see #188. The mangled type string is not getting passed correctly in current master. Kavindu and I saw the same for Any type returns as well.
I'd suggest adding the patch mention to the #188 to check the string length. And also add test to cover Any type returns.

2021-03-18 02:58 UTC, ramakotareddy commented
@Ruvi, i will investigate this issue and i will send the fix.

2021-03-18 03:12 UTC, ruvi-d requested changes
Some early feedback

2021-03-18 03:12 UTC, ruvi-d commented on compiler/codegen/ArrayInsns.cpp
> +        funcRetType = LLVMPointerType(LLVMInt8Type(), 0);
We have the function `Type::getNameOfType(TypeTag typeTag)` to convert the lhsOpTypeTag to string. You can simply do : `"array_load_"+Type::getNameOfType(lhsOpTypeTag);`

Same for RetType with the `Package::getLLVMTypeOfType(const Type &type)` function

This applies for ArrayStore and ArrayInit commands as well.

2021-03-18 03:12 UTC, ruvi-d commented on compiler/codegen/ArrayInsns.cpp
> -    const char *intArrayLoadChar = "int_array_load";
Why hasn't the `getArrayInitDeclaration()` been not updated to take into account the array type?

2021-03-18 03:12 UTC, ruvi-d commented on runtime/src/lib.rs
> +#[no_mangle]
We need a deinit() function to free the array memory allocation. Please see the `map_deint_int` function for reference.

2021-03-18 03:12 UTC, ruvi-d commented on runtime/src/lib.rs
> +    let n_size = n as usize;
Again I think we need init functions for each type also. Please correct me if otherwise.

2021-03-18 03:19 UTC, ramakotareddy commented on runtime/src/lib.rs
> +    let n_size = n as usize;
For Array init, we are passing only size of the array to rust function (size is i32 type of any array type). Please suggest if have any issues.

2021-03-18 03:19 UTC, ramakotareddy commented on runtime/src/lib.rs
> +#[no_mangle]
I will write deinit() function fror arrays also.

2021-03-18 03:25 UTC, ruvi-d commented on runtime/src/lib.rs
> +    let n_size = n as usize;
`new_init_array` at https://github.com/ballerina-platform/nballerina/blob/master/runtime/src/lib.rs#L123 is creating a vector of i32.. that is not going to work for floats or string right?

2021-03-18 04:07 UTC, ramakotareddy commented on runtime/src/lib.rs
> +    let n_size = n as usize;
I think "let foo: Box<Vec<*mut i32>> = Box::new(Vec::with_capacity(size_t));" here, i32 is vector size only. If we create seperate init function for float and string, we have to pass size of the array to those functions of i32(size) type only right ? here, "Vec<*mut i32>"  mut i32 means vector size. Please correct me if i am wrong.

2021-03-18 04:16 UTC, ramakotareddy commented on runtime/src/lib.rs
> +    let n_size = n as usize;
@Ruvi, i will go through once again with init function and confirm.

2021-03-18 04:21 UTC, ruvi-d commented on runtime/src/lib.rs
> +    let n_size = n as usize;
I am not a Rust expert but it looks like `Vec<T>` mean a vector of T type members: https://doc.rust-lang.org/std/vec/struct.Vec.html#method.new

2021-03-18 04:28 UTC, ramakotareddy commented on runtime/src/lib.rs
> +    let n_size = n as usize;
Same Ruvi  i am also beginer in Rust side. I will cross check once again and i will fix.

2021-03-23 00:49 UTC, ramakotareddy commented on runtime/src/lib.rs
> +#[no_mangle]
Fixed

2021-03-23 00:49 UTC, ramakotareddy commented on compiler/codegen/ArrayInsns.cpp
> -    const char *intArrayLoadChar = "int_array_load";
Fixed

2021-03-23 00:49 UTC, ramakotareddy commented on compiler/codegen/ArrayInsns.cpp
> +        funcRetType = LLVMPointerType(LLVMInt8Type(), 0);
Fixed

2021-03-23 00:49 UTC, ramakotareddy commented on runtime/src/lib.rs
> +    let n_size = n as usize;
Fixed

2021-03-23 12:56 UTC, ruvi-d requested changes

2021-03-23 12:56 UTC, ruvi-d commented on compiler/BIRReader.h
> +    uint32_t elementTypeCpIndex;
Are we going to keep adding class members to ShapeCpInfo for every new Type?
How about bundling the Type specific members in to separate structs (defined inside ShapeCpInfo) and including a std::variant of all the type specific structs in ShapeCpInfo?

2021-03-23 12:56 UTC, ruvi-d commented on compiler/include/ArrayInstructions.h
> +#include "Types.h"
Move this include to the .cpp  since we have Type forward declared here at line 28

2021-03-23 12:56 UTC, ruvi-d commented on compiler/codegen/ArrayInsns.cpp
> +    const string &arrayTypeFuncName = typeStr + "_new_array";
Using const reference to hold rvalues. This is very fragile and might break in unexpected ways when we extend. Just drop the `&`. Repeat for other Array functions too.

PS: Looks like you are not using the static analyser we enabled for master. Please use the provided tooling to spot these kind of issues.

2021-03-23 12:56 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn int_new_array(size: i32) -> *mut Vec<*mut i32> {
`map_init_*` ,  `map_store_*` , `map_store_*` and `box_bal_*` are all appending the type to the end. Shall we stick with the existing convention and rename these functions to the format of `array_<operation>_<type>` ?

2021-03-23 12:56 UTC, ruvi-d commented on runtime/src/lib.rs
> +#[no_mangle]
for line 118-121: you can keep size_t as non mut with something like: `let size = if size > 0 { size } else { 8 };`
Repeat for other new functions.

2021-03-23 12:56 UTC, ruvi-d commented on runtime/src/lib.rs
> +    let mut size_t = size;
Don't we have to save size, so that we can do out of bounds checks for load and store? Or is out of bounds checking being handled by the front end?

2021-03-23 12:56 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn bool_array_store(arr_ptr: *mut Vec<*mut bool>, n: i32, ref_ptr: *mut bool) {
Shouldn't we pass the the primitive values to store by value instead of by reference?

2021-03-23 12:56 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn float_array_load(arr_ptr: *mut Vec<*mut f32>, n: i32) -> *mut f32 {
Shouldn't the return type for primitives be values instead of references?

2021-03-23 15:47 UTC, ramakotareddy commented on compiler/include/ArrayInstructions.h
> +#include "Types.h"
@ruvi-d , I need to include Types.h in header file only because i am using TypeTag enum in header file. Please suggest possiblities here?

2021-03-23 16:17 UTC, ruvi-d commented on compiler/include/ArrayInstructions.h
> +#include "Types.h"
oh I see. Then you should be able to delete the forward declaration on line 28

2021-03-24 14:11 UTC, ramakotareddy commented on compiler/codegen/ArrayInsns.cpp
> +    const string &arrayTypeFuncName = typeStr + "_new_array";
Noted, i will fix

2021-03-24 14:11 UTC, ramakotareddy commented on runtime/src/lib.rs
> +pub extern "C" fn int_new_array(size: i32) -> *mut Vec<*mut i32> {
I will change rust function names.

2021-03-24 16:44 UTC, shubhamnarlawar commented on compiler/BIRReader.h
> +    uint32_t elementTypeCpIndex;
How about inheriting from `ShapeCpInfo` class for every new Type?

2021-03-24 17:05 UTC, ruvi-d commented on compiler/BIRReader.h
> +    uint32_t elementTypeCpIndex;
it's more of an association relationship as opposed to an inheritance relationship. Having a member variable of std::variant models it better imo. Also if you use inheritance,  you will have to pass pointers and then both cast and deference to get access to the member. That's would be a bigger overhead.

2021-03-24 17:07 UTC, ruvi-d commented on compiler/BIRReader.h
> +    uint32_t elementTypeCpIndex;
Here is an example of what I am proposing: https://github.com/ballerina-platform/nballerina/blob/ca55aee11012878c16d910baf4c799d3311feac7/compiler/include/MapInsns.h#L66

2021-03-25 04:23 UTC, ramakotareddy commented on runtime/src/lib.rs
> +#[no_mangle]
Fixed

2021-03-25 04:23 UTC, ramakotareddy commented on runtime/src/lib.rs
> +pub extern "C" fn int_new_array(size: i32) -> *mut Vec<*mut i32> {
Fixed

2021-03-25 04:23 UTC, ramakotareddy commented on compiler/codegen/ArrayInsns.cpp
> +    const string &arrayTypeFuncName = typeStr + "_new_array";
Fixed

2021-03-25 04:23 UTC, ramakotareddy commented on compiler/include/ArrayInstructions.h
> +#include "Types.h"
Fixed

2021-03-26 11:41 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn float_array_load(arr_ptr: *mut Vec<*mut f32>, n: i32) -> *mut f32 {
We have referred it from this repository - 

https://github.com/ballerina-platform/ballerina-lang/blob/30c21cd30607b9f34512aed96015f43debf85764/compiler/ballerina-backend-llvm/src/main/rust/src/lib.rs#L47

2021-03-26 11:42 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn bool_array_store(arr_ptr: *mut Vec<*mut bool>, n: i32, ref_ptr: *mut bool) {
We have referred it from this repository - to use pass by reference

https://github.com/ballerina-platform/ballerina-lang/blob/30c21cd30607b9f34512aed96015f43debf85764/compiler/ballerina-backend-llvm/src/main/rust/src/lib.rs#L35

2021-03-26 12:43 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn bool_array_store(arr_ptr: *mut Vec<*mut bool>, n: i32, ref_ptr: *mut bool) {
I don't think we need to pass by reference for primitives. It just adds an unnecessary overhead.

2021-03-26 12:43 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn float_array_load(arr_ptr: *mut Vec<*mut f32>, n: i32) -> *mut f32 {
commented

2021-03-28 09:13 UTC, ramakotareddy commented on runtime/src/lib.rs
> +pub extern "C" fn bool_array_store(arr_ptr: *mut Vec<*mut bool>, n: i32, ref_ptr: *mut bool) {
Hi Ruvi, I tried with values instead of references but while printing values, printing some garbage values like "RESULT=799838936" for integers and "RESULT=``" for strings.

2021-03-28 09:13 UTC, ramakotareddy commented on runtime/src/lib.rs
> +pub extern "C" fn float_array_load(arr_ptr: *mut Vec<*mut f32>, n: i32) -> *mut f32 {
Replied.

2021-03-28 09:23 UTC, ramakotareddy commented on compiler/BIRReader.h
> +    uint32_t elementTypeCpIndex;
@ruvi-d ,Created separate issue #218 for these Rust changes(below rust comments also included in this new issue).

2021-03-28 10:27 UTC, ramakotareddy commented
Opened new PR #219.

2021-03-28 10:27 UTC, closed without merging

2021-03-28 12:38 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn bool_array_store(arr_ptr: *mut Vec<*mut bool>, n: i32, ref_ptr: *mut bool) {
We are already successfully passing by value for the box operations. Please refer it's implementation https://github.com/ballerina-platform/nballerina/blob/master/runtime/src/lib.rs#L192

2021-03-28 13:04 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn bool_array_store(arr_ptr: *mut Vec<*mut bool>, n: i32, ref_ptr: *mut bool) {
Let's moved this discussion to #219