Support for map initialization
ballerina-platform/nballerina pull request #187
Opened 2021-03-17 08:45 UTC by ruvi-d

## Purpose
Adds support for key/value and spread field initialization of maps (only for `map<int>` types)

Resolves #121 

## Approach
* Key/value initialization is done by calling `map_store` runtime function for each key/value pair
* Spread field initialization via map type is supported
  * The implementation passes the map's reference from the spread field expression to  the runtime; where the fields are copied to the map that is being initialized.

Note: Requires `jballerina-tools-2.0.0-Preview2-nballerina-r2` (updated Ballerina pack) linked in the updated README

## Related PRs
Depends on #180

2021-03-17 08:48 UTC, ruvi-d commented
Generated code examples:
**Ballerina:**
```
public function main() {
    map<int> marks = {sam: 50, jon: 60};
}
```
**LLVM IR**
```
 ModuleID = '$anon.0.0.0'
source_filename = "mapInit.bal"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

@__string_table_ptr = internal global i8* null, align 4
@bal_nil_value = internal global i8* null
@"$annotation_data" = global i8* null, align 4
@.str = private unnamed_addr global [4 x i8] c"sam\00", align 1
@.str.1 = private unnamed_addr global [4 x i8] c"jon\00", align 1

define void @main() {
entry:
  %"%0" = alloca i8*, align 8
  %"%1" = alloca i8*, align 8
  %"%2" = alloca i32, align 4
  %"%4" = alloca i8*, align 8
  %"%5" = alloca i32, align 4
  %"%6" = alloca i8*, align 8
  %"%7" = alloca i32, align 4
  br label %bb0

bb0:                                              ; preds = %entry
  store i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i8** %"%4", align 8
  store i32 50, i32* %"%5", align 4
  store i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str.1, i64 0, i64 0), i8** %"%6", align 8
  store i32 60, i32* %"%7", align 4
  %0 = call i8* @map_new_int()
  store i8* %0, i8** %"%1", align 8
  %"%4_temp" = load i8*, i8** %"%4", align 8
  %"%1_temp" = load i8*, i8** %"%1", align 8
  call void @map_store_int(i8* %"%1_temp", i8* %"%4_temp", i32* %"%5")
  %"%6_temp" = load i8*, i8** %"%6", align 8
  %"%1_temp1" = load i8*, i8** %"%1", align 8
  call void @map_store_int(i8* %"%1_temp1", i8* %"%6_temp", i32* %"%7")
  br label %bb2

bb1:                                              ; No predecessors!
  br label %bb2

bb2:                                              ; preds = %bb1, %bb0
  ret void
}

declare i8* @map_new_int()
declare void @map_store_int(i8*, i8*, i32*)
declare void @map_spread_field_init(i8*, i8*)
```

2021-03-17 08:50 UTC, ruvi-d commented
**Ballerina**
```
public function main() {
	map<int> boys = {Jake:80, Steve:90};
	map<int> girls = {Amy:85, Sam:88};
	map<int> allMarks = {...boys, ...girls};
}
```
**LLVM IR**
```
; ModuleID = '$anon.0.0.0'
source_filename = "map.bal"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

@__string_table_ptr = internal global i8* null, align 4
@bal_nil_value = internal global i8* null
@"$annotation_data" = global i8* null, align 4
@.str = private unnamed_addr global [5 x i8] c"Jake\00", align 1
@.str.1 = private unnamed_addr global [6 x i8] c"Steve\00", align 1
@.str.2 = private unnamed_addr global [4 x i8] c"Amy\00", align 1
@.str.3 = private unnamed_addr global [4 x i8] c"Sam\00", align 1

define void @main() {
entry:
  %"%0" = alloca i8*, align 8
  %"%1" = alloca i8*, align 8
  %"%11" = alloca i8*, align 8
  %"%12" = alloca i32, align 4
  %"%13" = alloca i8*, align 8
  %"%14" = alloca i32, align 4
  %"%15" = alloca i8*, align 8
  %"%16" = alloca i32, align 4
  %"%2" = alloca i32, align 4
  %"%4" = alloca i8*, align 8
  %"%5" = alloca i32, align 4
  %"%6" = alloca i8*, align 8
  %"%7" = alloca i32, align 4
  %"%8" = alloca i8*, align 8
  %"%9" = alloca i32, align 4
  br label %bb0

bb0:                                              ; preds = %entry
  store i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.str, i64 0, i64 0), i8** %"%4", align 8
  store i32 80, i32* %"%5", align 4
  store i8* getelementptr inbounds ([6 x i8], [6 x i8]* @.str.1, i64 0, i64 0), i8** %"%6", align 8
  store i32 90, i32* %"%7", align 4
  %0 = call i8* @map_new_int()
  store i8* %0, i8** %"%1", align 8
  %"%4_temp" = load i8*, i8** %"%4", align 8
  %"%1_temp" = load i8*, i8** %"%1", align 8
  call void @map_store_int(i8* %"%1_temp", i8* %"%4_temp", i32* %"%5")
  %"%6_temp" = load i8*, i8** %"%6", align 8
  %"%1_temp1" = load i8*, i8** %"%1", align 8
  call void @map_store_int(i8* %"%1_temp1", i8* %"%6_temp", i32* %"%7")
  store i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str.2, i64 0, i64 0), i8** %"%11", align 8
  store i32 85, i32* %"%12", align 4
  store i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str.3, i64 0, i64 0), i8** %"%13", align 8
  store i32 88, i32* %"%14", align 4
  %1 = call i8* @map_new_int()
  store i8* %1, i8** %"%8", align 8
  %"%11_temp" = load i8*, i8** %"%11", align 8
  %"%8_temp" = load i8*, i8** %"%8", align 8
  call void @map_store_int(i8* %"%8_temp", i8* %"%11_temp", i32* %"%12")
  %"%13_temp" = load i8*, i8** %"%13", align 8
  %"%8_temp2" = load i8*, i8** %"%8", align 8
  call void @map_store_int(i8* %"%8_temp2", i8* %"%13_temp", i32* %"%14")
  %2 = call i8* @map_new_int()
  store i8* %2, i8** %"%15", align 8
  %"%15_temp" = load i8*, i8** %"%15", align 8
  %"%1_temp3" = load i8*, i8** %"%1", align 8
  call void @map_spread_field_init(i8* %"%15_temp", i8* %"%1_temp3")
  %"%15_temp4" = load i8*, i8** %"%15", align 8
  %"%8_temp5" = load i8*, i8** %"%8", align 8
  call void @map_spread_field_init(i8* %"%15_temp4", i8* %"%8_temp5")
  br label %bb2

bb1:                                              ; No predecessors!
  br label %bb2

bb2:                                              ; preds = %bb1, %bb0
  ret void
}

declare i8* @map_new_int()
declare void @map_store_int(i8*, i8*, i32*)
declare void @map_spread_field_init(i8*, i8*)
```

2021-03-24 16:21 UTC, ruvi-d commented
@ayonam please review

2021-03-24 17:37 UTC, manuranga commented on runtime/src/lib.rs
> +        assert!(!ptr_source.is_null());
If possible, shell we move asset out of unsafe ? goal is to keep unsafe sections to a minimal.

2021-03-24 17:45 UTC, manuranga commented on runtime/src/bal_map.rs
> +                self.map.insert(String::from(key), *value);
instead adding one by one, can we use `extend` function of map?

2021-03-25 07:45 UTC, ruvi-d commented on runtime/src/lib.rs
> +        assert!(!ptr_source.is_null());
will do

2021-03-25 07:50 UTC, ruvi-d commented on runtime/src/bal_map.rs
> +                self.map.insert(String::from(key), *value);
will do

2021-03-25 08:00 UTC, ruvi-d commented
@manuranga : please verify the review comment fixes

2021-03-27 11:38 UTC, ayonam requested changes

2021-03-27 11:38 UTC, ayonam commented on compiler/codegen/StructureInsn.cpp
> +                                      funcObj.getLLVMLocalOrGlobalVar(keyVal.getValue()));
I feel that this code should go into the translate function.  This initialization is part of the translation itself.  The map instruction that we got from BIR already had the initialization in it.  So the translation should be for the entire BIR map instruction including its initialization.

2021-03-27 11:38 UTC, ayonam commented on compiler/codegen/StructureInsn.cpp
> +        llvm_unreachable("Only int type maps are currently supporte");
Small typo here.  The last 'd' in the "supported" is missing.

2021-03-27 11:38 UTC, ayonam commented on compiler/include/MapInsns.h
> +class MapConstruct {
Shouldn't the MapConstruct derive from a NonTerminatorInsn?  The construction of the map is a BIR instruction, isn't it?

2021-03-27 11:38 UTC, ayonam commented on runtime/src/lib.rs
>      let bal_map = unsafe {
If we are already asserting that ptr is not NULL, then does this need to be marked as unsafe?  Or is this because, the ptr could be non-NULL but junk?

2021-03-27 11:38 UTC, ayonam commented on runtime/src/lib.rs
> +    println!("length={}", map_src.length());
I think you are using this print in the CHECK lines in your tests, right?  I would rather have this print moved to the tests, wherever needed, instead of being in the library.

2021-03-28 11:26 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +    return Type(type, name);
Looks like we never used the Type's flags. So similar to how we handled unused BIR info in the memory leak fix PR, I've removed it from this codegen class for consistency and code coverage improvement.

2021-03-28 11:30 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +    }
Adding support array initialization isn't non-trivial unfortunately. There we need to update the runtime and tests too. Let's take it up separately under #85

2021-03-28 11:32 UTC, ruvi-d commented on test/map/mapInitSpreadField.bal
> +// CHECK: length=4
I'm printing it from the runtime as a temporary stop gap till we have #128. Will be addressing it under this sprint.

2021-03-28 11:45 UTC, ruvi-d commented on compiler/codegen/StructureInsn.cpp
> +                                      funcObj.getLLVMLocalOrGlobalVar(keyVal.getValue()));
This logic is part of the `StructureInsn::translate()` function which is the virtual translate function for non-terminating instructions. This function also calls another private method called `mapInstructionTranslate()`, which calls the runtime to create the BalMap object. I suppose that this function name might have caused some confusing. 
If I rename `mapInstructionTranslate()` as `mapCreateTranslate()` and put the initialization logic you highlighted here into a function called `mapInitTranslate()`, will that address your concern?

2021-03-28 11:46 UTC, ruvi-d commented on compiler/codegen/StructureInsn.cpp
> +        llvm_unreachable("Only int type maps are currently supporte");
Noted. Will fix.

2021-03-28 11:50 UTC, ruvi-d commented on compiler/include/MapInsns.h
> +class MapConstruct {
`class MapStoreInsn : public NonTerminatorInsn` is the Instruction class. `MapConstruct` is the new class I created to hold the init information. The name `MapConstruct` maps to the BIR's `mapping_constructor` field.

2021-03-28 11:55 UTC, ruvi-d commented on runtime/src/lib.rs
>      let bal_map = unsafe {
Yes I believe so. The next bit of logic is the pointer de-referencing which is still unsfae even if the pointer is not null.

2021-03-28 12:05 UTC, ruvi-d commented on runtime/src/lib.rs
> +    println!("length={}", map_src.length());
Yes. But this is a temp stop gap till be have #85. Will be handling this correctly when when I implement #85 this sprint.

2021-03-28 12:13 UTC, ruvi-d commented on compiler/codegen/StructureInsn.cpp
> +                                      funcObj.getLLVMLocalOrGlobalVar(keyVal.getValue()));
Pushed a commit with this change.

2021-03-28 12:18 UTC, ruvi-d commented
@ayonam : please review my responses

2021-03-28 20:54 UTC, ayonam commented on compiler/BIRReader.cpp
> +    return Type(type, name);
Okay.  That's fine.

2021-03-28 20:58 UTC, ayonam commented on compiler/BIRReader.cpp
> +    }
You probably meant to say "isn't trivial".  :-)
Let's do it in PR #85 
But, then add a note in that PR that we need to ensure that the functionality expected of this PR vis-a-vis the array initialization part is taken care of by that one.

2021-03-28 21:00 UTC, ayonam commented on test/map/mapInitSpreadField.bal
> +// CHECK: length=4
Okay.  Actually, I think I mentioned this in some comment for some PR. Can't remember which one.  But that print should come here.  We should be able to print the length of the map by calling the size function for the map.

2021-03-28 21:03 UTC, ayonam commented on compiler/codegen/StructureInsn.cpp
> +                                      funcObj.getLLVMLocalOrGlobalVar(keyVal.getValue()));
Yes, that makes sense.

2021-03-28 21:07 UTC, ayonam commented on compiler/include/MapInsns.h
> +class MapConstruct {
Okay.  But then, this should still have some parent class, isn't it?  This is not a standalone class by itself.  It's relationship is with the Map and its associated classes.  That relationship is not reflected here.  I still feel that if it is derived out of NonTerminatorInsn and then made a friend of the MapStoreInsn class, that relationship may get reflected properly.  Or if you have some better idea to represent the interdependence, then please put forth your thoughts.

2021-03-28 21:08 UTC, ayonam commented on runtime/src/lib.rs
>      let bal_map = unsafe {
Okay.  Got it.

2021-03-28 21:10 UTC, ayonam commented on runtime/src/lib.rs
> +    println!("length={}", map_src.length());
But then, do we really need to wait for #85?  From the test case, we should be able to call map.length(), which should return the length, isn't it?

2021-03-29 03:14 UTC, ruvi-d commented on compiler/include/MapInsns.h
> +class MapConstruct {
I see your point. But they are both plain-old-data type classes and don't have any of the properties of `NonTerminatorInsn`. How about if I make `SpreadField` and `KeyValue` nested classes of `MapStoreInsn:NonTerminatorInsn`? I think that better models the relationship
This is the change I am proposing: https://github.com/ruvi-d/nballerina/commit/6877f30275d9a3d474a3a09644ab61f300b6336d

2021-03-29 03:22 UTC, ruvi-d commented on runtime/src/lib.rs
> +    println!("length={}", map_src.length());
We can create a new run time function and call it from the LLVM codegen side to print to length. But that's a lot of code that will be thrown away with #85. Also, print length doesn't actually verify that the correct values have been stored; we need to load the values back to correctly validate the values. Since we will have #85 in a few days, shall we leave this "stop gap solution" in for this PR?

2021-03-29 04:11 UTC, manuranga approved these changes

2021-03-29 05:31 UTC, ayonam commented on runtime/src/lib.rs
> +    println!("length={}", map_src.length());
Yes, let's go ahead with your suggestion for the time being.

2021-03-29 05:54 UTC, ayonam commented on compiler/include/MapInsns.h
> +class MapConstruct {
Yes, this looks fine.

2021-03-29 08:39 UTC, ayonam approved these changes

2021-03-29 08:48 UTC, merged