Add windows weekly build
ballerina-platform/nballerina pull request #189
Opened 2021-03-19 04:14 UTC by KavinduZoysa

## Purpose
$subject
Fixes #123 

## Goals
Adding a window weekly build to test the changes in windows

2021-03-19 05:19 UTC, ruvi-d commented on .github/workflows/WindowsWeeklyBuild.yml
> +          git clone https://github.com/llvm/llvm-project.git
We can download only the tagged llvm-core folder src from here : https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.1/llvm-11.0.1.src.tar.xz
This should help speed things up.

2021-03-19 05:19 UTC, ruvi-d commented on .github/workflows/WindowsWeeklyBuild.yml
> +          msbuild build\INSTALL.vcxproj /p:configuration=release
try this: `cmake --build .\build -t install -- /p:configuration=Release`

2021-03-19 05:19 UTC, ruvi-d commented on .github/workflows/WindowsWeeklyBuild.yml
> +      - name: Build LLVM
Enable build cache for LLVM

2021-03-19 05:19 UTC, ruvi-d commented on test/CMakeLists.txt
> +  COMMAND python ${CMAKE_SOURCE_DIR}/test/run_lit_tests.py "${CMAKE_CURRENT_BINARY_DIR}" -v
Let's remove the shebang from the run_lit_tests.py file. 
Also should this be `python` or `python3` ? I think `python` doesn't automatically redirect to python3 by default on Ubuntu

2021-03-21 15:19 UTC, KavinduZoysa commented on .github/workflows/WindowsWeeklyBuild.yml
> +          git clone https://github.com/llvm/llvm-project.git
I was unable to find a way to extract the source using `tar` command. Shall we keep it like this. It only takes a couple of minutes.

2021-03-21 15:19 UTC, KavinduZoysa commented on .github/workflows/WindowsWeeklyBuild.yml
> +          msbuild build\INSTALL.vcxproj /p:configuration=release
It is working.

2021-03-21 15:19 UTC, KavinduZoysa commented on .github/workflows/WindowsWeeklyBuild.yml
> +      - name: Build LLVM
Done

2021-03-21 15:19 UTC, KavinduZoysa commented on test/CMakeLists.txt
> +  COMMAND python ${CMAKE_SOURCE_DIR}/test/run_lit_tests.py "${CMAKE_CURRENT_BINARY_DIR}" -v
Removed the shebang.
I tested the python keyword in both Linux and windows, both are picking the correct version.

2021-03-22 03:42 UTC, ruvi-d commented on .github/workflows/WindowsWeeklyBuild.yml
> +          git clone https://github.com/llvm/llvm-project.git
Mingw has tar support. I believe it should be pretty easy to use it instead of the git clone

2021-03-22 03:51 UTC, ruvi-d requested changes

2021-03-22 03:51 UTC, ruvi-d commented on .github/workflows/WindowsWeeklyBuild.yml
> +          cmake -DLLVM_CCACHE_DIR=..\..\llvm-cache -DCMAKE_BUILD_TYPE=Release -Thost=x64 -G "Visual Studio 16 2019" -A x64 -DLLVM_USE_CRT_RELEASE=MT -DCMAKE_INSTALL_PREFIX=install -S . -B build\
This ccache won't persist between builds. 
I was suggesting something like this: https://github.com/ballerina-platform/nballerina/blob/c95618a9cac95d649264e0d73f13f1fe2bdfbc2e/.github/workflows/PRCheck.yml#L21

2021-03-22 03:51 UTC, ruvi-d commented on .github/workflows/WindowsWeeklyBuild.yml
> +      - name: Build LLVM
commented

2021-03-22 03:51 UTC, ruvi-d commented on test/CMakeLists.txt
> +  COMMAND python ${CMAKE_SOURCE_DIR}/test/run_lit_tests.py "${CMAKE_CURRENT_BINARY_DIR}" -v
This maybe a problem for older distros and for people with both python2 and python3 installed. If there is no good reason to not make this `python3`, I'd suggest changing this to python3

2021-03-22 04:05 UTC, KavinduZoysa commented on test/CMakeLists.txt
> +  COMMAND python ${CMAKE_SOURCE_DIR}/test/run_lit_tests.py "${CMAKE_CURRENT_BINARY_DIR}" -v
https://github.com/ballerina-platform/nballerina/pull/189#discussion_r598409237, I forgot to mention one thing here, I tested `python3` command in windows build. Then it does not run command. After I try `python3` command in windows machine, it opens up GUI on windows.

2021-03-22 07:24 UTC, ruvi-d commented on test/CMakeLists.txt
> +  COMMAND python ${CMAKE_SOURCE_DIR}/test/run_lit_tests.py "${CMAKE_CURRENT_BINARY_DIR}" -v
oh.. I see

2021-03-22 07:33 UTC, ruvi-d commented on .github/workflows/WindowsWeeklyBuild.yml
> +      - name: Build LLVM
@KavinduZoysa : looks like you need to manually check the cache before Executing `Build LLVM` 
https://github.com/actions/cache
https://github.com/KyleMayes/install-llvm-action

2021-03-28 06:51 UTC, KavinduZoysa commented on test/CMakeLists.txt
> +  COMMAND python ${CMAKE_SOURCE_DIR}/test/run_lit_tests.py "${CMAKE_CURRENT_BINARY_DIR}" -v
Added a check for safety.

2021-03-28 06:57 UTC, KavinduZoysa commented on .github/workflows/WindowsWeeklyBuild.yml
> +          git clone https://github.com/llvm/llvm-project.git
Let's fix it in this issue https://github.com/ballerina-platform/nballerina/issues/208

2021-03-28 06:57 UTC, KavinduZoysa commented on .github/workflows/WindowsWeeklyBuild.yml
> +      - name: Build LLVM
Let's fix it in this issue https://github.com/ballerina-platform/nballerina/issues/208

2021-03-28 12:30 UTC, ruvi-d approved these changes

2021-03-29 04:40 UTC, Kishanthan commented on test/CMakeLists.txt
> +
Missing EoF line.

2021-03-29 10:56 UTC, KavinduZoysa commented on test/CMakeLists.txt
> +
Fixed

2021-03-29 14:31 UTC, Kishanthan approved these changes

2021-03-29 19:02 UTC, merged