Box the data in any type
ballerina-platform/nballerina pull request #191
Opened 2021-03-19 10:00 UTC by KavinduZoysa

## Purpose
$subject

Fixes #190

## Approach
Bring the data of any value to heap using box.

2021-03-19 10:41 UTC, ruvi-d requested changes
Suggested some improvements

2021-03-19 10:41 UTC, ruvi-d commented on test/casting/anyTypeReturn.bal
> +    return 0.0;
Change to something like 2.5, so that we can verify the return val

2021-03-19 10:41 UTC, ruvi-d commented on compiler/include/TypeCastInsn.h
> +    LLVMValueRef boxValue(LLVMModuleRef &modRef, LLVMValueRef paramRef, TypeTag typeTag);
Make the new functions private

2021-03-19 10:41 UTC, ruvi-d commented on runtime/src/lib.rs
> +}
Need to add functions to free (deinit) the pointers

2021-03-19 10:41 UTC, ruvi-d commented on compiler/codegen/TypeCastInsn.cpp
> +bool TypeCastInsn::isBoxValueSupport(TypeTag typeTag) {
make static

2021-03-19 10:41 UTC, ruvi-d commented on compiler/codegen/TypeCastInsn.cpp
> +        new LLVMValueRef();
default should be an error

2021-03-19 10:41 UTC, ruvi-d commented on compiler/codegen/TypeCastInsn.cpp
> +}
You can make this one function by adding a Type param. We have functions to convert Type to string and Type to LLVMType, so no need to duplicate the code.

2021-03-19 18:25 UTC, KavinduZoysa commented on compiler/include/TypeCastInsn.h
> +    LLVMValueRef boxValue(LLVMModuleRef &modRef, LLVMValueRef paramRef, TypeTag typeTag);
Changed

2021-03-19 18:26 UTC, KavinduZoysa commented on runtime/src/lib.rs
> +}
Added

2021-03-19 18:26 UTC, KavinduZoysa commented on compiler/codegen/TypeCastInsn.cpp
> +}
Changed

2021-03-19 19:28 UTC, KavinduZoysa commented on compiler/codegen/TypeCastInsn.cpp
> +bool TypeCastInsn::isBoxValueSupport(TypeTag typeTag) {
Changed

2021-03-19 19:31 UTC, KavinduZoysa commented on compiler/codegen/TypeCastInsn.cpp
> +        new LLVMValueRef();
In here https://github.com/ballerina-platform/nballerina/pull/191/files#diff-6b9f0def66334b86f004fd973fd9137ff1d79244d97526871c61ffc273326f5eR164, I am checking the values that support box for now, others cases work as previous (bit casting), I think we do not need to throw and error. Anyway this line has changed to return `LLVMValueRef()`

2021-03-19 19:33 UTC, KavinduZoysa commented on test/casting/anyTypeReturn.bal
> +    return 0.0;
We have to fix this issue https://github.com/ballerina-platform/nballerina/issues/192 for that.

2021-03-22 03:13 UTC, ruvi-d commented on compiler/include/TypeCastInsn.h
> +    LLVMValueRef boxValue(LLVMModuleRef &modRef, LLVMValueRef paramRef, TypeTag typeTag);
`isSameType()` and `isBoxValueSupport()` are still public.
Please move `typeStringMangleName()` also

2021-03-22 03:26 UTC, ruvi-d requested changes

2021-03-22 03:26 UTC, ruvi-d commented on compiler/codegen/TypeCastInsn.cpp
> +        return generateBoxValueFunc(modRef, paramTypeRef, "box_bal_bool");
Can we generate these function programmatically like :
```
std::string functionName = "box_bal_";
functionName += Type::getNameOfType(typeTag);
```

2021-03-22 03:34 UTC, ruvi-d commented on compiler/codegen/TypeCastInsn.cpp
> +        new LLVMValueRef();
This will be a potential pitfall when someone tries to extend the functionality in the future.
I think something like a `llvm_unreachable()` would make more sense here.

2021-03-22 04:29 UTC, KavinduZoysa commented on compiler/include/TypeCastInsn.h
> +    LLVMValueRef boxValue(LLVMModuleRef &modRef, LLVMValueRef paramRef, TypeTag typeTag);
Fixed

2021-03-22 04:29 UTC, KavinduZoysa commented on compiler/codegen/TypeCastInsn.cpp
> +        new LLVMValueRef();
Removed this function

2021-03-22 04:29 UTC, KavinduZoysa commented on compiler/codegen/TypeCastInsn.cpp
> +        return generateBoxValueFunc(modRef, paramTypeRef, "box_bal_bool");
Yes, changed

2021-03-22 05:58 UTC, ruvi-d approved these changes

2021-03-22 06:24 UTC, manuranga commented on runtime/src/lib.rs
> +pub extern "C" fn deint_box_bal_int(ptr: *mut i32) {
wouldn't `unbox` be more meaningful

2021-03-22 06:30 UTC, KavinduZoysa commented on runtime/src/lib.rs
> +pub extern "C" fn deint_box_bal_int(ptr: *mut i32) {
+1, changed

2021-03-22 06:35 UTC, manuranga commented on compiler/codegen/TypeCastInsn.cpp
> +    LLVMValueRef boxBoolFuncRef = getPackage()->getFunctionRef(functionName);
`Bool` here is not valid anymore.

2021-03-22 06:43 UTC, KavinduZoysa commented on compiler/codegen/TypeCastInsn.cpp
> +    LLVMValueRef boxBoolFuncRef = getPackage()->getFunctionRef(functionName);
Fixed

2021-03-22 07:06 UTC, manuranga approved these changes

2021-03-22 07:43 UTC, merged