Fix is_type_check for Array types is broken
ballerina-platform/nballerina pull request #193
Opened 2021-03-20 00:38 UTC by ramakotareddy

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-03-21 14:00 UTC, KavinduZoysa commented
@ramakotareddy, please update the PR description.

2021-03-21 14:02 UTC, KavinduZoysa commented on compiler/codegen/Package.cpp
> +    strBuilder->finalize();
Do we need to call finalize in both places?

2021-03-21 14:05 UTC, KavinduZoysa commented on compiler/codegen/Package.cpp
> +    std::map<std::string, std::vector<LLVMValueRef>>::iterator itr1;
There is not an usage of `itr1`

2021-03-21 14:12 UTC, KavinduZoysa commented on compiler/codegen/Package.cpp
> +    }
I think, since `structElementStoreInst` is a map, it's key(typeString) is unique, we can get concatenated string using on for loop.
Please check, maybe I am wrong

2021-03-21 15:15 UTC, ramakotareddy commented on compiler/codegen/Package.cpp
> +    strBuilder->finalize();
Fixed. By mistake added in two places.

2021-03-21 15:15 UTC, ramakotareddy commented on compiler/codegen/Package.cpp
> +    std::map<std::string, std::vector<LLVMValueRef>>::iterator itr1;
Fixed

2021-03-21 15:16 UTC, ramakotareddy commented on compiler/codegen/Package.cpp
> +    }
Fixed.

2021-03-21 15:27 UTC, KavinduZoysa commented on compiler/codegen/Package.cpp
> +    }
Can't we reduce this logic to one for loop, because the key(`typeString`) of `structElementStoreInst` is unique?

2021-03-21 15:44 UTC, ramakotareddy commented on compiler/codegen/Package.cpp
> +    }
No, because typeString position will change from first loop to second loop based on offset values(min to max) after finalizing the string builder table.

2021-03-22 03:02 UTC, ruvi-d requested changes

2021-03-22 03:02 UTC, ruvi-d commented on compiler/codegen/Package.cpp
> +        concatString = concatString + element.second;
use `.append()` or `+=` operator here

2021-03-22 03:07 UTC, ruvi-d commented on compiler/codegen/Package.cpp
> +    }
I am with Kavindu here.. Looks like it can be combined as:
```
std::string concatString;
for (const auto &element : structElementStoreInst) {
        const std::string &typeString = element.first;
        size_t finalOrigOffset = strBuilder->getOffset(element.first);
        stringOffsetAfterFinalize.insert({finalOrigOffset, typeString});
       concatString.append(typeString);
    }
```

2021-03-22 03:25 UTC, KavinduZoysa commented on compiler/codegen/Package.cpp
> +    }
+1 Ruvi, that is what I meant.

2021-03-22 04:14 UTC, ramakotareddy commented on compiler/codegen/Package.cpp
> +    }
@ruvi-d , in the first loop, type strings are not in order comapre to String builder table offset values. why because, structElementStoreInst in this map first(primary) element is String(typeString) and map fields are changed to alphabet order after inserting values into this Map.
E.g: We have inserted strings into string builder table "__X,  __I" order. But from this map entries are " __I, __X" getting from first loop(unexpected). When we creating concatString from first loop, order is mismatching.
And when we are accessing string from string table(offset with 3), getting '__X' insted of '__I'.

Because of this, first we are changing offset values and storing it to new Map, first element is offset and fields will reorder based on offset values(min to max). when we will create concatString, will get correct order as per string Table string offset values.

I have tested as per you above suggestion, but getting wrong typestrings(using print functions from Rust file).

2021-03-22 04:19 UTC, ramakotareddy commented on compiler/codegen/Package.cpp
> +        concatString = concatString + element.second;
I will change

2021-03-22 04:31 UTC, ramakotareddy commented on compiler/codegen/Package.cpp
> +        concatString = concatString + element.second;
Fixed

2021-03-22 04:34 UTC, ruvi-d commented on compiler/codegen/Package.cpp
> +    }
Got it. 
Still, creating a new map just to order the strings based on the index is very inefficient.  How about creating a vector of pairs (index, string) and then sorting it on one go? Or better yet iterate a based on the StringTableBuilder offset and then look up the string from structElementStoreInst.

2021-03-22 05:34 UTC, ruvi-d commented
As discussed let's add another test case that creates multiple stringBuilder entries that are not in alphabetical order so that we can cover the specific bug addressed by this PR.

2021-03-22 06:27 UTC, ramakotareddy commented on compiler/codegen/Package.cpp
> +    }
Fixed

2021-03-22 06:28 UTC, ramakotareddy commented
Added test cases

2021-03-22 07:49 UTC, ruvi-d requested changes

2021-03-22 07:49 UTC, ruvi-d commented on compiler/codegen/Package.cpp
> +    std::vector<std::pair<int, std::string>> offsetStringPair;
pair should be <size_t,string>

2021-03-22 07:49 UTC, ruvi-d commented on compiler/codegen/Package.cpp
> +
Use `std::vector.reserve(size)` to set the capacity of offsetStringPair. Otherwise the vector's storage will resize on .push_back

2021-03-22 07:49 UTC, ruvi-d commented on test/casting/multipleStringBuilderEntries.bal
> +     	print_str(s11);
int and float values are no checked here. Use a more `if` checks or additional prints to validate their values too.

2021-03-22 09:19 UTC, ramakotareddy commented on compiler/codegen/Package.cpp
> +    std::vector<std::pair<int, std::string>> offsetStringPair;
Fixed

2021-03-22 09:19 UTC, ramakotareddy commented on compiler/codegen/Package.cpp
> +
Fixed

2021-03-22 09:22 UTC, ramakotareddy commented on test/casting/multipleStringBuilderEntries.bal
> +     	print_str(s11);
Fixed

2021-03-22 09:25 UTC, ruvi-d approved these changes

2021-03-22 09:30 UTC, KavinduZoysa approved these changes

2021-03-22 09:30 UTC, merged