Support for optional type
ballerina-platform/nballerina pull request #200
Opened 2021-03-24 10:07 UTC by KavinduZoysa

## Purpose
$subject
Fixes #173

2021-03-24 15:55 UTC, ruvi-d commented
Shall we add a test case for global optional variables too?

2021-03-24 17:39 UTC, KavinduZoysa commented
> And what about optional complex types like arrays and maps?

What you mean here is, `map<int>? marksOrNil = {};` or `map<int?> marks = {};`?

2021-03-25 04:24 UTC, ruvi-d commented
Only `map<int>?` at the moment because we only have support for map's of int type

2021-03-26 08:06 UTC, ruvi-d requested changes

2021-03-26 08:06 UTC, ruvi-d commented on runtime/src/lib.rs
> +    destination.remove(0);
remove looks like a very expensive operation to run twice like this on the same string. 
I think you can use string slices and ranges for this like: `let filtered_source = &source[2..];` 
Please check

2021-03-26 08:10 UTC, ruvi-d commented on runtime/src/lib.rs
> +    destination.remove(0);
i suppose that we should also do a length check

2021-03-28 12:27 UTC, ruvi-d approved these changes

2021-03-28 20:50 UTC, ayonam requested changes

2021-03-28 20:50 UTC, ayonam commented on test/optional_type/basic_optional_types3.bal
> +    printu32(231);
This test doesn't make much sense other than ascertaining that the compiler is generating some code or not.  How correct is the code is not reflected by this test.  So the value 'n' needs to have some kind of check to ensure that the computation we performed, went as per expectation.

2021-03-28 20:50 UTC, ayonam commented on test/optional_type/optional_type_in_array.bal
> +    int[]? arrOrNil = [];
We should have an initializer here for arrOrNil such that arrOrNil[0] has a value other than 32 to start with.  Thereafter the assignment to arr[0] should overwrite that and we should check if we got the new value or not.

2021-03-28 20:50 UTC, ayonam commented on test/optional_type/optional_type_in_func_arg1.bal
> +    printu32(foo(32));
There should also be a case where we pass a NIL to foo and check whether we print as expected.

2021-03-28 20:50 UTC, ayonam commented on test/optional_type/optional_type_in_func_arg2.bal
> +    print_str(foo("Test"));
Similar check here for a NIL being passed to foo().

2021-03-28 20:50 UTC, ayonam commented on test/optional_type/optional_type_in_global_var.bal
> +    a = 24;
This assignment should be a value other than 24.  Then we should see if we are actually assigning to the right location and the old value is being overwritten or not.

2021-03-28 20:50 UTC, ayonam commented on test/optional_type/optional_type_in_map.bal
> +    marks["jon"] = 60;
Again, this test should start with an assigned value in marksOrNil.  Then assign a different value to marks["jon"] and see if the assignment went through properly.

2021-03-28 20:50 UTC, ayonam commented on test/optional_type/optional_type_in_return.bal
> +    return i;
You could return i + 1 to ensure that the call is not optimized out and the passed value printed.

2021-03-29 03:44 UTC, ruvi-d commented on runtime/src/lib.rs
> +    if (source.len() < 2) || (destination.len() < 2) {
IMO spurious string checks shouldn't be part of a release build. It's not possible unless there is a bug in the LLVM codegen. How about something like a debug build only `assert` (like we do in C++) for both underscores and length checks?

Regarding the length value. I think `<2` is correct since length of 3 is a valid string and 2 isn't.

2021-03-29 07:37 UTC, KavinduZoysa commented on test/optional_type/optional_type_in_return.bal
> +    return i;
Fixed

2021-03-29 07:37 UTC, KavinduZoysa commented on test/optional_type/optional_type_in_map.bal
> +    marks["jon"] = 60;
Fixed

2021-03-29 07:37 UTC, KavinduZoysa commented on test/optional_type/optional_type_in_global_var.bal
> +    a = 24;
Fixed

2021-03-29 07:37 UTC, KavinduZoysa commented on test/optional_type/optional_type_in_array.bal
> +    int[]? arrOrNil = [];
Fixed

2021-03-29 07:37 UTC, KavinduZoysa commented on compiler/codegen/TypeCastInsn.cpp
> +        LLVMValueRef inherentTypeIdx = LLVMBuildStructGEP(builder, rhsOpRef, 0, inherentTypeChar);
Fixed

2021-03-29 08:35 UTC, KavinduZoysa commented on test/optional_type/basic_optional_types3.bal
> +    printu32(231);
@ayonam, I agree with you. But here we have a limitation that still we did not implement the `is-expr`(https://github.com/ballerina-platform/nballerina/issues/220). Ideally, we need to do a type check here, like `x is ()`. 

Also, we cannot do a type check like `n is ()` because it is a compile-time error. 
`unnecessary condition: expression will always evaluate to 'true'`

What we can do is assert the runtime error if `<()>x` fails, which is still a limitation.

```
    print_str("RESULT=");
    printu32(231);
```
I have a reason to add the above 2 lines. Based on the result return by runtime type checking(`is_same_type`) we split the basic block into two(split and abort). Above two lines are placed inside the `.split` basic block and if runtime type check passes `RESULT=231` should be printed. I know this is not a good approach, but with the current limitations I cannot do something better than this, until we fix https://github.com/ballerina-platform/nballerina/issues/220.

2021-03-29 08:38 UTC, KavinduZoysa commented on test/optional_type/optional_type_in_func_arg1.bal
> +    printu32(foo(32));
We have to wait until we fix this issue https://github.com/ballerina-platform/nballerina/issues/220 to check the nil type

2021-03-29 08:38 UTC, KavinduZoysa commented on test/optional_type/optional_type_in_func_arg2.bal
> +    print_str(foo("Test"));
We have to wait until we fix this issue https://github.com/ballerina-platform/nballerina/issues/220 to check the nil type

2021-03-29 10:08 UTC, ayonam commented on runtime/src/lib.rs
> +    if (source.len() < 2) || (destination.len() < 2) {
Okay.  You can have an assert in the debug builds.  But usually, we have situations where it is llvm_unreachable() that is used.  That could be a better way.

If length of 3 is valid string then the check should be <=2 or <3 for an assertion to fail.

2021-03-29 10:10 UTC, ayonam commented on test/optional_type/basic_optional_types3.bal
> +    printu32(231);
Yes, I agree with you.  But we should add a note in the relevant PR for the implementation of the <()>x that this test should be modified when that feature is implemented.

2021-03-29 10:11 UTC, ayonam commented on test/optional_type/optional_type_in_func_arg1.bal
> +    printu32(foo(32));
Agreed.

2021-03-29 12:45 UTC, ayonam commented on runtime/src/lib.rs
> +    if (source.len() < 2) || (destination.len() < 2) {
@KavinduZoysa Can you please make the necessary changes for this one?

2021-03-29 17:10 UTC, KavinduZoysa commented on runtime/src/lib.rs
> +    if (source.len() < 2) || (destination.len() < 2) {
@ayonam, I have done the change under this commit 75513c8, please check

2021-03-29 17:45 UTC, ayonam approved these changes

2021-03-29 17:57 UTC, merged