Array type support for float, boolean and string types
ballerina-platform/nballerina pull request #219
Opened 2021-03-28 10:20 UTC by ramakotareddy

Generic type array support (int, float, boolean and String)
    Added test cases for newly  added Array types.
    Fix all review comments #182 
    
Resolves #136

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-03-28 10:22 UTC, ramakotareddy commented
Fix all review comments from #182  and created separated issue #218 for Rust related comments and shubham will address these rust related comments.

2021-03-28 13:07 UTC, ruvi-d commented
Need to address : https://github.com/ballerina-platform/nballerina/pull/182#discussion_r599536591

2021-03-28 15:25 UTC, KavinduZoysa commented
It seems we need to have more test cases, such as
1. arrays as global var
2. array in function return
3. array in function arg

Please consider different cases as much as possible.

2021-03-28 15:25 UTC, ruvi-d requested changes

2021-03-28 15:25 UTC, ruvi-d commented on compiler/codegen/Types.cpp
> +    : type(type), name(std::move(namep)), flags(flagsp), memberType(memberType), size(size), state(state) {}
I think I mentioned this previously. We shouldn't be extending classes like this so support different variations. Shall we define structures to each new type and store them as std::variant as mentioned previously?
Here is an example: https://github.com/ballerina-platform/nballerina/blob/265df02e96b91953ca371f5b7a896d37ee4cfba6/compiler/include/MapInsns.h#L58
This is a bit more background about the approach: https://youtu.be/ojZbFIQSdl8?t=929

2021-03-28 15:25 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn array_init_int(size: i32) -> *mut Vec<*mut i32> {
Since all array_init_ functions have effectively the same method signature, can we combine them into one like:
`array_int(size: i32, type: *const c_char)`
Then we can have just one function call for all the types (will work for both primitive and reference types). We can match the passed `type` c-string and create the correct type of vector from the Rust side.
WDYT?

2021-03-28 15:25 UTC, ruvi-d commented on runtime/src/lib.rs
> +    let n_size = n as usize;
Should be named index, not n_size
Repeat for other functions too.

2021-03-28 15:25 UTC, ruvi-d commented on runtime/src/lib.rs
> +    let return_val = arr[n_size];
Don't we need to check whether array access is out of bounds?

2021-03-28 15:25 UTC, ruvi-d commented on test/array/booleanArrayLoadAndStore.bal
> +    boolean b = <boolean>b1;
Let's only do load/store in this test. Write separate tests for any casting, function params, global variables for key and value, etc..  

For this load and store test, store more than one value

2021-03-28 15:25 UTC, ruvi-d commented on test/array/stringArrayLoadAndStore.bal
> +    print_str(b);
Let's only do load/store in this test. Write separate tests for any casting, function params, global variables for key and value, etc..  

For this load and store test, store more than one value. like
```
arr4[0] = "Hello";
arr4[2] = " World";
string b = arr4[0];
string c = arr4[2];
print_str("RESULT=");
print_str(b);
print_str(c);
```

2021-03-28 15:27 UTC, ruvi-d commented
> It seems we need to have more test cases, such as
> 
> 1. arrays as global var
> 2. array in function return
> 3. array in function arg
> 
> Please consider different cases as much as possible.

+1 
You can more easily identify the missing test cases if you follow the naming convention from #213 and refer the tests from the other types.

2021-03-28 15:28 UTC, ruvi-d commented on compiler/codegen/ArrayInsns.cpp
> +    const string arrayTypeFuncName = "array_init_" + typeStr;
We generally won't to avoid named variables that are only used once.

2021-03-28 23:46 UTC, ramakotareddy commented on compiler/codegen/ArrayInsns.cpp
> +    assert(funcObj.getLocalOrGlobalVariable(getLhsOperand())->getType().getTypeTag());
Fixed

2021-03-28 23:46 UTC, ramakotareddy commented on compiler/codegen/ArrayInsns.cpp
> +    const string arrayTypeFuncName = "array_init_" + typeStr;
Fixed

2021-03-28 23:47 UTC, ramakotareddy commented on compiler/codegen/ArrayInsns.cpp
> +    LLVMValueRef addedFuncRef = getPackageMutableRef().getFunctionRef(arrayTypeFuncName);
Fixed

2021-03-28 23:47 UTC, ramakotareddy commented on compiler/codegen/ArrayInsns.cpp
> +    TypeTag lhsOpTypeTag = (TypeTag)(funcObj.getLocalOrGlobalVariable(getLhsOperand())->getType().getTypeTag());
Fixed

2021-03-28 23:47 UTC, ramakotareddy commented on runtime/src/lib.rs
> +    let n_size = n as usize;
Fixed

2021-03-29 00:57 UTC, ramakotareddy commented
Add support for array of arrays (multi dimensional arrays) int type.

2021-03-29 03:41 UTC, ramakotareddy commented
Add Support of Array of Arrays with Two dimensional array.
Added test cases with two dimensional load and store. will add more test cases with n dimensional and with array type cast.

2021-03-29 03:51 UTC, ruvi-d commented
> Add Support of Array of Arrays with Two dimensional array.
> Added test cases with two dimensional load and store. will add more test cases with n dimensional and with array type cast.

This PR title is "Array type support for float, boolean and string and array of arrays".. 
Are you sure you want to merge "Array of Arrays and Union types" with this PR? 
I would have thought that separate PRs would make sense, because we haven't resolved all the issues from the first review. If you keep adding commits with new functionality, we can't verify that you are fixing the review comments without having to do a complete PR review again.

2021-03-29 14:02 UTC, ramakotareddy commented
Added test cases.

2021-03-29 14:03 UTC, ramakotareddy commented on test/array/stringArrayLoadAndStore.bal
> +    print_str(b);
Fixed

2021-03-29 14:03 UTC, ramakotareddy commented on test/array/booleanArrayLoadAndStore.bal
> +    boolean b = <boolean>b1;
Fixed

2021-03-29 15:32 UTC, ruvi-d requested changes

2021-03-29 15:32 UTC, ruvi-d commented on test/array/string_array_with_any_typecast.bal
> +    arr4[0] = "Hello";
Since this is an array, let's initialize at least two values like:
```
arr4[1] = " World";
```
And print both values. Otherwise this test would pass even if string[] = string.

2021-03-29 15:32 UTC, ruvi-d commented on test/array/function_call_string_array.bal
> +public function printu32(int val) = external;
printu32 not used

2021-03-29 15:32 UTC, ruvi-d commented on test/array/function_call_boolean_array.bal
> +    if (!test(arr1)) {
don't use `!` because of #212

2021-03-29 15:32 UTC, ruvi-d commented on test/array/boolean_array_with_any_typecast.bal
> +    arr4[0] = true;
Since this is an array, let's initialize at least two values mentioned previously. But be aware of #199

2021-03-29 15:32 UTC, ruvi-d commented on test/array/boolean_array_global_boolean.bal
> +    arr4[0] = true;
As mentioned, let's initialize at least two values

2021-03-29 15:41 UTC, ramakotareddy commented on test/array/function_call_boolean_array.bal
> +    if (!test(arr1)) {
Ruvi,  We don't have print_boolean also. How can we check the boolean values? Please suggest

2021-03-29 15:42 UTC, ruvi-d requested changes

2021-03-29 15:42 UTC, ruvi-d commented on compiler/codegen/Types.cpp
> +    : type(type), name(std::move(namep)), typeInfo(arrayType) {}
Doesn't the static analyzer recommend to move the typeInfo?

2021-03-29 15:42 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn array_init_int(size: i32) -> *mut Vec<*mut i32> {
Create an issue for this if you are not gonna handle it in this PR

2021-03-29 15:42 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn array_store_float(arr_ptr: *mut Vec<*mut f32>, index: i32, ref_ptr: *mut f32) {
@ramakotareddy : Why are we are still passing values by reference for float, bool and int?

2021-03-29 15:46 UTC, ramakotareddy commented on runtime/src/lib.rs
> +pub extern "C" fn array_store_float(arr_ptr: *mut Vec<*mut f32>, index: i32, ref_ptr: *mut f32) {
In the new issue #218, will fix this. We need to change few things in Codegen side also.

2021-03-29 15:47 UTC, ruvi-d commented on runtime/src/lib.rs
> +    let return_val = arr[n_size];
This has not been addressed

2021-03-29 15:49 UTC, ruvi-d commented
Other open issues: 
https://github.com/ballerina-platform/nballerina/pull/219#discussion_r602891627
https://github.com/ballerina-platform/nballerina/pull/219#discussion_r602890915

Please address all open issues before requesting another review

2021-03-29 15:53 UTC, ramakotareddy commented on runtime/src/lib.rs
> +pub extern "C" fn array_init_int(size: i32) -> *mut Vec<*mut i32> {
Combine the array init functions into one #222

2021-03-29 17:35 UTC, ramakotareddy commented on test/array/boolean_array_global_boolean.bal
> +    arr4[0] = true;
Fixed

2021-03-29 17:35 UTC, ramakotareddy commented on test/array/boolean_array_with_any_typecast.bal
> +    arr4[0] = true;
Fixed

2021-03-29 17:35 UTC, ramakotareddy commented on test/array/function_call_boolean_array.bal
> +    if (!test(arr1)) {
Fixed

2021-03-29 17:35 UTC, ramakotareddy commented on test/array/function_call_string_array.bal
> +public function printu32(int val) = external;
Fixed

2021-03-29 17:35 UTC, ramakotareddy commented on test/array/string_array_with_any_typecast.bal
> +    arr4[0] = "Hello";
Fixed

2021-03-30 00:28 UTC, ramakotareddy commented on runtime/src/lib.rs
> +pub extern "C" fn array_store_float(arr_ptr: *mut Vec<*mut f32>, index: i32, ref_ptr: *mut f32) {
@ruvi-d , If i pass by value, printing int number as some garbage value instead of some number in my case. we need to debug deep and fix this issue. I will address this issue in #218 issue.

2021-03-30 00:48 UTC, ramakotareddy commented on compiler/codegen/Types.cpp
> +    : type(type), name(std::move(namep)), typeInfo(arrayType) {}
@ruvi-d , i got only three warnings related to constructor parameter names from Type and i have fixed those. i didn't get any recommendation/warning from static analyzer regarding move the typeInfo.

2021-03-30 01:14 UTC, ramakotareddy commented on runtime/src/lib.rs
> +    let return_val = arr[n_size];
Fixed

2021-03-30 02:56 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn array_store_float(arr_ptr: *mut Vec<*mut f32>, index: i32, ref_ptr: *mut f32) {
@ramakotareddy : can you clean up the description in #218 and just list in bullet form the pending items? i.e. without only the links. It's important to list them out because all of them don't have the same priority. I believe that we discussed that things like refactoring shapinfo class to use variants is low priority. 
This pass by reference issue I think is high priority and should be fixed before array of arrays.

2021-03-30 03:05 UTC, ramakotareddy commented on runtime/src/lib.rs
> +pub extern "C" fn array_store_float(arr_ptr: *mut Vec<*mut f32>, index: i32, ref_ptr: *mut f32) {
@ruvi-d , from the #218 issue i have updated the description and those two links are pointed to same issue.(pass by value) and we already addressed std::variant issue.

2021-03-30 03:44 UTC, ruvi-d requested changes

2021-03-30 03:44 UTC, ruvi-d commented on runtime/src/lib.rs
> +    assert!(arr.len() > index_n);
We need a test that covers this. Please create a task and link it with #181

2021-03-30 03:47 UTC, ramakotareddy commented on runtime/src/lib.rs
> +    assert!(arr.len() > index_n);
Created Ruvi, Create test case of Array out of bound Access Abort functionality #223

2021-03-30 03:50 UTC, ruvi-d approved these changes

2021-03-30 03:54 UTC, Kishanthan approved these changes

2021-03-30 03:55 UTC, merged