Support array of arrays
ballerina-platform/nballerina pull request #228
Opened 2021-03-31 05:23 UTC by ramakotareddy

## Purpose
Add support of two dimensional array with Int type.

Resolves #137  Array of Arrays 

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-03-31 17:58 UTC, KavinduZoysa commented on test/array/load_store_three_dim_array.bal
> +    arr1[0][1][1] = 1;
How does three dim arrays are working in this PR?

2021-04-01 12:53 UTC, ruvi-d requested changes

2021-04-01 12:53 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +    std::vector<Operand> initValues;
Delete the //TODO in line 452

2021-04-01 12:53 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +    std::vector<Operand> initValues;
Since we know the size of the vector, use `reserve()` to set capacity

2021-04-01 12:53 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +        initValues.push_back(initValue);
skip the temp named variable. `initValues.push_back(readerRef.readOperand());`

2021-04-01 12:53 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +    return std::make_unique<ArrayInsn>(lhsOp, currentBB, sizeOperand, initValues);
Add an early return to handle `init_values_count == 0` case. Better to use an `ArrayInsn` constructor without  initValues vector arg for that.

2021-04-01 12:53 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn array_init_array_int(size: i32) -> *mut Vec<*mut Vec<*mut i32>> {
We need to first fix the issue where we are passing and store array member as references

2021-04-01 12:53 UTC, ruvi-d commented on runtime/src/lib.rs
> +    let foo: Box<Vec<*mut Vec<*mut i32>>> = Box::new(Vec::with_capacity(size_t));
use a meaningful variable name instead of `foo`. Repeat for other functions

2021-04-01 12:53 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn array_init_array_array(size: i32) -> *mut Vec<*mut Vec<*mut i32>> {
Why does both `array_init_array_int` and `array_init_array_array` both return `*mut Vec<*mut Vec<*mut i32>>` ?

2021-04-01 12:53 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn array_init_array_string(size: i32) -> *mut Vec<*mut Vec<*mut String>> {
String needs to use BString

2021-04-01 12:53 UTC, ruvi-d commented on runtime/src/lib.rs
> +    let len = index_n + 1;
assert that index is not negative

2021-04-01 12:53 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn array_load_array_array(arr_ptr: *mut Vec<*mut Vec<*mut i32>>, index: i32) -> *mut Vec<*mut i32> {
Same questions as with the corresponding init function, why is this same as `array_load_array_int` ?

2021-04-01 12:53 UTC, ruvi-d commented on runtime/src/lib.rs
> +
Missing deinit functions

2021-04-01 12:53 UTC, ruvi-d commented on test/array/twod_int_array_with_any_typecast.bal
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" | filecheck %s
please check test file name. format should be `<action>_<type>_<other>.bal`

2021-04-01 12:53 UTC, ruvi-d commented on test/array/twod_int_array_with_any_typecast.bal
> +    any i1 = arr4[0][0];
for casting to any, we should be casting the entire multi dimensional array. as in `any val = arr4;`

2021-04-01 12:53 UTC, ruvi-d commented on runtime/src/lib.rs
> +
Missing tests for array init values that are not arrays. e.g. int, float, bool and string types.

2021-04-01 12:53 UTC, ruvi-d commented on test/array/string_twodim_array_with_global_var.bal
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" | filecheck %s
please check test file name. format should be `<action>_<type>_<other>.bal`

2021-04-01 12:53 UTC, ruvi-d commented on test/array/string_twodim_array_with_any_typecast.bal
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" | filecheck %s
please check test file name. format should be `<action>_<type>_<other>.bal`

2021-04-01 12:53 UTC, ruvi-d commented on test/array/load_store_two_dim_array_boolean.bal
> +    if (b) {
need to check at least 2 member values from array

2021-04-01 12:53 UTC, ruvi-d commented on runtime/src/lib.rs
> +
Missing test to cover function's with multi dimensional array return types

2021-04-01 15:34 UTC, KavinduZoysa commented on runtime/src/lib.rs
> +
Shall we add a test case something like this, 
```
function foo() returns string[][] {
    string[][] s = [[], []];
    s[0][0] = "Test";
    return s;
}

public function main() {
    string[][] s = foo();
    string x = s[0][0];
}
```

2021-04-07 04:35 UTC, ramakotareddy commented on runtime/src/lib.rs
> +
@ruvi-d, Please give any simple testcase.

2021-04-07 04:46 UTC, ruvi-d commented on runtime/src/lib.rs
> +
`int arr1[] = [1,2,3,4];` for float, bool and string

2021-04-08 04:11 UTC, ramakotareddy commented on runtime/src/lib.rs
> +pub extern "C" fn array_init_array_int(size: i32) -> *mut Vec<*mut Vec<*mut i32>> {
Fixed in #242 PR.

2021-04-08 04:12 UTC, ramakotareddy commented on runtime/src/lib.rs
> +pub extern "C" fn array_init_array_string(size: i32) -> *mut Vec<*mut Vec<*mut String>> {
Fixed in #242 PR.

2021-04-29 06:15 UTC, closed without merging