Stop creating extra BBs in foreach
ballerina-platform/nballerina pull request #228
Opened 2021-07-14 10:19 UTC by manuranga

Fixes #222

Issue became apparent after #208 which got reverted. A workaround has been introduced in #219. The workaround is reverted in this pr.

2021-07-14 11:24 UTC, heshanpadmasiri approved these changes

2021-07-15 05:48 UTC, jclark requested changes

2021-07-15 05:48 UTC, jclark commented on compiler/modules/front/codeGen.bal
> +        loopStep = cx.loopContinueBlock() ?: cx.createBasicBlock();
Why is this `cx.loopContinueBlock()` rather than `loopStep`? You assigned `loopStep` just above.

2021-07-15 05:48 UTC, jclark commented on compiler/modules/front/codeGen.bal
> +        // is this cast a JBUG?
Type of loopStep is not narrowed, so no...

2021-07-15 10:54 UTC, merged