Model Bal Int as 64 bits in codegen phase
ballerina-platform/nballerina pull request #235
Opened 2021-04-04 09:12 UTC by shubhamnarlawar

Resolves #156

2021-04-04 09:22 UTC, shubhamnarlawar commented
I have changed from `LLVMInt32Type()` to `LLVMInt64Type()` in `Package.cpp` and `ConstLoadInsn.cpp`.

@ruvi-d - Please suggest on how to handle maps in this case.

2021-04-04 10:12 UTC, ruvi-d commented
> @ruvi-d - Please suggest on how to handle maps in this case.

Same as for array of int types. The corresponding runtime functions need to be updated.

2021-04-05 11:00 UTC, shubhamnarlawar commented
@ruvi-d - Please review and suggest changes.

2021-04-05 11:05 UTC, ruvi-d commented
Please:
* Add a test for int value that is larger than 32 bits
* Remove 32 bit print int functions from runtime lib (update the tests accordingly)

2021-04-05 13:28 UTC, shubhamnarlawar commented
> Please:
> 
>     * Add a test for int value that is larger than 32 bits
> 
>     * Remove 32 bit print int functions from runtime lib (update the tests accordingly)



> Please:
> 
>     * Add a test for int value that is larger than 32 bits
> 
>     * Remove 32 bit print int functions from runtime lib (update the tests accordingly)

1. I have added a test which has a int value `> 32 bits` - `greater_than_32_bits.bal`
2. I have replaced all `printu32()` with `printu64()` in all bal tests.
3. I am using `uint64_t` instead of `int` as `int` just hold 4 bytes. Is this fine?

2021-04-05 15:15 UTC, ruvi-d commented
> 1. I have added a test which has a int value `> 32 bits` - `greater_than_32_bits.bal`

In the same test, print both positive and negative values that are larger than 32bit

> 2. I have replaced all `printu32()` with `printu64()` in all bal tests.

We should be using only signed 64 values. i.e `print_i64` not `print_u64`. Ballerina int's are signed and 64bit

> 3. I am using `uint64_t` instead of `int` as `int` just hold 4 bytes. Is this fine?

Again, you can't use unsigned. I assume that `long long` or `int64_t` will work

2021-04-06 08:37 UTC, ruvi-d requested changes
* Need to change all u64 references to i64
* Need to add test cases to cover negative value ints
* Delete Rust print functions that we are not using

2021-04-06 08:37 UTC, ruvi-d commented on test/any/cast_any_basic_types.bal
> +public function printu64(int val) = external;
Function not in use. Can be deleted.

2021-04-06 08:37 UTC, ruvi-d commented on test/int/greater_than_32_bits.bal
> +    int val = 8589934591;
Need to test a negative value too

2021-04-06 09:57 UTC, shubhamnarlawar commented on test/int/greater_than_32_bits.bal
> +    int val = 8589934591;
Done. I have added negative value also in `greater_than_32_bits.bal`

2021-04-06 09:58 UTC, shubhamnarlawar commented
> > 1. I have added a test which has a int value `> 32 bits` - `greater_than_32_bits.bal`
> 
> In the same test, print both positive and negative values that are larger than 32bit

Done.

> 
> > 1. I have replaced all `printu32()` with `printu64()` in all bal tests.
> 
> We should be using only signed 64 values. i.e `print_i64` not `print_u64`. Ballerina int's are signed and 64bit

Got it. We have `print64`. Let me rename it to `print_i64` and update all the testcases.

> 
> > 1. I am using `uint64_t` instead of `int` as `int` just hold 4 bytes. Is this fine?
> 
> Again, you can't use unsigned. I assume that `long long` or `int64_t` will work

`int64_t` seems fine to me.

2021-04-06 10:43 UTC, shubhamnarlawar commented on test/any/cast_any_basic_types.bal
> +public function printu64(int val) = external;
Deleted all unsigned print int functions from rust.

2021-04-06 10:48 UTC, shubhamnarlawar commented
>     * Need to change all u64 references to i64

Done.

> 
>     * Need to add test cases to cover negative value ints

Done in `greater_than_32_bits.bal` and `init_int.bal`.

> 
>     * Delete Rust print functions that we are not using

Removed unsued rust functions.

2021-04-06 11:28 UTC, shubhamnarlawar commented
Is it good to merge now?

2021-04-06 13:16 UTC, ruvi-d requested changes

2021-04-06 13:16 UTC, ruvi-d commented on compiler/BIRReader.h
> +    uint64_t getIntCp(uint32_t index);
Still using unsigned int

2021-04-06 13:16 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn print_i32(num32: i32) {
There is no need to use this function anymore

2021-04-06 13:16 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn print_i16(num16: i16) {
We don't need this either right?

2021-04-06 13:16 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn print_i8(num8: i8) {
Do we need print_i8?

2021-04-06 13:16 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn print_i64(num64: i64) {
`print_integer` would have been a more appropriate name here

2021-04-06 14:54 UTC, shubhamnarlawar commented on compiler/BIRReader.h
> +    uint64_t getIntCp(uint32_t index);
During initial stage, @ayonam suggested to read all the values from the BIR dump as unsigned values and not signed values.

2021-04-06 14:55 UTC, shubhamnarlawar commented on compiler/BIRReader.h
> +    uint64_t getIntCp(uint32_t index);
All byte stream functions return unsigned values. As per your suggestion to store it as `int64_t`, I am doing casting from `uint64_t` to `int64_t`.

2021-04-06 15:10 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn print_i16(num16: i16) {
No. All functions can use `print_i64`.
Removed.

2021-04-06 15:10 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn print_i8(num8: i8) {
Removed.

2021-04-06 15:12 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn print_i64(num64: i64) {
As `print_i32`, `print_i16` and `print_i8` are removed. `print_integer` seems a good name. Thanks for the suggestion.

2021-04-06 15:12 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn print_i32(num32: i32) {
Removed.

2021-04-06 15:25 UTC, ruvi-d commented on compiler/BIRReader.h
> +    uint64_t getIntCp(uint32_t index);
BIR spec says that it's 8 bytes and signed : https://github.com/ballerina-platform/ballerina-lang/blob/nballerina/docs/bir-spec/src/main/resources/kaitai/bir.ksy#L49

2021-04-06 15:31 UTC, ruvi-d requested changes
One issue to resolve: https://github.com/ballerina-platform/nballerina/pull/235#discussion_r607951884

2021-04-06 17:37 UTC, shubhamnarlawar commented
> One issue to resolve: [#235 (comment)](https://github.com/ballerina-platform/nballerina/pull/235#discussion_r607951884)

Done.

2021-04-06 17:37 UTC, shubhamnarlawar commented on compiler/BIRReader.h
> +    uint64_t getIntCp(uint32_t index);
Done. I have updated all the places. Thanks for the suggestion.

2021-04-07 02:43 UTC, ruvi-d approved these changes

2021-04-07 07:21 UTC, shubhamnarlawar commented
Please approve this PR - @Kishanthan @uthaiyashankar @manuranga @KavinduZoysa

2021-04-07 18:33 UTC, shubhamnarlawar commented
Merging PR #196 causes merge conflict in this PR because both PR were related to changes in all the testcases.

2021-04-08 14:48 UTC, KavinduZoysa approved these changes

2021-04-08 14:49 UTC, merged