Support for anydata
ballerina-platform/nballerina pull request #236
Opened 2021-04-05 04:27 UTC by KavinduZoysa

## Purpose
$subject

Fixes #210

2021-04-06 08:22 UTC, ruvi-d requested changes

2021-04-06 08:22 UTC, ruvi-d commented on compiler/include/TypeCastInsn.h
> +    bool isStructAvailable(TypeTag typeTag);
should be static

2021-04-06 08:22 UTC, ruvi-d commented on compiler/codegen/TypeCastInsn.cpp
> +bool TypeCastInsn::isStructAvailable(TypeTag typeTag) {
how about we call this function `isSmartStructType` ?

2021-04-06 08:22 UTC, ruvi-d commented on runtime/src/bal_map.rs
> +        map: HashMap<String, *const i8>,
we can use `*mut c_void` type for opaque pointers instead of `*const i8`. e.g. https://github.com/ruvi-d/nballerina/blob/ruvi/task/map-load/runtime/src/lib.rs#L42

2021-04-06 08:24 UTC, ruvi-d commented
@KavinduZoysa : better rename the test files to the `<action>-<type>-<other>.bal` format that the other tests are using in master.

Also, I'd suggest that we get #238 merged before this PR

2021-04-07 06:49 UTC, KavinduZoysa commented on compiler/include/TypeCastInsn.h
> +    bool isStructAvailable(TypeTag typeTag);
Done

2021-04-07 08:46 UTC, KavinduZoysa commented on compiler/codegen/TypeCastInsn.cpp
> +bool TypeCastInsn::isStructAvailable(TypeTag typeTag) {
Done

2021-04-07 08:46 UTC, KavinduZoysa commented on runtime/src/bal_map.rs
> +        map: HashMap<String, *const i8>,
Done

2021-04-07 08:46 UTC, KavinduZoysa commented
> @KavinduZoysa : better rename the test files to the `<action>-<type>-<other>.bal` format that the other tests are using in master.

done

2021-04-08 03:51 UTC, ruvi-d requested changes

2021-04-08 03:51 UTC, ruvi-d commented on compiler/codegen/MapInsns.cpp
> +
The member type is hard coded here (load function call) as Int32Type. Should be updated to support any type load?

2021-04-08 03:51 UTC, ruvi-d commented on runtime/src/lib.rs
> +    let vec: Box<Vec<*mut i8>> = Box::new(Vec::with_capacity(size_t));
The vector member type should also be `c_void` right?

2021-04-08 03:51 UTC, ruvi-d commented on runtime/src/lib.rs
> +        arr.resize(len, 0 as *mut i8);
array needs to be resized with `nill` values. As this test prints true.
```Java
import ballerina/io;

public function main() {
    anydata[] arr = [];
    arr[100] = 100;
    anydata val = arr[50];
    io:println(val is ());
}
```
Shall we create an issue to track this?

2021-04-08 03:51 UTC, ruvi-d commented on runtime/src/lib.rs
> +    println!("length={}", bal_map.length());
We should be able to support load for maps now without having to resort to this length print.

2021-04-09 07:21 UTC, KavinduZoysa commented on runtime/src/lib.rs
> +    let vec: Box<Vec<*mut i8>> = Box::new(Vec::with_capacity(size_t));
Done

2021-04-09 07:21 UTC, KavinduZoysa commented on compiler/codegen/MapInsns.cpp
> +
Done

2021-04-09 07:21 UTC, KavinduZoysa commented on runtime/src/lib.rs
> +    println!("length={}", bal_map.length());
Done

2021-04-09 12:44 UTC, ruvi-d requested changes

2021-04-09 12:44 UTC, ruvi-d commented on runtime/src/lib.rs
> +    println!("length={}", map_src.length());
Print is not required

2021-04-09 12:44 UTC, ruvi-d commented on runtime/src/lib.rs
> +    println!("length={}", map_src.length());
Print is not required

2021-04-09 12:45 UTC, ruvi-d commented on runtime/src/lib.rs
> +        arr.resize(len, 0 as *mut i8);
@KavinduZoysa : this is not resolved right?

2021-04-09 12:48 UTC, ruvi-d commented
@KavinduZoysa : regarding your "create*" and "define*" test cases.. Can you check the names used for the other type? I think you should be able to find a different wording that we have used for similar tests.

2021-04-11 03:38 UTC, KavinduZoysa commented on runtime/src/lib.rs
> +        arr.resize(len, 0 as *mut i8);
Created an issue https://github.com/ballerina-platform/nballerina/issues/247

2021-04-11 03:39 UTC, KavinduZoysa commented on runtime/src/lib.rs
> +    println!("length={}", map_src.length());
I have created another issue to support the spread field with a map of anydata. https://github.com/ballerina-platform/nballerina/issues/246

2021-04-11 03:39 UTC, KavinduZoysa commented on runtime/src/lib.rs
> +    println!("length={}", map_src.length());
Removed the method, should add under https://github.com/ballerina-platform/nballerina/issues/246

2021-04-11 03:39 UTC, KavinduZoysa commented
> @KavinduZoysa : regarding your "create*" and "define*" test cases.. Can you check the names used for the other type? I think you should be able to find a different wording that we have used for similar tests.

Changed

2021-04-16 04:17 UTC, ruvi-d approved these changes

2021-04-16 12:12 UTC, Kishanthan approved these changes

2021-04-16 12:12 UTC, merged