Pass call by value of array rust functions
ballerina-platform/nballerina pull request #242
Opened 2021-04-07 01:06 UTC by ramakotareddy

## Purpose
pass the the primitive values to store by value instead of by reference

Fixes: #218 

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-04-07 02:46 UTC, ruvi-d commented
Add that this resolves #226

2021-04-07 03:03 UTC, ruvi-d requested changes

2021-04-07 04:30 UTC, ramakotareddy commented on compiler/codegen/ArrayInsns.cpp
> +                                                         getFunctionRef().getLLVMLocalVar(rhsOp.getName()), ""))};
@ruvi-d , without LLVMBuildLoad, getting type as i32*, but now we are passing by value, so now i32 is the expected type. If we load Rhs value will get "i32".

2021-04-07 04:43 UTC, ruvi-d commented on compiler/codegen/ArrayInsns.cpp
> +                                                         getFunctionRef().getLLVMLocalVar(rhsOp.getName()), ""))};
can you share the BIR with the RHS type info?

2021-04-07 04:44 UTC, ramakotareddy commented on runtime/src/lib.rs
> +        arr.resize(len, 0 as f32);
Yes we can omit "as f32" if we use 0.0 instead on 0. 
i tried and it' working. Thanks Ruvi

2021-04-07 04:45 UTC, ramakotareddy commented on runtime/src/lib.rs
> +        arr.resize(len, 0 as i32);
"as i32" is not required, we can omit "as i32".

2021-04-07 04:55 UTC, ramakotareddy commented on compiler/codegen/ArrayInsns.cpp
> +                                                         getFunctionRef().getLLVMLocalVar(rhsOp.getName()), ""))};
@ruvi-d , you need total BIR output of simple testcase? or LLVM IR?

2021-04-07 05:02 UTC, ruvi-d commented on compiler/codegen/ArrayInsns.cpp
> +                                                         getFunctionRef().getLLVMLocalVar(rhsOp.getName()), ""))};
Adding an extra load operation just to get the a llvm value's didn't make sense to me. If you can share the BIR and LLVM IR for for the most basic store example, maybe I can help with a solution.

2021-04-07 05:08 UTC, ramakotareddy commented on compiler/codegen/ArrayInsns.cpp
> +                                                         getFunctionRef().getLLVMLocalVar(rhsOp.getName()), ""))};
test case:
-------------------
public function main() {
    int[] arr1 = [5];
    arr1[0] = 1;
    int a = arr1[0];
}

BIR:
---------------
public main function() -> () {
    %0(RETURN) ();
    %0(RETURN) ();
    %1(LOCAL) int[];
    %3(TEMP) int;
    %4(TEMP) int;
    %5(TEMP) int;
    %7(TEMP) int;
    %8(LOCAL) int;
    %10(TEMP) int;

    bb0 {
        %3 = ConstLoad -1;
        %4 = ConstLoad 5;
        %1 = newArray int[][%3];
        %5 = ConstLoad 1;
        %7 = ConstLoad 0;
        %1[%7] = %5;
        %10 = ConstLoad 0;
        %8 = %1[%10];
        %0 = ConstLoad 0;
        GOTO bb2;
    }
    bb1 {
        GOTO bb2;
    }
    bb2 {
        return;
    }
}

2021-04-07 05:09 UTC, ramakotareddy commented on compiler/codegen/ArrayInsns.cpp
> +                                                         getFunctionRef().getLLVMLocalVar(rhsOp.getName()), ""))};
LLVM IR:
------------------
entry:
  %"%0" = alloca i8*, align 8
  %"%1" = alloca i8*, align 8
  %"%10" = alloca i32, align 4
  %"%3" = alloca i32, align 4
  %"%4" = alloca i32, align 4
  %"%5" = alloca i32, align 4
  %"%7" = alloca i32, align 4
  %"%8" = alloca i32, align 4
  br label %bb0

bb0:                                              ; preds = %entry
  store i32 -1, i32* %"%3", align 4
  store i32 5, i32* %"%4", align 4
  %"%3_temp" = load i32, i32* %"%3", align 4
  %0 = call i8* @array_init_int(i32 %"%3_temp")
  store i8* %0, i8** %"%1", align 8
  store i32 1, i32* %"%5", align 4
  store i32 0, i32* %"%7", align 4
  %1 = load i32, i32* %"%5", align 4
  %2 = load i8*, i8** %"%1", align 8
  %"%7_temp" = load i32, i32* %"%7", align 4
  %"%5_temp" = load i32, i32* %"%5", align 4
  call void @array_store_int(i8* %2, i32 %"%7_temp", i32 %"%5_temp")
  store i32 0, i32* %"%10", align 4
  %3 = load i8*, i8** %"%1", align 8
  %"%10_temp" = load i32, i32* %"%10", align 4
  %4 = call i32 @array_load_int(i8* %3, i32 %"%10_temp")
  store i32 %4, i32* %"%8", align 4
  br label %bb2

2021-04-07 05:10 UTC, ramakotareddy commented on compiler/codegen/ArrayInsns.cpp
> +                                                         getFunctionRef().getLLVMLocalVar(rhsOp.getName()), ""))};
Ruvi, Please check the above details.

2021-04-07 05:32 UTC, ramakotareddy commented on runtime/src/lib.rs
> +        arr.resize(len, 0 as i32);
Fixed

2021-04-07 05:32 UTC, ramakotareddy commented on runtime/src/lib.rs
> +        arr.resize(len, 0 as f32);
Fixed

2021-04-07 05:33 UTC, ramakotareddy commented on runtime/src/lib.rs
> +        arr.resize(len, 0 != 0);
Fixed

2021-04-07 05:33 UTC, ramakotareddy commented on compiler/codegen/ArrayInsns.cpp
> +                                    LLVMBuildLoad(builder, funcObj.getLLVMLocalOrGlobalVar(rhsOp), "")};
Fixed

2021-04-07 06:00 UTC, ruvi-d commented on compiler/codegen/ArrayInsns.cpp
> +                                                         getFunctionRef().getLLVMLocalVar(rhsOp.getName()), ""))};
I see. 
so instead of 
`LLVMTypeOf(LLVMBuildLoad(getFunctionRef().getLLVMBuilder(), getFunctionRef().getLLVMLocalVar(rhsOp.getName()), "")`

You could have done:
`Package::getLLVMTypeOfType(rhsOpTypeTag)` // you will need to overload `getLLVMTypeOfType` to accept TypeTag

2021-04-07 06:38 UTC, ramakotareddy commented on compiler/codegen/ArrayInsns.cpp
> +                                                         getFunctionRef().getLLVMLocalVar(rhsOp.getName()), ""))};
Fixed

2021-04-07 09:39 UTC, ruvi-d requested changes

2021-04-07 09:39 UTC, ruvi-d commented on runtime/src/lib.rs
> +        arr.resize(len, 0 as *mut BString);
I don't think you can store `0` here. You need to store empty BStrings. Otherwise the following test would fail:
```Java
import ballerina/io;

public function main() {
    string[] arr = [];
    arr[100] = "end";
    io:println(arr[50]);
}
```

2021-04-07 10:23 UTC, ruvi-d commented on runtime/src/lib.rs
> +        arr.resize(len, 0 as *mut BString);
You should add this test case for other types also

2021-04-07 15:16 UTC, ramakotareddy commented on runtime/src/lib.rs
> +        arr.resize(len, 0 as *mut BString);
Fixed and added test cases for other types also

2021-04-08 03:23 UTC, ruvi-d approved these changes

2021-04-08 04:50 UTC, Kishanthan approved these changes

2021-04-08 04:51 UTC, merged