Model Bal Float as Double
ballerina-platform/nballerina pull request #245
Opened 2021-04-09 08:12 UTC by shubhamnarlawar

Resolves #157

2021-04-09 08:12 UTC, shubhamnarlawar commented
@ruvi-d - Please review and suggest changes.

2021-04-09 08:17 UTC, shubhamnarlawar commented
- Added a testcase ` test/float/float_upper_limit.bal` to validate double `value > 32 bits`.

2021-04-09 08:17 UTC, shubhamnarlawar commented
- Added a testcase ` test/float/float_upper_limit.bal` to validate double `value > 32 bits`.

2021-04-09 13:01 UTC, ruvi-d requested changes

2021-04-09 13:01 UTC, ruvi-d commented on test/float/init_float_global.bal
> +    printf64(val);
add a negative value too

2021-04-09 13:26 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +    let arr = unsafe { Box::from_raw(arr_ptr) };
Ideally yes. If the index size is > 32 bits, this will fail. Let me update it to `i64`.

2021-04-09 13:29 UTC, shubhamnarlawar commented on test/float/init_float_global.bal
> +    printf64(val);
Done

2021-04-09 13:29 UTC, shubhamnarlawar commented on test/float/float.bal
> +    printf64(2.2);
Done

2021-04-09 13:29 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +    let arr = unsafe { Box::from_raw(arr_ptr) };
Done

2021-04-09 13:30 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +    let arr = unsafe { Box::from_raw(arr_ptr) };
Changed it to f64.

2021-04-10 04:05 UTC, shubhamnarlawar commented
Is it good to merge now?
Ram will start working on floating point arithmetics and comparison once this PR is merged.

2021-04-16 02:32 UTC, ruvi-d requested changes

2021-04-16 02:32 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn box_bal_double(val: f64) -> *mut f64 {
This change will break https://github.com/ballerina-platform/nballerina/blob/master/compiler/codegen/Function.cpp#L219

Leave the name of the type as float (Ballerina basic type name) and please add a test for box_float so that we can catch this in the future

2021-04-16 06:16 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn box_bal_double(val: f64) -> *mut f64 {
Got it. I will keep it as `float`.
Do you mean to add rust unit test to check `box_bal_float`?

2021-04-16 06:24 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn box_bal_double(val: f64) -> *mut f64 {
@ruvi-d - Actually, this will not break. Because I have changed from `float` to `double` in `Type::getNameOfType()`.

Do you want me to restore it to `float`?

2021-04-16 06:25 UTC, ruvi-d commented on runtime/src/lib.rs
> +pub extern "C" fn box_bal_double(val: f64) -> *mut f64 {
Yes. Our LIT tests that should have failed when you made the change to `box_bal_float`. So, we must have missed a test.

2021-04-16 06:41 UTC, shubhamnarlawar commented on compiler/codegen/Types.cpp
> +        return "double";
@ruvi-d - Check here, I have changed it to `double` and hence the name at rust side should be `box_bal_double`.

2021-04-16 06:42 UTC, shubhamnarlawar commented on runtime/src/lib.rs
> +pub extern "C" fn box_bal_double(val: f64) -> *mut f64 {
Please check files changed diff in this PR.

2021-04-16 06:54 UTC, ruvi-d commented on compiler/codegen/Types.cpp
> +        return "double";
oh I see.
I think we should have kept it as float. That is the Ballerina's type name.

2021-04-16 07:09 UTC, shubhamnarlawar commented on compiler/codegen/Types.cpp
> +        return "double";
Done. Reverted type name to float.

2021-04-16 07:14 UTC, ruvi-d approved these changes

2021-04-16 07:35 UTC, shubhamnarlawar commented
Please merge this PR - @KavinduZoysa @Kishanthan

2021-04-19 18:09 UTC, Kishanthan approved these changes

2021-04-19 18:09 UTC, merged