Add support for float arithmetic operations
ballerina-platform/nballerina pull request #250
Opened 2021-04-14 15:58 UTC by ramakotareddy

Add support for Float arithmetic (addition, subtraction, multiplication, division, etc) and Float comparison ( greater or equal, etc).

Resolves #241 

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-04-16 03:02 UTC, ruvi-d requested changes

2021-04-16 03:02 UTC, ruvi-d commented on test/float/multiplication_float.bal
> +    printf32(a * b);
add negative values too

2021-04-16 03:02 UTC, ruvi-d commented on test/float/less_than_float.bal
> +    if (a < b) {
compare negative values too

2021-04-16 03:02 UTC, ruvi-d commented on test/float/greater_equal_than_float.bal
> +    if (a >= b) {
compare negative values too

2021-04-16 03:04 UTC, ruvi-d commented
Missing test cases for sign inversion

2021-04-20 01:03 UTC, ramakotareddy commented on compiler/codegen/BinaryOpInsn.cpp
> +    LLVMValueRef ifReturn = nullptr;
@ruvi-d , you suggested like, add 

if (INT_TYPE) {
  // switch case with all the operations (int)
}

else if (FLOAT_TYPE) {
  // switch case with all the operations (float)
}

else {
  // llvm_unreachable;
}

Please correct me if i am wrong.

2021-04-20 02:58 UTC, ruvi-d commented on compiler/codegen/BinaryOpInsn.cpp
> +    LLVMValueRef ifReturn = nullptr;
Yes. WDYT?

2021-04-20 02:58 UTC, ruvi-d commented on compiler/codegen/BinaryOpInsn.cpp
> +    LLVMValueRef ifReturn = nullptr;
Yes. WDYT?

2021-04-20 05:25 UTC, ramakotareddy commented on compiler/codegen/BinaryOpInsn.cpp
> +    LLVMValueRef ifReturn = nullptr;
Ok. instead of this,  is it OK if we change the "ifReturn" variable name to some meaningful name in the current implementation?
If we create two switch cases, in two switch cases code will be same except variable names right ? correct me if i am wrong. i am ok to create two separate switch cases for int and float.  Please suggest.

2021-04-20 05:36 UTC, ruvi-d commented on compiler/codegen/BinaryOpInsn.cpp
> +    LLVMValueRef ifReturn = nullptr;
Oh I see.
I am ok with a meaningful variable name and - without the two switch cases

2021-04-22 00:23 UTC, ramakotareddy commented
Created new issue for "Missing test cases for sign inversion" and other missing float test cases.

2021-04-22 00:24 UTC, ramakotareddy commented on compiler/codegen/BinaryOpInsn.cpp
> +        }
Fixed in #271

2021-04-22 00:24 UTC, ramakotareddy commented on compiler/codegen/BinaryOpInsn.cpp
> +    LLVMValueRef ifReturn = nullptr;
Fixed in #271

2021-04-22 00:24 UTC, ramakotareddy commented on test/float/add_float.bal
> +    printf32(a + b);
Fixed in #271

2021-04-22 00:24 UTC, ramakotareddy commented on test/float/division_float.bal
> +    printf32(a / b);
Fixed in #271

2021-04-22 00:24 UTC, ramakotareddy commented on test/float/division_float.bal
> +// CHECK: RESULT=1.8198198
Fixed in #271

2021-04-22 00:24 UTC, ramakotareddy commented on test/float/substraction_float.bal
> +    printf32(a - b);
Fixed in #271

2021-04-22 00:25 UTC, ramakotareddy commented on test/operations/operations_binary_all_float.bal
> +    g = h < 3.0;
Fixed in #271

2021-04-22 00:25 UTC, ramakotareddy commented on test/float/multiplication_float.bal
> +    printf32(a * b);
Fixed in #271

2021-04-22 00:25 UTC, ramakotareddy commented on test/float/less_than_float.bal
> +    if (a < b) {
Fixed in #271

2021-04-22 00:25 UTC, ramakotareddy commented on test/float/greater_equal_than_float.bal
> +    if (a >= b) {
Fixed in #271

2021-04-22 00:26 UTC, ramakotareddy commented
Open new PR #271

2021-04-22 00:26 UTC, closed without merging