Move nBallerina to Ballerina Swanlake alpha4 release
ballerina-platform/nballerina pull request #258
Opened 2021-04-20 10:27 UTC by heshanpadmasiri

## Purpose
Move nBallerina to Ballerina Swanlake alpha4 release.
Resolves #122 

## Goals
Update the BIRReader to work with bir files compiled with Ballerina Swanlake alpha4

## Approach
BIRReader has been updated to correctly read the bir files from Ballerian swanlake alpha4 release. However merging this will lead to issue #255 and #257 probably due to the same reason.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Unit test init_map_spread_field changed to reflect language changes and unit tests init_optional_string and define_basic_anydata_vars marked as expected failure due to issue #255
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-04-20 10:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ballerina-platform/nballerina?pullRequest=258) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ballerina-platform/nballerina?pullRequest=258) before we can accept your contribution.<br/><hr/>**Heshan Padmasiri** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ballerina-platform/nballerina?pullRequest=258) it.</sub>

2021-04-20 17:21 UTC, KavinduZoysa commented on test/anydata/define_basic_anydata_vars.bal
> +// XFAIL: *
missing new line in a couple of files.

2021-04-20 17:23 UTC, KavinduZoysa commented on test/map/init_map_spread_field.bal
> -
Can you explain why did you do this change?

2021-04-20 17:26 UTC, KavinduZoysa commented on compiler/BIRReader.cpp
> +    uint64_t flags __attribute__((unused)) = readS8be();
Please use `[[maybe_unused]]` instead of `__attribute__((unused))`, then we can remove the unix check.

2021-04-20 17:27 UTC, KavinduZoysa commented on compiler/BIRReader.cpp
> +        {
Incorrect formatting

2021-04-20 17:31 UTC, KavinduZoysa commented
There are formatting issues please check them. Did you skip this test file `operations_binary_all_int.bal`?

2021-04-21 02:29 UTC, heshanpadmasiri commented on test/map/init_map_spread_field.bal
> -
When you have multiple spread operations there newer ballerina front end throws an error saying `invalid usage of mapping constructor expression: multiple spread fields of inclusive mapping types are not allowed`. So I removed one of the spread operations

2021-04-21 02:58 UTC, heshanpadmasiri commented on compiler/BIRReader.cpp
> +    uint64_t flags __attribute__((unused)) = readS8be();
Fixed

2021-04-21 02:58 UTC, heshanpadmasiri commented on compiler/BIRReader.cpp
> +        {
Fixed

2021-04-21 03:01 UTC, heshanpadmasiri commented
I set the test case operations_binary_all_int.bal to skip due to issue #257 and test cases init_optional_string and define_basic_anydata_vars were set as expected failures due to issue #255. I think both are caused by the same cause because only difference in the newer and older llvm ir files are the same

2021-04-21 03:02 UTC, heshanpadmasiri commented on test/anydata/define_basic_anydata_vars.bal
> +// XFAIL: *
fixed

2021-04-21 04:19 UTC, KavinduZoysa commented on test/map/init_map_spread_field.bal
> -
ACK

2021-04-21 04:21 UTC, KavinduZoysa commented on test/optional-type/init_optional_string.bal
> +// XFAIL: *
Missing new line.

2021-04-21 04:22 UTC, KavinduZoysa commented
> I set the test case operations_binary_all_int.bal to skip due to issue #257 and test cases init_optional_string and define_basic_anydata_vars were set as expected failures due to issue #255. I think both are caused by the same cause because only difference in the newer and older llvm ir files are the same

ACK.

2021-04-21 04:33 UTC, heshanpadmasiri commented on test/optional-type/init_optional_string.bal
> +// XFAIL: *
Fixed

2021-04-21 05:49 UTC, ruvi-d requested changes

2021-04-21 05:49 UTC, ruvi-d commented on .github/workflows/PRCheck.yml
> +          sudo apt install -y build-essential llvm-11-dev lld-11 cmake cargo python3-pip cbindgen
If you are now installing `cbindgen` via apt, do we still need line 17 and 18?

2021-04-21 05:49 UTC, ruvi-d commented on .github/workflows/PRCheck.yml
> +          cd jballerina-tools-2.0.0-alpha8-20210419-135100-df7a4e3f/bin
It would be nice if you can move `alpha8-20210419-135100-df7a4e3f` to something like a shell variable.

2021-04-21 05:49 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +    uint32_t varDclNameCpIndex = readS4be();
What's the reasoning for this change? `readS4be()` is supposed to read and return a signed 4bit value.
I see that you have changed the signed values to unsigned values throughout this .cpp

2021-04-21 05:49 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +    is.read(&doc[0], docLength);
You can `is.ignore(docLength);` if you are not using the doc vector.

2021-04-21 05:49 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +    is.read(&annotations[0], annotationLength);
`is.ignore(annotationLength);` if value is not being used.

2021-04-21 05:49 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +        depended_global_var_cp_entry = readS4be();
i'd change this to: `[[maybe_unused]] uint32_t depended_global_var_cp_entry =  readS4be();` because otherwise `depended_global_var_cp_entry`'s scope is unnecessarily broad.

2021-04-21 05:49 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +            parentScopeIndex = readS4be();
Ditto about the variable scopes.

2021-04-21 05:49 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +    for (uint32_t i = 0; i < requiredParamCount; i++) {
Any reason to remove the auto type deduction? 
I see that you have made this change in multiple places.

2021-04-21 05:49 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +        elementTypeCpIndex = readerRef.readS4be(); // should this not be changed?
What's the concern here?

2021-04-21 05:49 UTC, ruvi-d commented on compiler/BIRReader.h
> +    ~TypeIdSet(){};
It's not best practice to define empty constructors and deconstructions. Just use `=default`
Ref: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c30-define-a-destructor-if-a-class-needs-an-explicit-action-at-object-destruction

Repeat for the other new friend classes

2021-04-21 05:49 UTC, ruvi-d commented on compiler/BIRReader.h
> +    uint32_t detailTypeCpIndex;
I think this is too many members. How about grouping the members it structs that always exist to gather? Like a inner class/struct for all params related to TYPE_TAG_RECORD, TYPE_TAG_TABLE, etc.
And then `ShapeCpInfo` can have a variant of these inner types.
e.g. https://github.com/ballerina-platform/nballerina/blob/master/compiler/include/MapInsns.h#L58

2021-04-21 05:49 UTC, ruvi-d commented on test/anydata/define_basic_anydata_vars.bal
> +// XFAIL
why the XFail here?

2021-04-21 05:49 UTC, ruvi-d commented on test/anydata/define_basic_anydata_vars.bal
> +// XFAIL: *
I don't think the filecheck.py we are using supports XFAIL

2021-04-21 05:49 UTC, ruvi-d commented on test/map/init_map_spread_field.bal
> +    map<int> allMarks = {...boys};
Can't we have multiple spread field initialization anymore?
The Map Initialization codegen will have to be updated if so

2021-04-21 05:49 UTC, ruvi-d commented on test/optional-type/init_optional_string.bal
> +// XFAIL: *
Ditto about XFAIL support

2021-04-21 05:49 UTC, ruvi-d commented on test/testRunScript.sh
> +    bal build --dump-bir-file=$filename-bir-dump $1 1>bal_out.log 2>bal_err.log
`testRunScript.bat` also needs to be updated

2021-04-21 07:04 UTC, heshanpadmasiri commented on .github/workflows/PRCheck.yml
> +          sudo apt install -y build-essential llvm-11-dev lld-11 cmake cargo python3-pip cbindgen
Fixed by removing cbindgen install from apt

2021-04-21 07:04 UTC, heshanpadmasiri commented on .github/workflows/PRCheck.yml
> +          cd jballerina-tools-2.0.0-alpha8-20210419-135100-df7a4e3f/bin
Fixed

2021-04-21 07:05 UTC, heshanpadmasiri commented on compiler/BIRReader.cpp
> +    uint32_t varDclNameCpIndex = readS4be();
Fixed by changing back to signed 4bit values

2021-04-21 07:05 UTC, heshanpadmasiri commented on compiler/BIRReader.cpp
> +    is.read(&doc[0], docLength);
Fixed

2021-04-21 07:06 UTC, heshanpadmasiri commented on compiler/BIRReader.cpp
> +    is.read(&annotations[0], annotationLength);
Fixed

2021-04-21 07:21 UTC, heshanpadmasiri commented on compiler/BIRReader.cpp
> +        elementTypeCpIndex = readerRef.readS4be(); // should this not be changed?
Comment removed

2021-04-21 07:34 UTC, heshanpadmasiri commented on compiler/BIRReader.h
> +    ~TypeIdSet(){};
fixed

2021-04-21 07:35 UTC, heshanpadmasiri commented on test/anydata/define_basic_anydata_vars.bal
> +// XFAIL: *
It works both locally and the pr check so probably it is supported

2021-04-21 07:36 UTC, heshanpadmasiri commented on test/testRunScript.sh
> +    bal build --dump-bir-file=$filename-bir-dump $1 1>bal_out.log 2>bal_err.log
Fixed

2021-04-21 07:37 UTC, heshanpadmasiri commented on compiler/BIRReader.cpp
> +    for (uint32_t i = 0; i < requiredParamCount; i++) {
Fixed by reverting all the loops back to using auto type deduction

2021-04-21 07:37 UTC, heshanpadmasiri commented on compiler/BIRReader.cpp
> +            parentScopeIndex = readS4be();
Fixed

2021-04-21 07:38 UTC, heshanpadmasiri commented on compiler/BIRReader.cpp
> +        depended_global_var_cp_entry = readS4be();
Fixed

2021-04-21 07:43 UTC, ruvi-d commented on test/anydata/define_basic_anydata_vars.bal
> +// XFAIL: *
https://github.com/mull-project/FileCheck.py/blob/master/filecheck/FileCheck.py#L53
^ doesn't seem so.

Regardless, what's the for you to have a XFAIL check here?

2021-04-21 07:56 UTC, heshanpadmasiri commented on compiler/BIRReader.h
> +    uint32_t detailTypeCpIndex;
These new members are new field in the bir file and thus they are not used in the rest of the code (because those parts are not changed). So is it better if I moved them in to the reader function and marked as unused.

2021-04-21 08:01 UTC, heshanpadmasiri commented on test/anydata/define_basic_anydata_vars.bal
> +// XFAIL
due to issue #255

2021-04-21 08:10 UTC, ruvi-d commented on test/anydata/define_basic_anydata_vars.bal
> +// XFAIL: *
My bad. XFAIL support is from LIT and not Filecheck

2021-04-21 08:11 UTC, ruvi-d commented on test/anydata/define_basic_anydata_vars.bal
> +// XFAIL
You have added `XFAIL` to the header and footer of this file. I assume that both are not required.

2021-04-21 08:22 UTC, ruvi-d commented on compiler/BIRReader.h
> +    uint32_t detailTypeCpIndex;
sure +1

2021-04-21 09:06 UTC, heshanpadmasiri commented on compiler/BIRReader.h
> +    uint32_t detailTypeCpIndex;
Fixed

2021-04-21 09:57 UTC, heshanpadmasiri commented on test/anydata/define_basic_anydata_vars.bal
> +// XFAIL
Fixed

2021-04-22 04:47 UTC, Kishanthan requested changes
The commit message is having wrong format. @heshanpadmasiri , please check the guideline - https://github.com/ballerina-platform/nballerina/blob/master/CONTRIBUTING.md on how to write commit messages, PR descriptions, etc

2021-04-22 07:27 UTC, heshanpadmasiri commented
Fixed by changing the new commit

2021-04-22 07:33 UTC, Kishanthan commented
> Fixed by changing the new commit

Check all the commits in this PR and fix them properly.

2021-04-22 09:25 UTC, heshanpadmasiri commented
Fixed by changing the commit history

2021-04-22 16:30 UTC, heshanpadmasiri commented on test/map/init_map_spread_field.bal
> +    map<int> allMarks = {...boys};
Front end throws an error saying `invalid usage of mapping constructor expression: multiple spread fields of inclusive mapping types are not allowed` when you have more than one. So I think yes but given this fails the front end without creating a BIR file it won't affect the codegen.

2021-04-22 17:17 UTC, shubhamnarlawar commented
`BIRReader` changes looks fine to me in this PR!

2021-04-23 03:58 UTC, ruvi-d requested changes

2021-04-23 03:58 UTC, ruvi-d commented on test/anydata/define_basic_anydata_vars.bal
> +// XFAIL: *
IMO we should add a `.skip` extension to skipped test instead of modifying the expected result to FAIL.
We will in the future have actual test that are supposed to fail. Therefore it it will be had to distinguish the test that are supposed to fail vs the ones we want to skip.

2021-04-23 03:59 UTC, ruvi-d commented
The commit history includes commit messages from master. Please clean the history.

2021-04-23 04:31 UTC, Kishanthan commented
> Fixed by changing the commit history

I can still see words like "Updated", "Changed" in some commit messages

2021-04-23 05:01 UTC, heshanpadmasiri commented
> The commit history includes commit messages from master. Please clean the history.

Fixed by squashing those commits in to a single commit

2021-04-23 05:02 UTC, heshanpadmasiri commented
> > Fixed by changing the commit history
> 
> I can still see words like "Updated", "Changed" in some commit messages

Fixed

2021-04-23 05:02 UTC, heshanpadmasiri commented on test/anydata/define_basic_anydata_vars.bal
> +// XFAIL: *
Fixed by changing these test in to skip instead of expected failures

2021-04-23 05:35 UTC, ruvi-d approved these changes

2021-04-23 10:36 UTC, KavinduZoysa approved these changes

2021-04-23 10:39 UTC, Kishanthan approved these changes

2021-04-23 10:46 UTC, merged