Arith float operations 241
ballerina-platform/nballerina pull request #271
Opened 2021-04-22 00:21 UTC by ramakotareddy

Support for Float Arithmetic Operations

Resolves #241 

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-04-22 00:31 UTC, ramakotareddy commented
Fixed all the review comments from #250. Created separate issue for sign inversion and other missing float arithmetic operation test cases #270.

2021-04-22 05:27 UTC, ruvi-d requested changes

2021-04-22 05:27 UTC, ruvi-d commented on compiler/codegen/BinaryOpInsn.cpp
> +    auto *binaryOpResult = (llvm::Value *)nullptr;
Suggest to place with: `llvm::Value *binaryOpResult = nullptr;`

2021-04-22 05:27 UTC, ruvi-d commented on compiler/codegen/BinaryOpInsn.cpp
> +            binaryOpResult = builder.CreateFCmp(llvm::CmpInst::Predicate::FCMP_OGT, rhsOp1ref, rhsOp2ref, lhstmpName);
Any reason to pic `FCMP_OGT` over `FCMP_UGT`? Better have tests to cover NaN if we are doing OGT and if that is inline with Ballerina spec. 
Ditto for other uses of floating point ordered instruction usage.

2021-04-22 05:27 UTC, ruvi-d commented on test/float/add_float_negative_values.bal
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" "%target_variant" "%skip_bir_gen" | filecheck %s
I think it's ok to move this inside `add_float.bal`
Ditto for the other separate negative value test cases.

2021-04-22 05:27 UTC, ruvi-d commented on test/float/greater_equal_than_float.bal
> +    }
Need to test the equal case too

2021-04-22 05:58 UTC, ramakotareddy commented on compiler/codegen/BinaryOpInsn.cpp
> +            binaryOpResult = builder.CreateFCmp(llvm::CmpInst::Predicate::FCMP_OGT, rhsOp1ref, rhsOp2ref, lhstmpName);
@ruvi-d, there is no particular reason to use  FCMP_OGT, can i use FCMP_UGT instead if FCMP_OGT ?

2021-04-22 06:22 UTC, ruvi-d commented on compiler/codegen/BinaryOpInsn.cpp
> +            binaryOpResult = builder.CreateFCmp(llvm::CmpInst::Predicate::FCMP_OGT, rhsOp1ref, rhsOp2ref, lhstmpName);
@ramakotareddy I am expecting you to figure out what the valid float values are by referring to the Ballerina spec and/or jBallerina implementation. Accordingly, you can pick the ordered or unordered float instructions. If you have any doubts please ask on slack or github discussion.

2021-04-23 02:54 UTC, ramakotareddy commented on compiler/codegen/BinaryOpInsn.cpp
> +            binaryOpResult = builder.CreateFCmp(llvm::CmpInst::Predicate::FCMP_OGT, rhsOp1ref, rhsOp2ref, lhstmpName);
@Ruvi, As per Ballerina Spec and discussion with ayonam, floats are ordered instructions. 
Below cases are printing NaN, Please check once.

    float nanVal = 0.0 / 0.0;
    printf64(nanVal);
    float a = 0.0 % 0.0;
    printf64(a);

Please share small example of any comparison NaN case.

2021-04-23 03:09 UTC, ramakotareddy commented on compiler/codegen/BinaryOpInsn.cpp
> +    auto *binaryOpResult = (llvm::Value *)nullptr;
Fixed

2021-04-23 03:09 UTC, ramakotareddy commented on test/float/add_float_negative_values.bal
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" "%target_variant" "%skip_bir_gen" | filecheck %s
Fixed

2021-04-23 03:10 UTC, ramakotareddy commented on test/float/greater_equal_than_float.bal
> +    }
Added equal case test

2021-04-23 04:11 UTC, ruvi-d requested changes

2021-04-23 04:11 UTC, ruvi-d commented on test/float/greater_equal_than_float.bal
> +    }
I meant something like this:
```
    float a = 5.5;
    float b = 5.5;
    print_boolean(a >= b);  // print true
```

2021-04-23 04:11 UTC, ruvi-d commented on compiler/codegen/BinaryOpInsn.cpp
> +            binaryOpResult = builder.CreateFCmp(llvm::CmpInst::Predicate::FCMP_OGT, rhsOp1ref, rhsOp2ref, lhstmpName);
I don't know where NaN comparison is required. 
But definitely make the NaN print a test case if it is the same behavior on jBallerina

2021-04-23 08:45 UTC, ramakotareddy commented on test/float/greater_equal_than_float.bal
> +    }
@Ruvi, with above test case, always printing false. created new issue #276

2021-04-23 09:32 UTC, ramakotareddy commented on compiler/codegen/BinaryOpInsn.cpp
> +            binaryOpResult = builder.CreateFCmp(llvm::CmpInst::Predicate::FCMP_OGT, rhsOp1ref, rhsOp2ref, lhstmpName);
Created New issue as per discussion in today's call and assign to Manu. #279

2021-04-27 02:46 UTC, ruvi-d approved these changes

2021-04-27 04:09 UTC, KavinduZoysa approved these changes

2021-04-27 04:09 UTC, merged