Add Testcases using llvm LIT framework.
ballerina-platform/nballerina pull request #28
Opened 2020-12-15 18:06 UTC by shubhamnarlawar

2020-12-15 18:06 UTC, shubhamnarlawar commented
Please review the testing infrastructure and suggest changes!

2020-12-15 18:12 UTC, shubhamnarlawar commented
There is small typo in test directory name which is `NBallerian` instead of `NBallerina`.
We will add this change in the upcoming commit in this same PR.

2020-12-16 13:46 UTC, shubhamnarlawar commented
Any suggestions on this PR?

2020-12-16 16:45 UTC, uthaiyashankar commented
Couldn't review yet. Will go through and get back: 

However, the test case directory seems to be wrong (llvm-project-master/llvm/test/). These are not llvm tests, so shouldn't reside in llvm-project-master. It should be moved to root directory under "test" folder or under "BIR2llvmIR/test"

2020-12-16 16:49 UTC, uthaiyashankar commented on BIR2llvmIR/testRunScript.sh
> +WORK_PATH=/home/ramakota/workspace/wso2
Can we node hardcode the absolute paths, please? This will fail for other users.

2020-12-16 16:56 UTC, uthaiyashankar requested changes

2020-12-16 16:56 UTC, uthaiyashankar commented on BIR2llvmIR/testRunScript.sh
> +echo RETVAL=$?
This is just echo the return value. Is there a way to assert?

2020-12-16 17:28 UTC, ayonam commented
Shankar,
    The assert happens in the LIT framework where we mention the
      CHECK: directives within the test file itself.  What gets printed
      here is asserted there.
    
    
      
      
    
    On 16/12/20 22:26, Shankar wrote:
    
    
      
      @uthaiyashankar requested changes on this pull request.
      
      In BIR2llvmIR/testRunScript.sh:
      > +then
+  echo "nballerinacc error. Check err.log"
+  exit 1
+fi
+
+
+clang -O0 -o $filename.out $filename-bir-dump.ll 2>err.log
+
+if [ -s ./err.log ]
+then
+  echo "Clang error. Check err.log"
+  exit 1
+fi
+
+$TESTBUILD_PATH/./$filename.out
+echo RETVAL=$?

      This is just echo the return value. Is there a way to assert?
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ballerina-platform/nballerina/pull/28#pullrequestreview-553888224",
"url": "https://github.com/ballerina-platform/nballerina/pull/28#pullrequestreview-553888224",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

2020-12-16 17:30 UTC, ayonam commented
Yes, I have already asked Ram to modify these.  We discussed this
    today morning.  He is waiting for me to fix the issues with the
    object files in the build directory, so that he can then make
    everything work out of the build directories with relative paths.
    
    
    On 16/12/20 22:20, Shankar wrote:
    
    
      
      @uthaiyashankar commented on this pull request.
      
      In BIR2llvmIR/testRunScript.sh:
      > @@ -0,0 +1,42 @@
+#!/bin/bash
+echo "Input file name is $1"
+FILE=$(basename $1)
+filename="${FILE%.*}"
+echo "file name: $filename"
+
+export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
+WORK_PATH=/home/ramakota/workspace/wso2

      Can we node hardcode the absolute paths, please? This will fail
        for other users.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ballerina-platform/nballerina/pull/28#pullrequestreview-553884532",
"url": "https://github.com/ballerina-platform/nballerina/pull/28#pullrequestreview-553884532",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

2020-12-17 04:56 UTC, dulvinw commented
`llvm-project-master/llvm/test/CodeGen/NBallerian/allop.bal` Theres a typo in the directory name. `NBallerian`

2020-12-17 05:59 UTC, uthaiyashankar commented on BIR2llvmIR/testRunScript.sh
> +$JBALLERINA_PATH/bin/./ballerina build --dump-bir --dump-bir-file=$filename-bir-dump $1 1>out.log 2>err.log
$JBALLERINA_PATH is not defined.

2020-12-17 07:44 UTC, uthaiyashankar commented on BIR2llvmIR/testRunScript.sh
> +echo "Input file name is $1"
This echo statement is affecting the LIT's CHECK statement. This value is taken as the return value (in Mac OS at least)

2020-12-17 07:51 UTC, uthaiyashankar commented on BIR2llvmIR/testRunScript.sh
> +clang -O0 -o $filename.out $filename-bir-dump.ll 2>err.log
we need to pass -Wno-override-module

Reason: We are hardcoding the module target to linux.. When compiling in Mac, it is overriding with mac targets. And it generates following "warning" in err.log, but line 36 will exit if there is an error log. 

Warning generated: 
warning: overriding the module target triple with x86_64-apple-macosx10.15.0 [-Woverride-module]

2020-12-17 07:57 UTC, uthaiyashankar commented on BIR2llvmIR/testRunScript.sh
> +TESTBUILD_PATH=$WORK_PATH/nballerina/build/llvm/test/CodeGen/NBallerian
Do we need this TESTBUILD_PATH? Script works without any issues even without the build path. Anyway, other .ll, -bir-file etc. are relative and they are getting created in the build/llvm/... directory? Can we remove this path?

2020-12-17 07:58 UTC, uthaiyashankar commented on BIR2llvmIR/testRunScript.sh
> +echo RETVAL=$?
It is asserted by LIT framework, hence resolving.

2020-12-17 08:00 UTC, uthaiyashankar commented on BIR2llvmIR/testRunScript.sh
> +$JBALLERINA_PATH/bin/./ballerina build --dump-bir --dump-bir-file=$filename-bir-dump $1 1>out.log 2>err.log
Also, we can remove "--dump-bir" flag. Having only --dump-bir-file=<filename> is enough in this case. Shall we remove the additional flag, please?

2020-12-17 08:03 UTC, ayonam commented
No, the right thing to do here should be to make the nballerina compiler
          generate the proper triple and have the clang which has the
          particular target enabled.  Then this warning should go away. 
          
        
    @Ramakota, can you explore
          how this can be done?  There will be an API to return you the
          native architecture triple.  That needs to be used in the
          generation of LLVM IR.  Then we need to ensure that the LLVM
          pre-built binaries have that triple enabled.
        
    
         
      
      
      
    
    On 17/12/20 13:21, Shankar wrote:
    
    
      
      @uthaiyashankar commented on this pull request.
      
      In BIR2llvmIR/testRunScript.sh:
      > +then
+  echo "JBallerina error . Check err.log"
+  exit 1
+fi
+
+rm $filename-bir-dump.ll
+$NBALLERIAN_PATH/./nballerinacc $filename-bir-dump  2>err.log
+
+if [ -s ./err.log ]
+then
+  echo "nballerinacc error. Check err.log"
+  exit 1
+fi
+
+
+clang -O0 -o $filename.out $filename-bir-dump.ll 2>err.log

      we need to pass -Wno-override-module
      Reason: We are hardcoding the module target to linux.. When
        compiling in Mac, it is overriding with mac targets. And it
        generates following "warning" in err.log, but line 36 will exit
        if there is an error log.
      Warning generated:
        warning: overriding the module target triple with
        x86_64-apple-macosx10.15.0 [-Woverride-module]
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ballerina-platform/nballerina/pull/28#pullrequestreview-554349932",
"url": "https://github.com/ballerina-platform/nballerina/pull/28#pullrequestreview-554349932",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

2020-12-17 08:03 UTC, uthaiyashankar commented on llvm-project-master/llvm/test/CodeGen/NBallerian/simpleMain.bal
> +// CHECK-SAME: 128
I am getting a RETVAL  - 112 (instad of 128) on Mac machine. Can we check whether it is an OS-specific value?

2020-12-17 08:04 UTC, uthaiyashankar commented on llvm-project-master/llvm/test/CodeGen/NBallerian/wso2testcase.bal
> +// RUN: ./../../../../../BIR2llvmIR/testRunScript.sh %s -o - | FileCheck %s
the file name "wso2testcase.bal" is too generic. Can we find a proper name, please?

2021-01-02 13:27 UTC, ramakotareddy commented on llvm-project-master/llvm/test/CodeGen/NBallerian/wso2testcase.bal
> +// RUN: ./../../../../../BIR2llvmIR/testRunScript.sh %s -o - | FileCheck %s
I will change the test file name.

2021-01-05 04:06 UTC, manuranga commented on llvm-project-master/llvm/test/CodeGen/NBallerian/wso2testcase.bal
> +// RUN: ./../../../../../BIR2llvmIR/testRunScript.sh %s -o - | FileCheck %s
and there seem to be a spelling mistake in `NBallerian`.

2021-01-11 18:38 UTC, shubhamnarlawar commented
Generation of object files of src directory is moved to `build/nballerina`. It has been fixed by #39

We will push suggested changes of this PR tomorrow. We are stuck on finding correct API for generating correct triplet based on target architecture.

2021-01-21 13:26 UTC, shubhamnarlawar commented
I have opened a new PR for LIT framework -  #47.
I was getting some merge conflict while fixing some issues in this PR. Hemce, I have opened a new PR. I will close this PR when #47 is merged into the master.

2021-01-21 13:34 UTC, shubhamnarlawar commented on BIR2llvmIR/testRunScript.sh
> +WORK_PATH=/home/ramakota/workspace/wso2
Will be resolved by #47.

2021-01-21 13:35 UTC, shubhamnarlawar commented on BIR2llvmIR/testRunScript.sh
> +$JBALLERINA_PATH/bin/./ballerina build --dump-bir --dump-bir-file=$filename-bir-dump $1 1>out.log 2>err.log
Done. Will be resolved by #47.

2021-01-21 13:35 UTC, shubhamnarlawar commented on BIR2llvmIR/testRunScript.sh
> +TESTBUILD_PATH=$WORK_PATH/nballerina/build/llvm/test/CodeGen/NBallerian
Done. Will be resolved by #47.

2021-01-21 13:36 UTC, shubhamnarlawar commented on llvm-project-master/llvm/test/CodeGen/NBallerian/simpleMain.bal
> +// CHECK-SAME: 128
If its 112 in your case, then it seems a OS specific value. Once we use rust print routines then above issue will be resolved.

2021-01-21 13:36 UTC, shubhamnarlawar commented on llvm-project-master/llvm/test/CodeGen/NBallerian/wso2testcase.bal
> +// RUN: ./../../../../../BIR2llvmIR/testRunScript.sh %s -o - | FileCheck %s
Done. Will be resolved by #47.

2021-01-27 07:53 UTC, shubhamnarlawar commented
Closing this PR. The changes requested in this PR will be present in PR #47

2021-01-27 07:53 UTC, closed without merging