Update readme file
ballerina-platform/nballerina pull request #280
Opened 2021-04-27 03:42 UTC by heshanpadmasiri

## Purpose
> Update readme file to give correct instructions on installing swanlake alpha4

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
>  #258

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-04-27 08:50 UTC, ruvi-d requested changes
Suggest that you only fix the relevant lines and not automatically try to fix other formatting issues

2021-04-27 08:50 UTC, ruvi-d commented on README.md
> +- The nballerinacc (BIR to LLVM IR converter) app : build/nballerinacc
still a few `*` have been replaced with `-`

2021-04-27 08:50 UTC, ruvi-d commented on README.md
> +* cargo installs the dependencies in user's home directory. Hence, add `~/.cargo/bin` to your `PATH` system variable. `export PATH=$PATH:~/.cargo/bin`
This is no longer a sub bullet point

2021-04-27 08:50 UTC, ruvi-d commented on README.md
> +  - `-UCMAKE_CXX_COMPILER` To unset it
ditto on `-`

2021-04-27 09:31 UTC, heshanpadmasiri commented on README.md
> +- The nballerinacc (BIR to LLVM IR converter) app : build/nballerinacc
Fixed by reusing the read me from the master

2021-04-27 09:31 UTC, heshanpadmasiri commented on README.md
> +* cargo installs the dependencies in user's home directory. Hence, add `~/.cargo/bin` to your `PATH` system variable. `export PATH=$PATH:~/.cargo/bin`
Fixed by reusing the read me from the master

2021-04-27 09:58 UTC, ruvi-d requested changes
Please squash the commits to one.

2021-04-28 03:26 UTC, heshanpadmasiri commented
> Please squash the commits to one.

Fixed

2021-04-28 03:37 UTC, ruvi-d approved these changes

2021-04-28 14:56 UTC, KavinduZoysa approved these changes

2021-04-28 14:56 UTC, merged