Represent array struct in LLVM side and migrate rust array to match
ballerina-platform/nballerina pull request #285
Opened 2021-04-29 06:48 UTC by heshanpadmasiri

## Purpose
Represent the arrays in LLVM structs and make the runtime library create objects matching that type
Resolves #272, #278

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
* Change the LLVM type definition for array from i8 pointer to a pointer to a struct given in #272
* Change the rust runtime to create, store and load from such a pointer (currently implemented only for int)

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-04-29 08:13 UTC, ruvi-d commented on runtime/src/bal_array.rs
> +}
Missing EoF

2021-04-29 08:24 UTC, ruvi-d commented on runtime/src/bal_array.rs
> +               let new_size = self.capacity * GROWTH_FACTOR;
Have to keep growing till new index fits

2021-04-29 08:27 UTC, ruvi-d commented on runtime/src/lib.rs
> +    let vec_pointer = Box::into_raw(array);
vec_pointer is a bad variable name here

2021-04-29 08:27 UTC, ruvi-d commented on runtime/Cargo.toml
> +libc = "0.2.94"
Missing EoF

2021-04-29 08:35 UTC, ruvi-d commented on compiler/codegen/ArrayInsns.cpp
> +    builder.CreateStore(bitCastRes, lhsOpRef);
I assume the bitcase is not required here?

2021-04-29 08:56 UTC, ruvi-d commented
One more thing.
Need to support this : https://github.com/ballerina-platform/nballerina/blob/master/test/array/load_store_int_array_print_empty_value.bal

So when you are expanding the array, you need to fill it with empty values too. i.e. 0 for int types

2021-04-29 09:37 UTC, KavinduZoysa commented on runtime/src/bal_array.rs
> +
This new line is not needed.

2021-04-29 09:52 UTC, heshanpadmasiri commented on runtime/src/lib.rs
> +    let vec_pointer = Box::into_raw(array);
changed to array_pointer

2021-04-29 09:52 UTC, heshanpadmasiri commented on runtime/src/bal_array.rs
> +}
fixed

2021-04-29 09:52 UTC, heshanpadmasiri commented on runtime/src/bal_array.rs
> +               let new_size = self.capacity * GROWTH_FACTOR;
fixed

2021-04-29 09:52 UTC, heshanpadmasiri commented on runtime/src/bal_array.rs
> +            if self.capacity <= index {
That if block is trying to see if we need to grow the underlying memory block to store the value and I am taking the size of that as the capacity

2021-04-29 09:52 UTC, heshanpadmasiri commented on runtime/Cargo.toml
> +libc = "0.2.94"
fixed

2021-04-29 09:52 UTC, heshanpadmasiri commented on compiler/codegen/CodeGenUtils.cpp
> +            auto *dynamicArrayType = module.getTypeByName("struct.dynamicArray");
fixed

2021-04-29 09:52 UTC, heshanpadmasiri commented on compiler/codegen/CodeGenUtils.cpp
> +        if (dynamicBalArrayType == nullptr) {
fixed

2021-04-29 09:52 UTC, heshanpadmasiri commented on compiler/codegen/ArrayInsns.cpp
> +    builder.CreateStore(bitCastRes, lhsOpRef);
Fixed by changing the array init function signature in the cpp side to return a struct pointer type and removing the bit cast

2021-04-29 09:54 UTC, heshanpadmasiri commented
> One more thing.
> Need to support this : https://github.com/ballerina-platform/nballerina/blob/master/test/array/load_store_int_array_print_empty_value.bal
> 
> So when you are expanding the array, you need to fill it with empty values too. i.e. 0 for int types

Since I am using calloc to allocated memory it should fill entire block with 0

2021-04-29 09:54 UTC, heshanpadmasiri commented on runtime/src/bal_array.rs
> +
Fixed

2021-04-29 10:14 UTC, ruvi-d commented on runtime/src/bal_array.rs
> +            if self.capacity <= index {
got it

2021-04-29 10:21 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +        llvm::FunctionType::get(llvm::PointerType::getUnqual(module.getTypeByName("struct.dynamicBalArray")),
Genrally we want to avoid using magic values like  "struct.dynamicBalArray".
Use `getLLVMTypeOfType(TYPE_TAG_ARRAY) to get the type here. Otherwise if the name changes, you will have to update in two places.

2021-04-29 14:32 UTC, heshanpadmasiri commented on compiler/codegen/CodeGenUtils.cpp
> +        llvm::FunctionType::get(llvm::PointerType::getUnqual(module.getTypeByName("struct.dynamicBalArray")),
Fixed

2021-04-30 04:59 UTC, ruvi-d commented on runtime/src/bal_array.rs
> +                values: DynamicBalArray::allocate_memory(size_t),
I was going through the design again and I think we have a problem here. 

I think we need to allocate memory within `DynamicArray` and not allocate memory externally.
As in for a Dynamic array of capacity 4, the structure should look like
```
struct DynamicArray {
        header: u64,
        values1: i64,
        values2: i64,
        values3: i64,
        values4: i64,
    }
```
Otherwise with `values: *mut i64,`, there is no point of having a DynamicArray struct.

@manuranga  your input please

2021-04-30 05:28 UTC, ruvi-d commented on runtime/src/bal_array.rs
> +                let new_array = DynamicBalArray::allocate_memory(new_size);
`realloc` should be a better choice here 
https://doc.rust-lang.org/stable/std/alloc/fn.realloc.html

2021-05-01 05:30 UTC, ruvi-d commented on runtime/src/bal_array.rs
> +                values: DynamicBalArray::allocate_memory(size_t),
e.g. from the BalMap implementation 
https://github.com/ruvi-d/nballerina/blob/ruvi/task/new_balmap/runtime/c_rt/include/balmap.h#L15
https://github.com/ruvi-d/nballerina/blob/ruvi/task/new_balmap/runtime/c_rt/src/balmap.c#L44

2021-05-03 07:16 UTC, heshanpadmasiri commented on runtime/src/bal_array.rs
> +                values: DynamicBalArray::allocate_memory(size_t),
For clarification is this is just move the memory management logic (memeory allocation and resizing) in to DynamicArray (from DynamicBalArray) where the DynamicArray will still have a pointer to a memory block with all the values (which we then access by pointer offset) or should the  structure of DynamicArray change such that each value in it is a separate variable

2021-05-03 07:48 UTC, ruvi-d commented on runtime/src/bal_array.rs
> +                values: DynamicBalArray::allocate_memory(size_t),
> or should the structure of DynamicArray change such that each value in it is a separate variable

I don't think that is possible unless you use something like C++ templates. Even if you did implement it using templates, you wouldn't be able to call generic functions from LLVM.
So, I think what you need is something like https://en.wikipedia.org/wiki/Flexible_array_member, which is what I've used in the `balmap` example I linked above.

2021-05-03 11:21 UTC, heshanpadmasiri commented on runtime/src/bal_array.rs
> +                values: DynamicBalArray::allocate_memory(size_t),
Changed such that entire DynamicArray is [allocated directly](https://github.com/heshanpadmasiri/nballerina/blob/6110191fe21a49ee1ad021b4cb6719e932488135/runtime/src/bal_array.rs#L45) and [resized directly](https://github.com/heshanpadmasiri/nballerina/blob/6110191fe21a49ee1ad021b4cb6719e932488135/runtime/src/bal_array.rs#L73)

2021-05-03 11:21 UTC, heshanpadmasiri commented on runtime/src/bal_array.rs
> +                let new_array = DynamicBalArray::allocate_memory(new_size);
Fixed with [grow_array ](https://github.com/heshanpadmasiri/nballerina/blob/6110191fe21a49ee1ad021b4cb6719e932488135/runtime/src/bal_array.rs#L69) function

2021-05-04 01:36 UTC, ruvi-d requested changes

2021-05-04 01:36 UTC, ruvi-d commented on compiler/codegen/ArrayInsnsCodeGen.cpp
> +        rhsOpTempRef, builder.getInt8PtrTy(), "");
Can drop the third arg since it's the default value: https://llvm.org/doxygen/classllvm_1_1IRBuilderBase.html#a06d64f226fabd94d694d6abd82e3c7b3

2021-05-04 01:36 UTC, ruvi-d commented on compiler/codegen/ArrayInsnsCodeGen.cpp
> +        lhsOpTempRef, builder.getInt8PtrTy(), "");
Ditto about ""

2021-05-04 03:42 UTC, heshanpadmasiri commented on compiler/codegen/ArrayInsnsCodeGen.cpp
> +        lhsOpTempRef, builder.getInt8PtrTy(), "");
Fixed

2021-05-04 03:43 UTC, heshanpadmasiri commented on compiler/codegen/ArrayInsnsCodeGen.cpp
> +        rhsOpTempRef, builder.getInt8PtrTy(), "");
Fixed

2021-05-04 05:31 UTC, ruvi-d requested changes
No comments about the

2021-05-04 05:31 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +    case TYPE_TAG_ARRAY: {
Better make a note that as of this PR this new array type is only valid for `int[]` type; Other types like `float[]` would be still using `Int8PtrTy`; even though we are are not handling it explicitly.

2021-05-04 05:31 UTC, ruvi-d commented on compiler/codegen/ArrayInsnsCodeGen.cpp
> +        rhsOpTempRef, builder.getInt8PtrTy());
Make a note that this is also only a temp requirement as we can update the load and store function declaration to pass a DynamicBalArray type pointer.

2021-05-04 05:31 UTC, ruvi-d commented on runtime/src/bal_array.rs
> +    }
These two structs should have `#[repr(C)]` annotations so that their alignment is consistent with what we defined in LLVM

2021-05-04 05:31 UTC, ruvi-d commented on runtime/src/bal_array.rs
> +        }
Need someone to review this get_layout logic

2021-05-04 09:36 UTC, heshanpadmasiri commented on compiler/codegen/CodeGenUtils.cpp
> +    case TYPE_TAG_ARRAY: {
Add a comment in the file stating the current state of implementation

2021-05-04 09:37 UTC, heshanpadmasiri commented on compiler/codegen/ArrayInsnsCodeGen.cpp
> +        rhsOpTempRef, builder.getInt8PtrTy());
Changed the function definition to use the new type and add the comment there as well saying for other array types it is silently ignored

2021-05-04 09:37 UTC, heshanpadmasiri commented on runtime/src/bal_array.rs
> +    }
Fixed

2021-05-05 01:24 UTC, ruvi-d approved these changes
Need to address : https://github.com/ballerina-platform/nballerina/pull/285/files#r625517875

2021-05-05 11:14 UTC, KavinduZoysa commented on runtime/src/bal_array.rs
> +        }
@heshanpadmasiri, can you please explain it here?

2021-05-05 11:39 UTC, heshanpadmasiri commented on runtime/src/bal_array.rs
> +        }
In order to use the rust [alloc](https://doc.rust-lang.org/alloc/alloc/fn.alloc.html) I have to give it a [layout](https://doc.rust-lang.org/std/alloc/struct.Layout.html) of how that memory block should look like. This function gives the memory layout for a [DynamicArray](https://github.com/heshanpadmasiri/nballerina/blob/55e2d7c592285530a4c921dc9ff8c91563e7b37f/runtime/src/bal_array.rs#L37) of a given capacity. 

Since the header is i64 and it's layout is defined in rust i used it directly as the header_layout
For values since it is a i64 array I used the array layout as described [here](https://doc.rust-lang.org/reference/type-layout.html). (Basically it says the alignment is the same as the data type and size is n time the size of type. Since size of returns a usize I thought n must also be usize)

Finally to create the layout for the DynamicArray I extended the layout for header with the layout for value which should give the memory layout for a object with header fallowed by the values

2021-05-05 14:52 UTC, KavinduZoysa commented on runtime/src/bal_array.rs
> +        }
Thanks got it. Can't we set the type of capacity as u64 and do a change like this? 

`let size = capacity * mem::size_of::<i64>();`

2021-05-06 02:51 UTC, heshanpadmasiri commented on runtime/src/bal_array.rs
> +        }
We can't because `mem::size_of::<i64>()` returns a `usize` and it can be multiplied only with another `usize`

2021-05-06 03:19 UTC, manuranga commented on runtime/src/bal_array.rs
> +            unsafe {
ideally `unsafe` should be short as possible. does all of this code needs to be in unsafe.

2021-05-06 03:58 UTC, KavinduZoysa commented on runtime/src/bal_array.rs
> +        }
Yes, that's correct. My suggestion was to change the method to accept `u64` instead of i64 `fn get_layout(capacity: u64)`. Then we can simply multiply, right?

2021-05-06 04:28 UTC, heshanpadmasiri commented on runtime/src/bal_array.rs
> +            unsafe {
The problem is unsafe also defines the scope. I need unsafe to allocate memory in to the `raw_ptr`. And I can't access the `raw_ptr` (which I need to check if the allocation is successful and create the `dynamic_array` pointers) outside of unsafe.

2021-05-06 04:32 UTC, heshanpadmasiri commented on runtime/src/bal_array.rs
> +        }
No, what I am saying is if we are to avoid the casting capacity can't be an integer it must be a `usize`. That way it will work fine in the rust side but we may run in to issues if try to access it outside of rust.

2021-05-11 04:56 UTC, manuranga commented on compiler/codegen/CodeGenUtils.cpp
> +        assert(module.getTypeByName("struct.dynamicArray") == nullptr);
should this be 
```suggestion
        assert(module.getTypeByName("struct.dynamicBalArray") == nullptr);
```

2021-05-11 07:17 UTC, manuranga commented on compiler/codegen/CodeGenUtils.cpp
> +        assert(module.getTypeByName("struct.dynamicArray") == nullptr);
Oh i just realized this is the growing part of the array.

2021-05-17 03:52 UTC, manuranga commented on runtime/src/bal_array.rs
> +        }
Actually values need not to be aligned, the header is. We have references form stack to header, pointer to value is private.

2021-05-17 03:59 UTC, manuranga commented on runtime/src/bal_array.rs
> +                if new_size > old_capacity {
better to use something slimier to memcpy, no need to do in this pr, because runtime impl will change. just to comment.

2021-05-17 04:00 UTC, manuranga commented on runtime/src/bal_array.rs
> +                if new_size > old_capacity {
oh i got it worng this is remainder, isn't this zeroed out by allocater ?

2021-05-17 04:02 UTC, manuranga commented on runtime/src/bal_array.rs
> +        }
btw, out initial idea to allocate header and body in one go might not work, because GC needs to know about them separately.

2021-05-17 04:05 UTC, manuranga commented on runtime/src/bal_array.rs
> +                if new_size > old_capacity {
ahh I see it's realloc

2021-05-17 04:11 UTC, manuranga approved these changes

2021-05-17 04:18 UTC, manuranga commented on runtime/src/bal_array.rs
> +            unsafe {
following rust code works for me
```
use std::alloc::{alloc_zeroed, Layout};

fn main() {
    let layout = Layout::new::<u16>();
    let raw_ptr;
    unsafe{
        raw_ptr = alloc_zeroed(layout);
    }
    println!("Hello, world! {:#?}", raw_ptr);
}
```
this doesn't need to be fixed right away, because we very likely to rewrite this but just to comment

2021-05-17 04:36 UTC, merged

2021-05-17 05:44 UTC, heshanpadmasiri commented on runtime/src/bal_array.rs
> +            unsafe {
Fixed in the byte array implementation

2021-05-17 05:51 UTC, heshanpadmasiri commented on runtime/src/bal_array.rs
> +        }
If we are to break the header and body allocation in to two when the array get resized I assume we resize only the value and leave the header intact. Or should we reallocate both again as well.

2021-05-17 07:46 UTC, manuranga commented on runtime/src/bal_array.rs
> +        }
yes we'll only need to reallocate the values. please take a look at map impl's grow logic.
If we reallocate header, we need to update pointers to it from everywhere (ie: like moving GC), which we don't plan to support.