Migrate String New Representation
ballerina-platform/nballerina pull request #291
Opened 2021-05-05 18:08 UTC by shubhamnarlawar

Resolves #273.

2021-05-05 18:13 UTC, shubhamnarlawar commented on compiler/codegen/Package.cpp
> +    builder.CreateMemCpy(loadUtf, llvm::Align(1), value, llvm::Align(1), stringValue.length());
`CreateMemCpy` is generating `immarg` at end of its param list.

```
error: expected ')' at end of argument list
declare void @llvm.memcpy.p0i8.p0i8.i64(i8* noalias nocapture writeonly, i8* noalias nocapture readonly, i64, i1 immarg) #0
```

and also,
```
error: unterminated attribute group
attributes #0 = { argmemonly nounwind willreturn }
```

2021-05-06 04:50 UTC, manuranga commented on compiler/codegen/Package.cpp
> +    builder.CreateMemCpy(loadUtf, llvm::Align(1), value, llvm::Align(1), stringValue.length());
we should not need any runtime memcpy for string literal, we should be passing them by pointers

2021-05-09 17:30 UTC, shubhamnarlawar commented on compiler/codegen/Package.cpp
> +    builder.CreateMemCpy(loadUtf, llvm::Align(1), value, llvm::Align(1), stringValue.length());
Removed memcpy operation.

2021-05-12 17:06 UTC, shubhamnarlawar commented
Now, with the latest changes - 

LLVM IR - 

```
entry:
  %"%0" = alloca i8*, align 8
  %"%1" = alloca %struct.balAsciiString, align 8
  br label %bb0

bb0:                                              ; preds = %entry
  store %struct.balAsciiString { i64 6, i64 5, [5 x i8] c"hello" }, %struct.balAsciiString* %"%1", align 8
```

Instead of `alloca` of balAsciiString, it should be `constant balAsciiString`.

2021-05-12 17:09 UTC, shubhamnarlawar commented
The equivalent LLVM IR of a C code -

```
@.str = private unnamed_addr constant [6 x i8] c"hello\00", align 1
@bal_string = dso_local constant %struct.BalAsciiString { i32 43981, i32 6, i8* getelementptr inbounds ([6 x i8], [6 x i8]* @.str, i32 0, i32 0) }, align 8
```

which is generating two .rodata section.

I am planning to generate both string constant and struct constant in the same .rodata section.

2021-05-16 18:16 UTC, shubhamnarlawar commented
Now, with the latest changes, I am able to generate struct constant and pass a pointer to it on the rust side.

`print_string("hello");`

LLVM IR -

```
; ModuleID = '$anon.0.0.0'
source_filename = "t.bal"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

%struct.balAsciiString = type { i64, i64, i8* }

@__string_table_ptr = internal global i8* null, align 4
@"$annotation_data" = global i8* null, align 4
@.str = private constant [5 x i8] c"hello"
@bal_string = private constant %struct.balAsciiString { i64 6, i64 5, i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.str, i64 0, i64 0) }
@ptr = private constant %struct.balAsciiString* @bal_string

declare i8* @print_string(%struct.balAsciiString*)

define void @main() {
entry:
  %"%0" = alloca i8*, align 8
  %"%1" = alloca %struct.balAsciiString*, align 8
  %"%2" = alloca i8*, align 8
  br label %bb0

bb0:                                              ; preds = %entry
  %0 = load %struct.balAsciiString*, %struct.balAsciiString** @ptr, align 8
  store %struct.balAsciiString* %0, %struct.balAsciiString** %"%1", align 8
  %"%1_temp" = load %struct.balAsciiString*, %struct.balAsciiString** %"%1", align 8
  %call = call i8* @print_string(%struct.balAsciiString* %"%1_temp")
  store i8* %call, i8** %"%2", align 8
  br label %bb1

bb1:                                              ; preds = %bb0
  br label %bb3

bb2:                                              ; No predecessors!
  br label %bb3

bb3:                                              ; preds = %bb2, %bb1
  ret void
}

```

2021-05-16 18:18 UTC, shubhamnarlawar commented
At rust side, I am getting below opaque pointer - 

```
(gdb) p *ascii_ptr
$2 = ballerina_rt::BalAsciiString {header: 6, n_bytes: 5, bytes: &[char] {data_ptr: 0x22d650 "hello\000\000\000", length: 988461440040959}}
```

2021-05-16 18:35 UTC, shubhamnarlawar commented
> At rust side, I am getting below opaque pointer -
> 
> ```
> (gdb) p *ascii_ptr
> $2 = ballerina_rt::BalAsciiString {header: 6, n_bytes: 5, bytes: &[char] {data_ptr: 0x22d650 "hello\000\000\000", length: 988461440040959}}
> ```

Here, we have the string length stored as n_bytes, but length seems garbage value. (I suspect due to non terminated string from llvm side)

2021-05-17 08:06 UTC, shubhamnarlawar commented
I have updated `print_string()` which is now correctly printing the constant string. With above changes, all tests except anydata, map, optional-type are passing.

Now, as `test/anydata test/map test/optional-type` are dependant on old `BString` which uses rust `&str`, 

Old structure - (is also present in the code)

```
pub struct BString {
    value: &'static str,
}
```

The current structure - 

```
#[repr(C)]
pub struct BalAsciiString {
    header: u64,
    n_bytes: u64,
    bytes: *const u8,
}
```

All the rust functions related to array, map, any, optional type needs to be migrated to use BalAsciiString right? That means converting `*const u8` to `&str` at appropriate places at rust side.

WDYT? @manuranga @ruvi-d

2021-05-17 08:23 UTC, ruvi-d commented
> All the rust functions related to array, map, any, optional type needs to be migrated to use BalAsciiString right? That means converting `*const u8` to `&str` at appropriate places at rust side.
> 
> WDYT? @manuranga @ruvi-d

Yes! please update where applicable. Should be a minor change on the Rust side to support map. 
What is `optional` and `anydata` type's dependency with Strings?
With you PR, I'd expect to see no more references to `BString`.

2021-05-17 11:22 UTC, shubhamnarlawar commented
> > All the rust functions related to array, map, any, optional type needs to be migrated to use BalAsciiString right? That means converting `*const u8` to `&str` at appropriate places at rust side.
> > WDYT? @manuranga @ruvi-d
> 
> Yes! please update where applicable. Should be a minor change on the Rust side to support map.
> What is `optional` and `anydata` type's dependency with Strings?
> With you PR, I'd expect to see no more references to `BString`.

Got it. I am working on it.
I think anydata and optional testcases contains strings - 
e.g. `map<anydata> marks = {jon: 60};`

2021-05-17 11:47 UTC, shubhamnarlawar commented
@ruvi-d - For map store and load for int, I am getting different function signature - 

`declare void @map_store_int(i8*, %struct.balAsciiString*, i64)`

`declare i8 @map_load_int(i8*, i8*, i64*)`

Can you please point the source code on why map_load is happening with i8* and map_store is happening with opaque pointer `balAsciiString` earlier `BString`.

2021-05-17 12:08 UTC, shubhamnarlawar commented
> @ruvi-d - For map store and load for int, I am getting different function signature -
> 
> `declare void @map_store_int(i8*, %struct.balAsciiString*, i64)`
> 
> `declare i8 @map_load_int(i8*, i8*, i64*)`
> 
> Can you please point the source code on why map_load is happening with i8* and map_store is happening with opaque pointer `balAsciiString` earlier `BString`.

Found the signatures in `CodeGenUtils`. But can you state reason for it?

2021-05-17 12:08 UTC, ruvi-d commented
> Can you please point the source code on why map_load is happening with i8* and map_store is happening with opaque pointer `balAsciiString` earlier `BString`.

@shubhamnarlawar since my last comment #288 was merged and now the Map functions are in `runtime/c_rt`
Please refer : 
* String def : https://github.com/ballerina-platform/nballerina/blob/master/runtime/c_rt/include/common.h#L45
* Map APIs : https://github.com/ballerina-platform/nballerina/blob/master/runtime/c_rt/include/balmap.h#L45

If it seems that it will take too long to support maps, just disable the test, create a new task to add support back and assign it to me.

2021-05-17 12:12 UTC, ruvi-d commented
> Found the signatures in `CodeGenUtils`. But can you state reason for it?

map_load return is a bool to indicate success or failure. The actual value is got via an out param, the `i64*` value. The detail reasons are here : https://github.com/ballerina-platform/nballerina/discussions/230

Hope that is sufficient for you to carry on?

2021-05-17 13:45 UTC, shubhamnarlawar commented
> > Can you please point the source code on why map_load is happening with i8* and map_store is happening with opaque pointer `balAsciiString` earlier `BString`.
> 
> @shubhamnarlawar since my last comment #288 was merged and now the Map functions are in `runtime/c_rt`
> Please refer :
> 
>     * String def : https://github.com/ballerina-platform/nballerina/blob/master/runtime/c_rt/include/common.h#L45
> 
>     * Map APIs : https://github.com/ballerina-platform/nballerina/blob/master/runtime/c_rt/include/balmap.h#L45
> 
> 
> If it seems that it will take too long to support maps, just disable the test, create a new task to add support back and assign it to me.

Got it. I have modified all the map changes related to rust. Since, you C runtime PR got merged recently, I try to replicate similar changes.

2021-05-17 13:46 UTC, shubhamnarlawar commented
> > Found the signatures in `CodeGenUtils`. But can you state reason for it?
> 
> map_load return is a bool to indicate success or failure. The actual value is got via an out param, the `i64*` value. The detailed reasons are here : #230
> 
> Hope that is sufficient for you to carry on?

Got it. Thanks for the explantation.
Yes.

2021-05-17 15:05 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        llvm::ArrayRef<llvm::Constant *> elements = {header, size, static_cast<llvm::Constant *>(valueRef)};
@ruvi-d - I am casting from `LLVMValueRef` to `llvm::Constant` using `static_cast` and hence due to this warning all the tests are failing. Can you please suggest alternate way here?

By disabling sanitizers, all tests except map and optional type are passing. Map and optional type tests are failing as the code is now moved to C runtime. Functionality wise, this PR is completed. (review remaining).

2021-05-17 15:09 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        llvm::ArrayRef<llvm::Constant *> elements = {header, size, static_cast<llvm::Constant *>(valueRef)};
Here, valueRef is GEP of the std::string and needs to pass it as llvm::Constant for creation of constant struct object.

2021-05-17 15:35 UTC, ruvi-d commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        llvm::ArrayRef<llvm::Constant *> elements = {header, size, static_cast<llvm::Constant *>(valueRef)};
What's the warning that's causing the test failure?

2021-05-17 15:44 UTC, ruvi-d commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        llvm::ArrayRef<llvm::Constant *> elements = {header, size, static_cast<llvm::Constant *>(valueRef)};
For your reference : https://llvm.org/docs/ProgrammersManual.html#the-isa-cast-and-dyn-cast-templates

2021-05-18 07:26 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        llvm::ArrayRef<llvm::Constant *> elements = {header, size, static_cast<llvm::Constant *>(valueRef)};
Thanks for the link. It is helpful👍🏻

I could not replicate why the PR workflow run is causing all tests to fail. I followed all build steps on our server and all tests except map and optional type are passing.

2021-05-18 07:35 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        llvm::ArrayRef<llvm::Constant *> elements = {header, size, static_cast<llvm::Constant *>(valueRef)};
In release mode, all tests are failing in nballerinaacc phase.

2021-05-18 07:37 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        auto *constStruct = llvm::ConstantStruct::get(structType, elements);
This line is causing segmentation fault in release mode and hence difficult to debug.

In debug mode all tests except map and optional type are passing.

2021-05-18 07:41 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        llvm::ArrayRef<llvm::Constant *> elements = {header, size, static_cast<llvm::Constant *>(valueRef)};
I suspect it is due to casting. I am checking usage of dyn_cast to solve above problem.

2021-05-18 08:53 UTC, ruvi-d commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        auto *constStruct = llvm::ConstantStruct::get(structType, elements);
Does this mean that you are able to replicate the issue with the release builds on your end?

2021-05-18 08:55 UTC, ruvi-d commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        auto *constStruct = llvm::ConstantStruct::get(structType, elements);
Two other points: try using std::vector for `llvm::ArrayRef<llvm::Constant *> elements` and also note that Github PR check is using clang-11 instead of gcc to build (since #288).

2021-05-18 09:11 UTC, ruvi-d commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        auto *constStruct = llvm::ConstantStruct::get(structType, elements);
@shubhamnarlawar : I checked out your code and can confirm that `std::vector<llvm::Constant *> elements{header, size, static_cast<llvm::Constant *>(valueRef)};` resolves your issue.

2021-05-18 09:14 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        auto *constStruct = llvm::ConstantStruct::get(structType, elements);
Yes. Now, with vector, it resolves the issue.
Thanks for the help.

Earlier, at my end tests in release mode were failing. (same as PR workflow).

2021-05-18 09:15 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        auto *constStruct = llvm::ConstantStruct::get(structType, elements);
Now, I am investigating map and optional type test issue. (Should be minor change. Earlier, I fixed those in rust runtime).

2021-05-18 13:18 UTC, shubhamnarlawar commented
I have replicated changes in C runtime. Now all the tests are passing.

@ruvi-d - There seems an issue with workflow run, it is running but I can not see the log.

Same is happening with #308

2021-05-18 14:23 UTC, ruvi-d commented
> I have replicated changes in C runtime. Now all the tests are passing.
> 
> @ruvi-d - There seems an issue with workflow run, it is running but I can not see the log.
> 
> Same is happenin

Issue with actions appears to be on GitHub side
https://www.githubstatus.com/history

2021-05-18 14:43 UTC, shubhamnarlawar commented
> > I have replicated changes in C runtime. Now all the tests are passing.
> > @ruvi-d - There seems an issue with workflow run, it is running but I can not see the log.
> > Same is happenin
> 
> Issue with actions appears to be on GitHub side
> https://www.githubstatus.com/history

Can you please give review of the code

2021-05-18 14:50 UTC, ruvi-d requested changes

2021-05-18 14:50 UTC, ruvi-d commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        }
Duplicated logic from Type::getLLVMTypeOfTag(). Please use that function to get the struct type.

2021-05-18 14:50 UTC, ruvi-d commented on runtime/c_rt/include/common.h
> +    uint64_t n_bytes;
Line 58 needs to be updated `size_t n = strlen(p);`
value is not null terminated so n_bytes needs to be used instead

2021-05-18 14:50 UTC, ruvi-d commented on runtime/rust_rt/src/lib.rs
> +    let ptr = unsafe { (*ascii_ptr).value };
assert that ascii_ptr.value is also not null

2021-05-18 14:50 UTC, ruvi-d commented on runtime/rust_rt/src/lib.rs
> +    }
printing character by character is not efficient. Can you construct a string from value and n_bytes ?

2021-05-18 14:50 UTC, ruvi-d commented on runtime/rust_rt/src/lib.rs
> +pub extern "C" fn deinit_string(ptr: *mut BalAsciiString) {
deinit is not required because we are not allocating from the Rust side

2021-05-18 14:50 UTC, ruvi-d commented on runtime/rust_rt/src/lib.rs
> +    return unsafe { CStr::from_ptr(key as *const i8) }.to_str().unwrap()
Unused function?

2021-05-19 02:34 UTC, ruvi-d commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +                                             llvm::GlobalValue::PrivateLinkage, globalStruct, "ptr");
Why do we need this "ptr" global variable to hold a pointer value of  "bal_string" ?

It look like you are creating three RO section entries for each string literal. 1) The Char array 2) A Bal String struct that points to the said Char array 3) A pointer to the said Bal String struct.
Do we really need #3?

2021-05-19 07:47 UTC, ruvi-d commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +            globalValue, llvm::ArrayRef<llvm::Value *>({builder.getInt64(0), builder.getInt64(0)}), "simple");
We don't need `simple` name here as valueRef name won't show up anyway (since it's used for the global variable GEP)

2021-05-19 08:00 UTC, shubhamnarlawar commented on runtime/rust_rt/src/lib.rs
> +    let ptr = unsafe { (*ascii_ptr).value };
Done.

2021-05-19 08:01 UTC, shubhamnarlawar commented on runtime/rust_rt/src/lib.rs
> +    }
Generated `&str` and printing it directly now.

2021-05-19 08:01 UTC, shubhamnarlawar commented on runtime/rust_rt/src/lib.rs
> +    return unsafe { CStr::from_ptr(key as *const i8) }.to_str().unwrap()
Yes. Removed.

2021-05-19 08:01 UTC, shubhamnarlawar commented on runtime/rust_rt/src/lib.rs
> +pub extern "C" fn deinit_string(ptr: *mut BalAsciiString) {
Removed.

2021-05-19 08:02 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +                                             llvm::GlobalValue::PrivateLinkage, globalStruct, "ptr");
You are right. Looks like I don't need a ptr variable to store the struct. Instead I am storing it to generated local variable `alloca %struct*`.

Removed pointer to balAsciiStruct!

2021-05-19 08:05 UTC, shubhamnarlawar commented on runtime/c_rt/include/common.h
> +    uint64_t n_bytes;
I tried changing above `uint64_t n_bytes` to `size_t n_bytes` and

`size_t n = s->n_bytes` which is causing 2nd c_rt test failing as - `Segmentation fault`. I am looking into it.

2021-05-19 08:06 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +            globalValue, llvm::ArrayRef<llvm::Value *>({builder.getInt64(0), builder.getInt64(0)}), "simple");
Got it. I will remove it.

2021-05-19 08:09 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        }
That function actually returns - `Pointer to Type*` which again need to dereference it to `Type*` followed by a dynamic cast to `StructType*`.

I am checking appropriate API for converting it as - 

`Pointer to Type*` -> `Type*` -> `StructType*`

2021-05-19 08:14 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        }
You mean `CodeGenUtils::getLLVMTypeOfType()`?

That function actually returns - `Pointer to Type*` which again need to dereference it to `Type*` followed by a dynamic cast to `StructType*`.

I am checking appropriate API for converting it as - 

`Pointer to Type*` -> `Type*` -> `StructType*`

2021-05-19 08:29 UTC, ruvi-d commented on runtime/c_rt/include/common.h
> +    uint64_t n_bytes;
looks like there are few changes required here:
1) Keep `uint64_t n_bytes` 
2) Update the string comparison on common (strcmp doesn't work wince it's not null terminated)
```
inline static bool bal_string_equals(BalStringPtr str1, BalStringPtr str2) {
    if (str1 == str2) {
        return true;
    }
    if (str1->n_bytes != str2->n_bytes) {
        return false;
    }
    return memcmp(str1->value, str2->value, str2->n_bytes) == 0;
}
```
3) Update test/main.cpp  and set the n_bytes

2021-05-19 09:07 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +            globalValue, llvm::ArrayRef<llvm::Value *>({builder.getInt64(0), builder.getInt64(0)}), "simple");
Removed.

2021-05-19 09:08 UTC, shubhamnarlawar commented on runtime/c_rt/include/common.h
> +    uint64_t n_bytes;
Updated above C runtime changes along with relevant changes. Thanks for the code snippet.

2021-05-19 09:30 UTC, ruvi-d commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        }
Got it your point. 
I'd create a common function called `llvm::StructType *CodeGenUtils::getStringStructType()` and have `CodeGenUtils::getLLVMTypeOfType()` and `void NonTerminatorInsnCodeGen::visit(ConstantLoadInsn &obj, llvm::IRBuilder<> &builder)` call it.
`getLLVMTypeOfType()` will ofcoz have to call `llvm::PointerType::get()` on  `getStringStructType()`'s return value.

2021-05-19 10:40 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        }
Done. Thanks.

Earlier, I have added similar function in `CodeGenUtils` but later I had removed it.

2021-05-19 10:59 UTC, ruvi-d requested changes

2021-05-19 10:59 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +    assert(typeTag == TYPE_TAG_CHAR_STRING || typeTag == TYPE_TAG_STRING);
We can omit `TypeTag typeTag` arg. It's not adding any value here.

2021-05-19 10:59 UTC, ruvi-d commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        constRef = globalStruct;
directly assign to `constRef` as
```
constRef = new llvm::GlobalVariable(moduleGenerator.getModule(), structType, true, llvm::GlobalValue::PrivateLinkage, constStruct, "bal_string");
```

2021-05-19 10:59 UTC, ruvi-d commented on runtime/c_rt/test/main.cpp
> +    BalString bstring1 = {.header = 1, .n_bytes = 1, .value = "1"};
We should probably add a function to create a BalString from char*. No need to do that in this PR, JFYI. I'll take it up in a separately PR.

2021-05-19 10:59 UTC, ruvi-d commented on runtime/rust_rt/src/lib.rs
> +    let _string: &str = unsafe { CStr::from_ptr(ptr as *const i8) }.to_str().unwrap();
You are not using `n_bytes` here to construct the string, so I am assuming that this will generally fail for non null terminated char * ?

2021-05-19 11:56 UTC, shubhamnarlawar commented on runtime/rust_rt/src/lib.rs
> +    let _string: &str = unsafe { CStr::from_ptr(ptr as *const i8) }.to_str().unwrap();
Yes. It will fail.
I will find a conversion that takes const char * and length to construct a rust str.

2021-05-19 12:01 UTC, shubhamnarlawar commented on runtime/rust_rt/src/lib.rs
> +    let _string: &str = unsafe { CStr::from_ptr(ptr as *const i8) }.to_str().unwrap();
Will we have non null terminated char* ? As the struct is coming from C++/llvm side, it will always be null terminated right ?

2021-05-19 12:11 UTC, ruvi-d commented on runtime/rust_rt/src/lib.rs
> +    let _string: &str = unsafe { CStr::from_ptr(ptr as *const i8) }.to_str().unwrap();
Yes.. expect to be non null terminated. Two points:
1) These struct won't always come from C++/llvm side. Run time string creation like when we do string concatenation will happen in the runtime lib (C/Rust).
2) If you check the .ll you are generating with this PR vs old .ll's; you will notice that your new char * are actually not null terminated. Because you are using std::string.length to get size, which omits the null character.

2021-05-19 12:29 UTC, shubhamnarlawar commented on runtime/rust_rt/src/lib.rs
> +    let _string: &str = unsafe { CStr::from_ptr(ptr as *const i8) }.to_str().unwrap();
Got it.
Yes. I am generating non null terminated const char*.

2021-05-19 13:24 UTC, shubhamnarlawar commented on compiler/codegen/CodeGenUtils.cpp
> +    assert(typeTag == TYPE_TAG_CHAR_STRING || typeTag == TYPE_TAG_STRING);
Removed.

2021-05-19 13:24 UTC, shubhamnarlawar commented on compiler/codegen/ConstantLoadInsnCodeGen.cpp
> +        constRef = globalStruct;
Done.

2021-05-19 13:24 UTC, shubhamnarlawar commented on runtime/rust_rt/src/lib.rs
> +    let _string: &str = unsafe { CStr::from_ptr(ptr as *const i8) }.to_str().unwrap();
Now, I am generating string from const char * and length.

2021-05-19 13:25 UTC, shubhamnarlawar commented on runtime/c_rt/test/main.cpp
> +    BalString bstring1 = {.header = 1, .n_bytes = 1, .value = "1"};
Created an issue for it.

2021-05-19 14:19 UTC, ruvi-d approved these changes

2021-05-20 06:14 UTC, KavinduZoysa approved these changes

2021-05-20 06:15 UTC, merged

2021-08-12 07:55 UTC, jclark commented on compiler/modules/front.syntax/scan.bal
> +            CP_CIRCUMFLEX => {
The common code needs to be factored out here.

2021-08-12 07:56 UTC, jclark commented on compiler/modules/front.syntax/ast.bal
> +type CompoundAssignArithmeticOp "+=" | "-=" | "/=" | "*=";
These are not needed

2021-08-12 07:57 UTC, jclark commented on compiler/modules/front.syntax/parseStmt.bal
> +    if op is CompoundAssignArithmeticOp {
You don't need if/else

2021-08-12 08:15 UTC, ushirask commented on compiler/modules/front.syntax/ast.bal
> +type CompoundAssignArithmeticOp "+=" | "-=" | "/=" | "*=";
fixed