Extend the array implementation to byte
ballerina-platform/nballerina pull request #301
Opened 2021-05-10 06:46 UTC by heshanpadmasiri

## Purpose
Extend the array implementation in #285 to support byte datatype.
Resolves #295

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
-  Implement the minimum code changes to set a variable as a byte value 
-  Change the array implementation to a generic and use that to implement both integer and byte arrays
-  Add new test cases for byte arrays based on integer arrays

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
Expand on #285

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-05-16 18:38 UTC, shubhamnarlawar commented on compiler/BIRReader.cpp
> +    assert(poolEntry->getTag() == ConstantPoolEntry::tagEnum::TAG_ENUM_CP_ENTRY_INTEGER || poolEntry->getTag() == ConstantPoolEntry::tagEnum::TAG_ENUM_CP_ENTRY_BYTE);
Apply rust-fmt or cargo-fmt.

2021-05-17 03:35 UTC, heshanpadmasiri commented on compiler/include/bir/ConstantLoad.h
> +    ~ConstantLoadInsn() = default;
Fixed

2021-05-17 03:36 UTC, heshanpadmasiri commented on test/array/function_call_array_byte.bal
> +    print_byte(test(arr1));
Added test to check 3 data points (2 with values one without a value assigned)

2021-05-17 03:36 UTC, heshanpadmasiri commented on compiler/BIRReader.cpp
> +    assert(poolEntry->getTag() == ConstantPoolEntry::tagEnum::TAG_ENUM_CP_ENTRY_INTEGER || poolEntry->getTag() == ConstantPoolEntry::tagEnum::TAG_ENUM_CP_ENTRY_BYTE);
Fixed

2021-05-17 05:50 UTC, heshanpadmasiri commented
@manuranga if we are to break the header and body allocation in to [two](https://github.com/ballerina-platform/nballerina/pull/285/files#r633208078) when the array get resized I assume we resize only the value and leave the header intact. Or should we reallocate both again as well.

2021-05-17 09:12 UTC, ruvi-d requested changes

2021-05-17 09:12 UTC, ruvi-d commented on test/byte/init_byte.bal
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" "%target_variant" "%skip_bir_gen" | filecheck %s
We need some tests to cover arithmetic operations for Byte type. Not necessary for this PR, so please create an issue to track that.

2021-05-17 09:12 UTC, ruvi-d commented on test/array/load_store_array_byte.bal
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" "%target_variant" "%skip_bir_gen" | filecheck %s
Please verify load/store with multiple values.

2021-05-17 09:12 UTC, ruvi-d commented on test/array/load_store_array_byte_global.bal
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" "%target_variant" "%skip_bir_gen" | filecheck %s
Ditto about verifying multiple values

2021-05-17 09:30 UTC, heshanpadmasiri commented on test/byte/init_byte.bal
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" "%target_variant" "%skip_bir_gen" | filecheck %s
Created new issue #313

2021-05-17 11:15 UTC, heshanpadmasiri commented on compiler/include/bir/ConstantLoad.h
>          : NonTerminatorInsn(std::move(lhs), currentBB), typeTag(TYPE_TAG_INT), value(intVal) {}
Is making the constructor private a hard requirement? Because as far as I can figure out we can't call make_unique on private constructors [ [ref](https://abseil.io/tips/134) , same issue exists in std::make_unique and I think due to same reasons]

2021-05-17 11:24 UTC, heshanpadmasiri commented on test/array/load_store_array_byte.bal
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" "%target_variant" "%skip_bir_gen" | filecheck %s
Fixed

2021-05-17 11:24 UTC, heshanpadmasiri commented on test/array/load_store_array_byte_global.bal
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" "%target_variant" "%skip_bir_gen" | filecheck %s
Fixed

2021-05-17 11:25 UTC, heshanpadmasiri commented on compiler/include/reader/ConstantPool.h
> +    int64_t getByteCp(int32_t index);
Changed to `in32_t` because bir file uses 4 bytes to represent the byte value

2021-05-17 11:26 UTC, heshanpadmasiri commented on compiler/include/bir/ConstantLoad.h
>          : NonTerminatorInsn(std::move(lhs), currentBB), typeTag(TYPE_TAG_INT), value(intVal) {}
Temporarily added buildermethods to take the same arguments as the constructors while keeping constructors public

2021-05-17 11:46 UTC, ruvi-d commented on compiler/include/bir/ConstantLoad.h
>          : NonTerminatorInsn(std::move(lhs), currentBB), typeTag(TYPE_TAG_INT), value(intVal) {}
You can make the constructors private and use `std::unique_ptr(new ConstantLoad(..))` type patter instead of `std::make_unique` right?

2021-05-17 12:25 UTC, ruvi-d requested changes
Please resolve merge conflicts with master and this comment https://github.com/ballerina-platform/nballerina/pull/301#discussion_r633460413

2021-05-18 04:29 UTC, heshanpadmasiri commented on compiler/include/bir/ConstantLoad.h
>          : NonTerminatorInsn(std::move(lhs), currentBB), typeTag(TYPE_TAG_INT), value(intVal) {}
Fixed

2021-05-18 04:47 UTC, heshanpadmasiri commented
> Please resolve merge conflicts with master and this comment [#301 (comment)](https://github.com/ballerina-platform/nballerina/pull/301#discussion_r633460413)

Fixed

2021-05-18 04:55 UTC, ruvi-d requested changes

2021-05-18 04:55 UTC, ruvi-d commented on compiler/reader/ConstantPool.cpp
> +    return byteCp->getValue();
Even though BIR is using 4 bytes to represent a Bal Byte value, since we are truncating it to `int8_t` shall we do the narrow casting (with checks) here and return a `int8_t` from `getByteCp`?

2021-05-18 04:55 UTC, ruvi-d commented on test/array/load_store_array_byte.bal
> +// CHECK: RESULT=0
Missing EoF

2021-05-18 05:46 UTC, manuranga commented on compiler/reader/ConstantPool.cpp
> +    return byteCp->getValue();
+1, lets also assert that it's in correct range.

2021-05-18 06:31 UTC, heshanpadmasiri commented on test/array/load_store_array_byte.bal
> +// CHECK: RESULT=0
Fixed

2021-05-18 06:31 UTC, heshanpadmasiri commented on compiler/reader/ConstantPool.cpp
> +    return byteCp->getValue();
Fixed

2021-05-18 06:35 UTC, ruvi-d approved these changes

2021-05-20 06:12 UTC, KavinduZoysa approved these changes

2021-05-20 06:13 UTC, merged