Int to any and any to int balvalue representation
ballerina-platform/nballerina pull request #308
Opened 2021-05-15 08:51 UTC by ramakotareddy

## Purpose
Remove fat-pointer (smtPtr) usage when compiling int to any casting and use BalValue.

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

Resolves #252 
Resolves #293 
Resolves #292

2021-05-15 08:54 UTC, ramakotareddy commented
@manuranga  and @ruvi-d Implemented only int_to_any and any_to_int typecast and other typecast tests are failing. what can i do for this problem ?

2021-05-16 03:17 UTC, ruvi-d commented
> @manuranga and @ruvi-d Implemented only int_to_any and any_to_int typecast and other typecast tests are failing. what can i do for this problem ?

Let's disable them. We will have to add them back as we make progress.

2021-05-17 04:05 UTC, ruvi-d requested changes
Partial review comments.

2021-05-17 04:08 UTC, ruvi-d commented
@ramakotareddy I have a serious concern with how the codegen has been implemented in the `IntToAny` and `AnyToInt` functions. Please see https://github.com/ballerina-platform/nballerina/pull/308#discussion_r633204546

2021-05-17 04:12 UTC, ramakotareddy commented on compiler/include/codegen/PackageCodeGen.h
> +    llvm::Function *getIntToAnyCast(llvm::Module &module, llvm::IRBuilder<> &builder);
@ruvi-d , i can move this function to CodeGenUtils and i will change the function name.

2021-05-17 04:12 UTC, ramakotareddy commented on compiler/include/codegen/NonTerminatorInsnCodeGen.h
> +    llvm::Function *getAnyToIntCast(llvm::Module &module, llvm::IRBuilder<> &builder);
@ruvi-d , i can move this function to CodeGenUtils and i will change the function name.

2021-05-17 08:38 UTC, ruvi-d requested changes
Please create tasks for the disabled functionality (unions, optional, etc)

2021-05-17 08:38 UTC, ruvi-d commented on compiler/codegen/TypeCastInsnCodeGen.cpp
>      if (Type::isSmartStructType(rhsTypeTag)) {
`Type::isSmartStructType()` is no longer valid

2021-05-17 08:38 UTC, ruvi-d commented on compiler/codegen/TypeCastInsnCodeGen.cpp
> +        paramValues.push_back(rhsValueRef);
Ditto about passing `CreateLoad` value directly to `CreateCall`

2021-05-17 08:38 UTC, ruvi-d commented on compiler/codegen/TypeCastInsnCodeGen.cpp
> +        auto *namedFuncRef = module.getFunction("any_to_int");
need to check LHS type and pick "any_to_int" if only Int. Use llvm_unreachable to abort if otherwise.

2021-05-17 08:38 UTC, ruvi-d commented on compiler/codegen/TypeCastInsnCodeGen.cpp
>          moduleGenerator.storeValueInSmartStruct(builder, rhsOpRef, rhsType, lhsOpRef);
Need to check types here and only call IntToAny if types match. llvm_unreable if otherwise.

2021-05-17 08:38 UTC, ruvi-d commented on compiler/codegen/TypeCastInsnCodeGen.cpp
> +    paramTypes.push_back(builder.getInt8PtrTy());
Ditto about about using ArrayRef

2021-05-17 08:38 UTC, ruvi-d commented on compiler/codegen/TypeCastInsnCodeGen.cpp
> +    auto *abortFuncCallInsn = builder.CreateCall(abortFunc);
Missing Unreachable instruction and associated attributes for abort call
```
abortFuncCallInsn->addAttribute(~0U, llvm::Attribute::NoReturn);
abortFuncCallInsn->addAttribute(~0U, llvm::Attribute::NoUnwind);
builder.CreateUnreachable();
```

2021-05-18 06:52 UTC, ramakotareddy commented on compiler/codegen/PackageCodeGen.cpp
> +void PackageCodeGen::storeValueInSmartStruct(llvm::IRBuilder<> &builder, llvm::Value *value,
Fixed

2021-05-18 06:52 UTC, ramakotareddy commented on compiler/codegen/PackageCodeGen.cpp
> +    paramValues.push_back(inputValueRef);
Fixed

2021-05-18 06:53 UTC, ramakotareddy commented on compiler/include/codegen/PackageCodeGen.h
> +    llvm::Function *getIntToAnyCast(llvm::Module &module, llvm::IRBuilder<> &builder);
Moved int_to_any function to CodeGenUtils and changed the function name

2021-05-18 06:53 UTC, ramakotareddy commented on compiler/include/codegen/NonTerminatorInsnCodeGen.h
> +    llvm::Function *getAnyToIntCast(llvm::Module &module, llvm::IRBuilder<> &builder);
Fixed

2021-05-18 06:53 UTC, ramakotareddy commented on compiler/codegen/PackageCodeGen.cpp
> +    const std::string functionName = "int_to_any";
Fixed

2021-05-18 06:53 UTC, ramakotareddy commented on compiler/codegen/PackageCodeGen.cpp
> +    paramTypes.push_back(builder.getInt64Ty());
Fixed

2021-05-18 06:54 UTC, ramakotareddy commented on compiler/codegen/PackageCodeGen.cpp
> +    llvm::BasicBlock *entryBB = llvm::BasicBlock::Create(module.getContext(), "entry");
Fixed

2021-05-18 06:55 UTC, ramakotareddy commented on compiler/codegen/PackageCodeGen.cpp
> +    entryBB->getInstList().push_back(localVarRef4);
Now i am using builder.SetInsertPoint(entryBB); instead of creating and removing instructions.

2021-05-18 06:55 UTC, ramakotareddy commented on compiler/codegen/PackageCodeGen.cpp
> +    llvm::StoreInst *storeInputIntValue = builder.CreateStore(funcArg, localVarRef2);
Fixed

2021-05-18 06:55 UTC, ramakotareddy commented on compiler/codegen/PackageCodeGen.cpp
> +    auto *constIntValue = llvm::ConstantInt::get(builder.getInt64Ty(), 4611686018427387903);
Fixed

2021-05-18 06:55 UTC, ramakotareddy commented on compiler/codegen/PackageCodeGen.cpp
> +    const std::string ifElseBBName = "if.else";
Fixed

2021-05-18 06:55 UTC, ramakotareddy commented on compiler/codegen/PackageCodeGen.cpp
> +    const std::string ifBBName = "if.then";
Fixed

2021-05-18 06:55 UTC, ramakotareddy commented on compiler/codegen/PackageCodeGen.cpp
> +    const std::string returnBBName = "return";
Fixed

2021-05-18 06:55 UTC, ramakotareddy commented on compiler/codegen/PackageCodeGen.cpp
> +    auto *constByteValue = llvm::ConstantInt::get(builder.getInt64Ty(), 1);
Fixed

2021-05-18 06:56 UTC, ramakotareddy commented on compiler/codegen/PackageCodeGen.cpp
> +    llvm::BinaryOperator *elseAddInsn = llvm::BinaryOperator::CreateAdd(balValSize, constByteValue, "");
Fixed

2021-05-18 06:56 UTC, ramakotareddy commented on compiler/codegen/TypeCastInsnCodeGen.cpp
>      if (Type::isSmartStructType(rhsTypeTag)) {
updated the function name to isBalValueType().

2021-05-18 06:56 UTC, ramakotareddy commented on compiler/codegen/TypeCastInsnCodeGen.cpp
> +        paramValues.push_back(rhsValueRef);
Fixed

2021-05-18 06:57 UTC, ramakotareddy commented on compiler/codegen/TypeCastInsnCodeGen.cpp
> +        auto *namedFuncRef = module.getFunction("any_to_int");
Added checks

2021-05-18 06:57 UTC, ramakotareddy commented on compiler/codegen/TypeCastInsnCodeGen.cpp
>          moduleGenerator.storeValueInSmartStruct(builder, rhsOpRef, rhsType, lhsOpRef);
Fixed

2021-05-18 06:57 UTC, ramakotareddy commented on compiler/codegen/TypeCastInsnCodeGen.cpp
> +    paramTypes.push_back(builder.getInt8PtrTy());
Fixed

2021-05-18 06:57 UTC, ramakotareddy commented on compiler/codegen/TypeCastInsnCodeGen.cpp
> +    auto *abortFuncCallInsn = builder.CreateCall(abortFunc);
Fixed

2021-05-18 08:40 UTC, ruvi-d requested changes

2021-05-18 08:40 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +
Without passing `builder` and `currBB`.. You can create a new build from module and further simplify the function interface.
Just call `auto builder = llvm::IRBuilder<>(module.getContext());` inside the function to create a new builder.

Ditto for `createAnyToIntFunction`

2021-05-18 08:40 UTC, ruvi-d commented on compiler/include/codegen/CodeGenUtils.h
> +                                                  llvm::BasicBlock *currBB);
Suggest that the these functions be named `getIntToAnyFunction` and `getAnyToIntFunc` inline with the other function names in this class. If you wish you can make `createIntToAnyFunction` a private or free function and have `getIntToAnyFunction` call it to do the codegen if `module.getFunction(functionName);` returns null

2021-05-18 08:40 UTC, ruvi-d commented on compiler/codegen/TypeCastInsnCodeGen.cpp
> +            llvm_unreachable("Invalid type");
Should be "unsupported type"

2021-05-18 08:40 UTC, ruvi-d commented on compiler/codegen/PackageCodeGen.cpp
> +    // call the created int_to_any function
check whether `valueType` is Int and llvm_unreachable if otherwise

2021-05-18 08:40 UTC, ruvi-d commented on compiler/codegen/PackageCodeGen.cpp
> +                                    [[maybe_unused]] const Type &valueType, llvm::Value *balValue) {
Since this function is supposed to "create" a bal value, I'd suggest to remove the last store instruction to `balValue` and return `callResult` to the function callee.

2021-05-18 08:40 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +    auto *localVarRef4 = builder.CreateAlloca(llvm::Type::getInt64PtrTy(module.getContext()), nullptr, "");
nullptr and "" can be omitted from the function call as they are the default values

2021-05-18 08:40 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +    auto *localVarRef4 = builder.CreateAlloca(llvm::Type::getInt64PtrTy(module.getContext()), nullptr, "");
Please check other uses of "" too

2021-05-18 10:51 UTC, ramakotareddy commented on compiler/codegen/CodeGenUtils.cpp
> +    auto *localVarRef4 = builder.CreateAlloca(llvm::Type::getInt64PtrTy(module.getContext()), nullptr, "");
Fixed. "" is to create alloca with particular name.

2021-05-18 10:51 UTC, ramakotareddy commented on compiler/codegen/PackageCodeGen.cpp
> +                                    [[maybe_unused]] const Type &valueType, llvm::Value *balValue) {
Fixed

2021-05-18 10:52 UTC, ramakotareddy commented on compiler/codegen/PackageCodeGen.cpp
> +    // call the created int_to_any function
Fixed

2021-05-18 10:52 UTC, ramakotareddy commented on compiler/codegen/TypeCastInsnCodeGen.cpp
> +            llvm_unreachable("Invalid type");
Fixed

2021-05-18 10:52 UTC, ramakotareddy commented on compiler/include/codegen/CodeGenUtils.h
> +                                                  llvm::BasicBlock *currBB);
Fixed

2021-05-18 10:52 UTC, ramakotareddy commented on compiler/codegen/CodeGenUtils.cpp
> +
Fixed

2021-05-18 10:52 UTC, ramakotareddy commented on compiler/include/codegen/PackageCodeGen.h
> +    void createBalValue(llvm::IRBuilder<> &builder, llvm::Value *value, const Type &valueType, llvm::Value *balValue);
Moved to CodeGenUtils

2021-05-18 11:54 UTC, ruvi-d requested changes

2021-05-18 11:54 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +        auto *inputValueRef = llvm::dyn_cast<llvm::Instruction>(builder.CreateLoad(value, ""));
is `llvm::dyn_cast<llvm::Instruction>()` required?

2021-05-18 11:54 UTC, ruvi-d commented on compiler/codegen/MapInsnsCodeGen.cpp
> +    CodeGenUtils::createBalValue(moduleGenerator.getModule(), builder, outParam, Type(memTypeTag, ""));
need to store the value returned to lhs

2021-05-18 11:54 UTC, ruvi-d commented on compiler/include/codegen/CodeGenUtils.h
> +                                                  llvm::BasicBlock *currBB);
Unused function definitions

2021-05-18 11:54 UTC, ruvi-d commented on compiler/include/codegen/CodeGenUtils.h
> +    static llvm::Function *getIntToAnyFunction(llvm::Module &module);
This too can be private

2021-05-18 12:25 UTC, ramakotareddy commented on compiler/include/codegen/CodeGenUtils.h
> +    static llvm::Function *getIntToAnyFunction(llvm::Module &module);
Fixed

2021-05-18 12:26 UTC, ramakotareddy commented on compiler/include/codegen/CodeGenUtils.h
> +                                                  llvm::BasicBlock *currBB);
Removed unused function definitions

2021-05-18 12:26 UTC, ramakotareddy commented on compiler/codegen/MapInsnsCodeGen.cpp
> +    CodeGenUtils::createBalValue(moduleGenerator.getModule(), builder, outParam, Type(memTypeTag, ""));
Fixed

2021-05-18 12:26 UTC, ramakotareddy commented on compiler/codegen/CodeGenUtils.cpp
> +        auto *inputValueRef = llvm::dyn_cast<llvm::Instruction>(builder.CreateLoad(value, ""));
Not required, removed.

2021-05-18 12:48 UTC, ruvi-d approved these changes

2021-05-19 09:57 UTC, KavinduZoysa commented
@ramakotareddy, do we have an issue tracking the disabled tests?

2021-05-19 10:03 UTC, ramakotareddy commented
Yes Kavindu I have created an issue #314

2021-05-19 10:09 UTC, KavinduZoysa approved these changes

2021-05-19 10:09 UTC, ruvi-d commented
> Yes Kavindu I have created an issue #314

@ramakotareddy : I don't think that is enough and I've commented in that issue. We need granular issues (for each feature that was disabled), so that people can take them up piece by piece.

2021-05-19 10:10 UTC, merged

2021-05-19 10:35 UTC, ramakotareddy commented
@ruvi-d , i forgot to create separate  issues, i will create separate issues for each feature.