Add support for String Typecast
ballerina-platform/nballerina pull request #41
Opened 2021-01-11 18:32 UTC by shubhamnarlawar

Following are the patches in this PR - 

-> Add support for string, float and boolean data type

-> Add support for String Typecast.

2021-01-11 23:36 UTC, ramakotareddy commented
Added support for string, boolean, float in Translation side.
Added support for int, float, boolean and string Typecast from Any.
Added test cases to test new functionality.

2021-01-12 04:28 UTC, shubhamnarlawar commented
Please review and suggest changes on this PR.

2021-01-12 17:30 UTC, shubhamnarlawar commented
PING.

2021-01-13 10:46 UTC, dulvinw commented on BIR2llvmIR/BIR.h
> +  void setFloatValue(float floatVal, TypeTagEnum TypeTag) {
Can't we infer the typetag based on the value? For example for `int` value we can infer the `TYPE_TAG_INT`?

2021-01-13 10:52 UTC, dulvinw commented on BIR2llvmIR/llvmFunctionGen.cpp
> +const char *BIRFunction::getTypeNameOfTypeTag(TypeTagEnum typeTag) {
Shouldnt we support all the subtypes of Int here?

2021-01-13 14:14 UTC, shubhamnarlawar commented on BIR2llvmIR/llvmFunctionGen.cpp
> +const char *BIRFunction::getTypeNameOfTypeTag(TypeTagEnum typeTag) {
Does it mean Decimal and Byte data type along with int subtypes

TYPE_TAG_INT:
 TYPE_TAG_UNSIGNED8_INT:
TYPE_TAG_UNSIGNED16_INT:
TYPE_TAG_UNSIGNED32_INT:
  TYPE_TAG_SIGNED8_INT:
  TYPE_TAG_SIGNED16_INT:
  TYPE_TAG_SIGNED32_INT:
  TYPE_TAG_DECIMAL:
  TYPE_TAG_BYTE

2021-01-13 18:16 UTC, shubhamnarlawar commented on BIR2llvmIR/llvmFunctionGen.cpp
> +const char *BIRFunction::getTypeNameOfTypeTag(TypeTagEnum typeTag) {
@ramakotareddy - Will there be a major change in translation side for supporting sub types of int?

2021-01-14 00:49 UTC, ramakotareddy commented on BIR2llvmIR/llvmFunctionGen.cpp
> +const char *BIRFunction::getTypeNameOfTypeTag(TypeTagEnum typeTag) {
I will add int subtypes if it is minor change else will add it in next task.

2021-01-14 05:04 UTC, shubhamnarlawar commented
@dulvinw - Any more suggestions on this PR apart from support for sub types of int?

2021-01-18 11:48 UTC, dulvinw commented on BIR2llvmIR/BIR.h
> +  void setBoolValue(bool boolVal, TypeTagEnum TypeTag) {
I thought they are keeping it for the conformity. Other than for int, i believe rest of the tags are self explanatory

2021-01-18 11:57 UTC, shubhamnarlawar commented on BIR2llvmIR/BIR.h
> +  void setBoolValue(bool boolVal, TypeTagEnum TypeTag) {
Yes. We are keeping it for conformity.

2021-01-18 12:28 UTC, shubhamnarlawar commented on BIR2llvmIR/llvmConstantLoadInsn.cpp
> +      LLVMValueRef *paramTypes = new LLVMValueRef[3];
Sure. How about below comment? - 

/*
1. At first, string constant is created using string value and string length
2. Using string constant, a Global Variable is created.
3. Using in bound get element pointer, Global Variable is loaded into a local variable
*/

2021-01-19 05:16 UTC, manuranga commented on BIR2llvmIR/BIRReader.cpp
> +// Search string from the constant pool based on index
```suggestion
// Search float from the constant pool based on index
```

2021-01-19 05:16 UTC, manuranga commented on BIR2llvmIR/BIRReader.cpp
> +// Search string from the constant pool based on index
```suggestion
// Search boolean from the constant pool based on index
```

2021-01-19 05:31 UTC, manuranga commented on BIR2llvmIR/BIR.h
> +  void setBoolValue(bool boolVal, TypeTagEnum TypeTag) {
I also agree with Waruna, can't we have this with only one argument ? since we know the typeTag
(btw shouldn't TypeTag has to be typeTag ?)

2021-01-19 05:32 UTC, dulvinw commented on BIR2llvmIR/llvmConstantLoadInsn.cpp
> +          new GlobalVariable(*unwrap(modRef), C->getType(), false,
Just for my knowledge, why do we need a global variable to hold the `string` value?

2021-01-19 08:50 UTC, shubhamnarlawar commented on BIR2llvmIR/BIR.h
> +  void setBoolValue(bool boolVal, TypeTagEnum TypeTag) {
The process we are following is - 

Why not set the typetag directly from the BIR instead of setting it based in assumption? Using this, we can conform BIR in every function. In future, if we want to put assert messages on the received typeTag - 

`assert(typeTag != tagEnum::TAG_ENUM_CP_ENTRY_SHAPE);`

WDYT on this? I can keep only one argument also.

(The local variable is typeTag hence the parameter is named as TypeTag for readibility purpose)

  `void setBoolValue(bool boolVal, TypeTagEnum TypeTag) {`
    `val.boolValue = boolVal;`
   ` typeTag = TypeTag;`
  `}`

2021-01-19 08:52 UTC, shubhamnarlawar commented on BIR2llvmIR/llvmConstantLoadInsn.cpp
> +          new GlobalVariable(*unwrap(modRef), C->getType(), false,
@ramakotareddy - Can you give comment on this?

2021-01-19 17:12 UTC, ayonam commented
That is because all string literals need to go
        into the ".rodata" section and that will happen only if we
        declare it as a GlobalVariable.  If we declare it as a local
        variable, then its initialization needs to be done character by
        character in the generated assembly code, which will add to its
        runtime.
    
        
      
      
    
    On 19/01/21 11:03, Dulvin Witharane
      wrote:
    
    
      
      @dulvinw commented on this pull request.
      
      In BIR2llvmIR/llvmConstantLoadInsn.cpp:
      >        break;
     }
+    case TYPE_TAG_STRING:
+    case TYPE_TAG_CHAR_STRING: {
+      LLVMValueRef *paramTypes = new LLVMValueRef[3];
+      string stringValue = val.strValue->data();
+      Constant *C = llvm::ConstantDataArray::getString(
+          *unwrap(LLVMGetGlobalContext()),
+          StringRef(stringValue.c_str(), stringValue.length()));
+      GlobalVariable *GV =
+          new GlobalVariable(*unwrap(modRef), C->getType(), false,

      Just for my knowledge, why do we need a global variable to hold
        the string value?
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ballerina-platform/nballerina/pull/41#pullrequestreview-570917197",
"url": "https://github.com/ballerina-platform/nballerina/pull/41#pullrequestreview-570917197",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

2021-01-20 17:49 UTC, shubhamnarlawar commented
Are there any further suggestions or changes need to be done on this PR? If not, can you please merge it?

2021-01-25 10:54 UTC, warunalakshitha commented on BIR2llvmIR/BIR.h
> +  void setBoolValue(bool boolVal, TypeTagEnum TypeTag) {
+1 to keep the typeTag so we can add any validation if required for typetag later.

2021-01-27 08:14 UTC, shubhamnarlawar commented
PING.

Is anything blocking for this PR to get merge in the master? I think this PR is good to go!

2021-01-27 08:51 UTC, ruvi-d reviewed
> PING.
> 
> Is anything blocking for this PR to get merge in the master? I think this PR is good to go!

Sorry my bad. I wrote some review comments yesterday, but haven't submitted them. Let me submit them now.

2021-01-27 11:09 UTC, shubhamnarlawar commented
We have pushed the code for Array Translation in this PR as a seperate commit.

2021-01-27 12:21 UTC, ruvi-d commented
> We have pushed the code for Array Translation in this PR as a seperate commit.
> 
> Added reading and translation support for new array, store array and load array instructions.

Can you update the Readme with instructions to compile the runtime?

2021-01-29 15:54 UTC, dulvinw commented on BIR2llvmIR/BIRReader.cpp
> +    strVal[0] = readerRef.constantPool->getStringCp(valueCpIndex);
+1 to use RAII.

2021-02-02 04:57 UTC, ramakotareddy commented on BIR2llvmIR/BIRReader.cpp
> +    constantloadInsn->setBoolValue(valueCpIndex, typeTag);
Fixed.

2021-02-02 10:16 UTC, ruvi-d approved these changes

2021-02-02 10:19 UTC, dulvinw approved these changes

2021-02-02 10:22 UTC, ruvi-d requested changes
A few comments left by me are still open

2021-02-02 12:46 UTC, shubhamnarlawar commented
> A few comments left by me are still open

Pushing the remaining suggested changes.

2021-02-02 12:46 UTC, shubhamnarlawar commented
> > We have pushed the code for Array Translation in this PR as a seperate commit.
> > Added reading and translation support for new array, store array and load array instructions.
> 
> Can you update the Readme with instructions to compile the runtime?

Sure. I will update Readme with other changes.

2021-02-02 13:38 UTC, shubhamnarlawar commented
> > We have pushed the code for Array Translation in this PR as a seperate commit.
> > Added reading and translation support for new array, store array and load array instructions.
> 
> Can you update the Readme with instructions to compile the runtime?

As we have updated the Makefile, a simple `make` would build the runtime also.

2021-02-02 17:55 UTC, shubhamnarlawar commented
Issue #56 and #57 has been created from the suggestions of this PR.

@ruvi-d - We will send remaining changes of the PR.

This PR has become very big. Is it fine if we send separate PR addressing issues #56 and #57 later?

WDYT?

2021-02-03 04:43 UTC, ruvi-d commented
> Issue #56 and #57 has been created from the suggestions of this PR.
> 
> @ruvi-d - We will send remaining changes of the PR.
> 
> This PR has become very big. Is it fine if we send separate PR addressing issues #56 and #57 later?
> 
> WDYT?

Makes sense @shubhamnarlawar. Let me review the commits so far and try to pass this PR through with new issues to track any requested changes that maybe required.

2021-02-03 05:38 UTC, ruvi-d approved these changes
Good to merge PR

2021-02-03 05:41 UTC, merged