Implement nil type descriptor
ballerina-platform/nballerina pull request #532
Opened 2021-10-06 19:30 UTC by manuranga

Fixes #133
Part of #412

2021-10-07 01:54 UTC, jclark requested changes

2021-10-07 01:54 UTC, jclark commented on compiler/modules/front.syntax/preparseStmt.bal
> +const TD = true;
These are globally scoped, so need to be a bit longer e.g. PREPARSE_TYPE_DESC PREPARSE_EXPR

2021-10-07 01:54 UTC, jclark commented on compiler/modules/front.syntax/parseStmt.bal
> +            boolean isTd = check preparseParenTypeDesc(tok);
I prefer isTypeDesc to isTd here.

2021-10-07 01:54 UTC, jclark commented on compiler/modules/front.syntax/preparseStmt.bal
> +function preparseParenTypeDesc(Tokenizer tok) returns boolean|err:Syntax {
This needs a comment to explain what's going on.

2021-10-07 01:54 UTC, jclark commented on compiler/modules/front.syntax/preparseStmt.bal
> +    if t == "." {
This is better done as a `match` statement.

2021-10-07 01:54 UTC, jclark commented on compiler/modules/front.syntax/preparseStmt.bal
> +        check tok.advance();
SUBSET this can also be the start of a binding pattern (semantically invalid)

2021-10-07 01:54 UTC, jclark commented on compiler/modules/front.syntax/preparseStmt.bal
> +    return tok.err("invalid statement");
I would be inclined to return EXPR here and leave it to the regular statement parsing return an error. Then you can leave out `else { return EXPR; }` above.  So the function's contract is to return true if it maybe a valid type descriptor, false otherwise, and returns an error if it cannot get sufficient tokens to decide.

2021-10-07 01:54 UTC, jclark commented on compiler/modules/front.syntax/preparseStmt.bal
> +function preparseParenTypeDesc(Tokenizer tok) returns boolean|err:Syntax {
Returns true if a statement whose first token was `(` begins a type descriptor rather than an expression (implying that the statement is a local variable declaration rather than a method call). This is a preparse: the statement will be parsed again according to the value returned. For now, this only handles a statement starting with `()`. It will be expanded later.

2021-10-08 04:14 UTC, jclark reviewed
Please change to something else in #412.

2021-10-08 04:14 UTC, jclark commented on compiler/modules/front.syntax/preparseStmt.bal
> +const PREDICT_TYPE_DESC = true;
The name PREDICT_x is just not right. It doesn't fit with preparse. We are saying it can only be a expression or type descriptor, although it may not be a valid one: and that's not really what prediction means.

2021-10-08 04:15 UTC, merged

2021-10-08 04:36 UTC, manuranga commented on compiler/modules/front.syntax/preparseStmt.bal
> +const PREDICT_TYPE_DESC = true;
I'll replace with PREPARSE_x in next pr.

2021-10-08 04:48 UTC, manuranga commented on compiler/modules/front.syntax/preparseStmt.bal
> +const PREDICT_TYPE_DESC = true;
(I don't get your objection though. Does predict gives the idea that it can be the other way some times?)
Other options : signal, cue

2021-10-08 07:53 UTC, jclark commented on compiler/modules/front.syntax/preparseStmt.bal
> +const PREDICT_TYPE_DESC = true;
predict is saying something about the future and implies uncertainty. Here we are not guessing how we are going to parse it, we are saying with certainty how it must be parsed.