Add projection semtype testing
ballerina-platform/nballerina pull request #534
Opened 2021-10-07 04:01 UTC by ushirask

## Purpose
> Partially fixes #499 

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-10-07 09:36 UTC, manuranga commented on compiler/modules/front.syntax/parseTypeTest.bal
> +        check tok.advance();
`tok.expect("]")`

2021-10-07 09:38 UTC, manuranga commented on compiler/modules/front.syntax/parseTypeTest.bal
> +        string index = check tok.expectIdentifier();
I am not sure if you were planing to do this as separate PR, but we want this to be either Identifier or an int literal.(we'll have to add string literal as well, but we can do that later)

2021-10-07 09:46 UTC, ushirask commented on compiler/modules/front.syntax/parseTypeTest.bal
> +        string index = check tok.expectIdentifier();
I'll be adding that in the same PR

2021-10-08 07:39 UTC, jclark requested changes

2021-10-08 07:39 UTC, jclark commented on compiler/testSuite/01-boolean/boolean-t.bal
> +// @type BL[ONE] = B
It's better to put the `@type` lines just before the types they use (like we do with `@output` lines)

2021-10-08 07:39 UTC, jclark commented on compiler/modules/front/front.bal
> +        if v is s:ConstDefn && v.expr is s:ConstValueExpr && (<s:ConstValueExpr> v.expr).value is string {
Too many casts. Split off some helper functions and introduce some temporary variables.

2021-10-08 07:39 UTC, jclark commented on compiler/tests/testSuite.bal
> +            t:SemType t2 = m.entries().get(test.member)[1];
Introduce temp variables to avoid all these casts.

2021-10-08 07:39 UTC, jclark commented on compiler/tests/testSuite.bal
> +        t:SemType t1 = m.entries().get(test.left)[1];
I'm not sure what you're doing here, but you shouldn't be repeatedly calling m.entries().

2021-10-08 08:07 UTC, ushirask commented on compiler/tests/testSuite.bal
> +        t:SemType t1 = m.entries().get(test.left)[1];
each item in `expected` is a single `@test` and I'm getting the semtypes of the types in that test from the semtype map, can this be avoided?

2021-10-08 08:12 UTC, ushirask commented on compiler/tests/testSuite.bal
> +        t:SemType t1 = m.entries().get(test.left)[1];
or do you mean that `m.entries()` should be kept outside the loop with just calling the `get` repeatedly

2021-10-08 08:23 UTC, manuranga commented on compiler/tests/testSuite.bal
> +        t:SemType t1 = m.entries().get(test.left)[1];
No, the qustion is why there is `entries` at all. Isn't `m.entries().get(test.left)[1];` same as `m.get(test.left)` ?

2021-10-08 08:38 UTC, jclark commented on compiler/tests/testSuite.bal
> +        t:SemType t1 = m.entries().get(test.left)[1];
The normal way to use a map is `m[k]`: that gives you a nil if the map doesn't contain an entry for k. If you somehow know for sure that it does, then you can use `m.get(k)`.  The normal use case for entries is something like

```
foreach var [k, v] in m.entries() {
   // do something with the key and value
}
```

2021-10-11 04:28 UTC, manuranga commented on compiler/testSuite/01-boolean/boolean-t.bal
> +// @type T < TF
When ever possible, try to have the types referred in an assertion before the assertion.

2021-10-11 04:30 UTC, manuranga commented on compiler/tests/testSuite.bal
> +                    t:SemType key = m.get(index);
Don't lookup twice, `t:SemType? key = m[index];` then check if it's nil.

2021-10-11 05:02 UTC, manuranga commented on compiler/tests/testSuite.bal
> +                    t:SemType key = <t:SemType> keyn;
We'll not need the cast from jBallerina beta 4, but until then lest write this in a `else` case to avoid the cast.

2021-10-11 05:08 UTC, ushirask commented on compiler/tests/testSuite.bal
> +                    t:SemType key = <t:SemType> keyn;
should this be done only for this `key` semtype since for other types where a large portion of the code will have to be moved into an else block

2021-10-11 05:11 UTC, manuranga commented on compiler/tests/testSuite.bal
> +                    t:SemType key = <t:SemType> keyn;
It'll have to be the whole thing, I agree it's getting too indented, can we move to a function, and maybe even reused it for below section?

(btw please don't use `null` use `()`)

2021-10-11 07:32 UTC, manuranga commented on compiler/modules/front.syntax/parseTypeTest.bal
> +    check tok.expect("[");
Don't use expect here, this should be an `else` case of the above `if`.
Otherwise then someone writes a wrong assertion (eg `T > S`) it will say `[ expected found >`, which is wrong.

2021-10-11 07:33 UTC, manuranga commented on compiler/modules/front.syntax/parseTypeTest.bal
> +    string? index = ();
Make this `string? index;` and move `index = ();` to `if`.
General idea is to minimize the amount of mutable local variables.

2021-10-11 07:43 UTC, manuranga commented on compiler/modules/front.syntax/parseTypeTest.bal
> +public function parseTypeTest(string str) returns TypeTest|error {
This has to be broken up to two functions.
We need to support `T[1] < S` as well, so do the parsing of `T[1]` and `S` in one, and call it form here.
```
type-expr := identifier ("[" number "]")?
type-assertion := type-expr ("<"|"="|"<>") type-expr 
```

2021-10-12 06:11 UTC, manuranga commented on compiler/modules/front.syntax/parseTypeTest.bal
> +function parseTypeExpr(Tokenizer tok) returns Operand|error {
let's call this `parseTypeProjection`

2021-10-12 06:15 UTC, ushirask commented on compiler/modules/front.syntax/parseTypeTest.bal
> +function parseTypeExpr(Tokenizer tok) returns Operand|error {
would that be appropriate since this handles the parsing of both projection and non types?

2021-10-12 06:31 UTC, manuranga commented on compiler/modules/front.syntax/parseTypeTest.bal
> +function parseTypeExpr(Tokenizer tok) returns Operand|error {
I think so, since we defining a min grammar where this is parsing a rule like `type-projection := identifier ("[" ( number | identifier ) "]")?`.

2021-10-12 06:45 UTC, manuranga commented on compiler/modules/front/front.bal
> +}
is this used ?

2021-10-12 06:49 UTC, ushirask commented on compiler/modules/front/front.bal
> +}
it's used for getting key value for `mappingMemberType` called in testSuite

2021-10-12 06:58 UTC, manuranga commented on compiler/modules/front.syntax/parseTypeTest.bal
> +};
```suggestion
public type SubtypeTest record {
    SubtypeTestOp op;
    string|TypeProjection left;
    string|TypeProjection right;
};
```
`parseTypeProjection` should return `string|TypeProjection`.
You will also have to change other types and testing code accordingly.

2021-10-12 08:43 UTC, manuranga commented on compiler/modules/front.syntax/parseTypeTest.bal
> +public type TypeTest record {
Try to arrange files such that,  things are defined before they are referred. So have these at the top of the file.

2021-10-12 08:48 UTC, ushirask commented on compiler/modules/front.syntax/parseTypeTest.bal
> +public type TypeTest record {
fixed

2021-10-12 08:51 UTC, manuranga commented on compiler/modules/front.syntax/parseTypeTest.bal
> +    int|string index;
Should be moved inside `if`, just before the second `if`.

2021-10-12 08:53 UTC, manuranga commented on compiler/tests/testSuite.bal
> +        t:SemType t2 = resolveTestSemtype(tc, m, test.right);
I slightly prefer to call these two, `left` and `right`.

2021-10-12 09:13 UTC, manuranga commented on compiler/tests/testSuite.bal
> +    return error("cannot resolve semtype");
Isn't this line unreachable ? lets change the message to say, `"unreachable"`.
I think this can be fixed from jBallerina side. Please add JBUG comment referring to https://github.com/ballerina-platform/ballerina-lang/issues/31642

2021-10-12 09:15 UTC, manuranga commented on compiler/modules/front.syntax/tests/testParserOnTestSuite.bal
> +                continue;
Does it fail for `t` cases ? I wonder why? perhaps we should fix.

2021-10-12 09:36 UTC, ushirask commented on compiler/modules/front.syntax/tests/testParserOnTestSuite.bal
> +                continue;
it fails with 
`something impossible happened (typedesc not implemented in typeDescToWords: '{"value":true}')`

2021-10-12 09:40 UTC, ushirask commented on compiler/modules/front.syntax/tests/testParserOnTestSuite.bal
> +                continue;
I'll try adding needed TypeDesc handing to typeDescToWords

2021-10-12 09:41 UTC, manuranga commented on compiler/tests/testSuite.bal
> +    return error("unreachable");
Sorry I should have said, `panic error("unreachable");`.
(BTW how does this even compile ? return type  is mismatched)

2021-10-12 09:43 UTC, manuranga commented on compiler/modules/front.syntax/tests/testParserOnTestSuite.bal
> +                continue;
hmm, unless it's a very small change let's do it in a separate PR, create an issue, and add comment referring to that issue here.

2021-10-12 09:43 UTC, ushirask commented on compiler/tests/testSuite.bal
> +    return error("unreachable");
I was confused as well originally I returned  SemType|error and used a check however it worked even without

2021-10-12 09:48 UTC, manuranga commented on compiler/tests/testSuite.bal
> +    return error("unreachable");
It's very concerning if this compiles, lets create an issue in jBallerina if it does.

2021-10-12 10:22 UTC, ushirask commented on compiler/tests/testSuite.bal
> +    return error("unreachable");
created in https://github.com/ballerina-platform/ballerina-lang/issues/33175

2021-10-12 10:35 UTC, ushirask commented on compiler/modules/front.syntax/tests/testParserOnTestSuite.bal
> +                continue;
created issue in #555

2021-10-12 11:15 UTC, manuranga commented on compiler/modules/front.syntax/tests/testParserOnTestSuite.bal
> +                continue;
Please add a `xxx` comment here.

2021-10-12 14:24 UTC, manuranga commented on compiler/modules/front.syntax/tests/testParserOnTestSuite.bal
> +            // XXX need to handle type test cases in typeDescToWords
sorry I meant `xxx`

2021-10-12 14:25 UTC, manuranga commented on compiler/modules/front.syntax/tests/testParserOnTestSuite.bal
> +            // XXX need to handle type test cases in typeDescToWords
`// xxx remove after fixing #555`

2021-10-12 14:32 UTC, manuranga commented on compiler/testSuite/01-boolean/boolean-t.bal
> +type BL boolean[];
```suggestion
type B boolean;

// @type TF = B
type TF true|false;

// @type T < TF
type T true;

// @type F < B
type F false;

// @type INTEGER <> B
type INTEGER int;

// @type BL[1] = B
// @type BL[2] = B
type BL boolean[]; 
```

2021-10-12 17:51 UTC, manuranga commented on compiler/tests/testSuite.bal
> +            if t:isSubtype(tc, t, t:LIST) {
I think `t:isSubtypeSimple(t, t:LIST)` is better.

2021-10-12 17:51 UTC, manuranga commented on compiler/tests/testSuite.bal
> +            if t:isSubtype(tc, t, t:LIST) {
same for mapping

2021-10-13 05:11 UTC, manuranga commented
@jclark I think this is ready to be reviewed.

Please note that we only support literals in projection.

```
const R = 1;

type S [int, boolean, string];
type T 1|2;
type U boolean|string;
type V boolean;

// Below is useful to test, but I don't think SemTypes support it yet, does it?
// @type S[T] = U 

// This is not that useful, one can use literals instead.
// @type S[R] = V 
```

2021-10-13 07:40 UTC, manuranga commented on compiler/modules/front.syntax/parseTypeTest.bal
> +        return {identifier, index};
missing spaces.

2021-10-13 09:12 UTC, manuranga commented on compiler/modules/front.syntax/tests/testParserOnTestSuite.bal
> +            // xxx remove after fixing #555
Sorry, `XXX` was the correct thing.

2021-10-13 09:13 UTC, manuranga commented on compiler/modules/front.syntax/tests/testParserOnTestSuite.bal
> +            // xxx remove after fixing #555
Sorry, `XXX` was the correct thing.

2021-10-13 17:41 UTC, manuranga commented
Answering my own question :
```
// Below is useful to test, but I don't think SemTypes support it yet, does it?
// @type S[T] = U 
```
It is not supported for any SemType `T` but it is supported when T is `int` for lists and `T` is `string` for mappings.

Opt1 : Support `// @type S[T] = U`, we'll look up `T` if check if it's `int`/`string` and pass `()` to corresponding projection function.

Opt2: Support `// @type S[string] = U`


@ushirask Shall we try above Opt1.

2021-10-14 02:09 UTC, jclark commented
@manuranga I haven't implemented that yet: we'll need this when we add support for singletons. Opt1 sounds good to me.

2021-10-14 04:53 UTC, jclark commented
> This doesn't belong in 01-boolean.  A directory NN-foo is for subset NN. 

I suggest semtype/proj1-t.bal

2021-10-14 04:57 UTC, jclark requested changes

2021-10-14 04:57 UTC, jclark commented on compiler/showTypes.bal
> +
Why is this changed?

2021-10-14 04:57 UTC, jclark commented on compiler/testSuite/01-boolean/boolean-t.bal
> +type B boolean;
This doesn't belong in 01-boolean.  A directory NN-foo is for subset NN.

2021-10-14 04:57 UTC, jclark commented on compiler/tests/testSuite.bal
> +        match test.op {
You can do this much better.  Do t:isSubtype(tc, left, right) and vice-versa once. Make it into a pair of booleans. Then check that the pair of booleans has the right result.

2021-10-14 05:06 UTC, manuranga commented on compiler/modules/front.syntax/parseTypeTest.bal
> +    boolean literal;
Please remove the boolean, Lets make the identifiers separate. `int|string|Identifier index;`. this means we'll need something like `type Identifier [string];`.

2021-10-14 05:10 UTC, manuranga commented on compiler/tests/testSuite.bal
> +                    else if t:isSubtype(tc, k, t:INT){
I think this should be `k == t:INT`

2021-10-14 05:15 UTC, manuranga commented on compiler/tests/testSuite.bal
> +                    }
else we need to say we currently only support projections on int literals or the whole int type.

2021-10-14 06:12 UTC, ushirask commented on compiler/showTypes.bal
> +
It shouldn't be; fixed.

2021-10-14 08:07 UTC, manuranga commented on compiler/modules/front.syntax/parseTypeTest.bal
> +public type Identifier [string];
I don't get why James is not too keen on using `[string]` since that is essentially what `token.bal` is doing with `VariableLengthToken`, anyway let's stick to `public type Identifier string;` for now.

2021-10-14 08:22 UTC, manuranga commented on compiler/tests/testSuite.bal
> +                }
we need a `else` case that calls `singleShape(k)` and check if it `is int`.

2021-10-14 10:56 UTC, manuranga commented on compiler/modules/front.syntax/parseTypeTest.bal
> +    int|string|Identifier index;
```suggestion
    int|Identifier index;
```

2021-10-15 11:50 UTC, jclark approved these changes

2021-10-15 11:51 UTC, merged