Disallow underscore for org-name and module-name in import-decl
ballerina-platform/nballerina pull request #540
Opened 2021-10-08 09:02 UTC by KavinduZoysa

## Purpose
Fixes #444

2021-10-08 10:42 UTC, jclark requested changes

2021-10-08 10:42 UTC, jclark commented on compiler/modules/front.syntax/token.bal
> +    function expectImportPart() returns string|err:Syntax {
This should not be a method. Furthermore, the rule is not the identifier cannot contain identifiers.

2021-10-08 10:42 UTC, jclark commented on runtime/error.c
> +        if (*p == '_' || *p == '\0') {
This is not correct.

2021-10-08 10:42 UTC, jclark commented on runtime/tests/demangle.c
> -    { "_B0m7foo_bar3bazhello", "hello (foo_bar.baz)" },
Not correct

2021-10-08 11:30 UTC, KavinduZoysa commented on runtime/tests/demangle.c
> -    { "_B0m7foo_bar3bazhello", "hello (foo_bar.baz)" },
@jclark, since we disallow underscores in module name, `_B0m7foo_bar3bazhello` should not be demangled. So the output should be `_B0m7foo_bar3bazhello`.
Is this output incorrect or test case invalid?

2021-10-08 18:20 UTC, KavinduZoysa commented on runtime/tests/demangle.c
> -    { "_B0m7foo_bar3bazhello", "hello (foo_bar.baz)" },
Please ignore the above comment.

2021-10-10 02:47 UTC, KavinduZoysa commented on compiler/modules/front.syntax/token.bal
> +    function expectImportPart() returns string|err:Syntax {
Changed

2021-10-10 02:47 UTC, KavinduZoysa commented on runtime/error.c
> +        if (*p == '_' || *p == '\0') {
Changed

2021-10-10 02:47 UTC, KavinduZoysa commented on runtime/tests/demangle.c
> -    { "_B0m7foo_bar3bazhello", "hello (foo_bar.baz)" },
Changed

2021-10-11 06:25 UTC, jclark requested changes

2021-10-11 06:25 UTC, jclark commented on runtime/error.c
> +        if (*p == '_') {
Don't make this change. We are not validating other characters. Apply Postel's law.

2021-10-11 06:25 UTC, jclark commented on compiler/modules/front.syntax/parse.bal
> +function validImportPart(Tokenizer tok) returns string|err:Syntax {
You are not checking for a leading `_`. Right way to write this function is to have a local variable `string? prevChar` and then iterate over each character (`foreach var ch in identifier`); if it's an underscore, then check whether prevChar is () or `_`. At the end check for prevChar being `_`.

2021-10-11 15:16 UTC, KavinduZoysa commented on runtime/error.c
> +        if (*p == '_') {
Reverted runtime change

2021-10-11 15:17 UTC, KavinduZoysa commented on compiler/modules/front.syntax/parse.bal
> +function validImportPart(Tokenizer tok) returns string|err:Syntax {
Fixed

2021-10-12 00:52 UTC, jclark requested changes

2021-10-12 00:52 UTC, jclark commented on compiler/modules/front.syntax/parse.bal
> +                return tok.err("expect an identifier without leading underscores");
In all of the three messages instead "expect an identifier without" say "identifier in an import must not have"

2021-10-12 02:58 UTC, KavinduZoysa commented on compiler/modules/front.syntax/parse.bal
> +                return tok.err("expect an identifier without leading underscores");
Changed

2021-10-12 04:04 UTC, merged