Add positions to statement AST nodes
ballerina-platform/nballerina pull request #542
Opened 2021-10-10 10:56 UTC by heshanpadmasiri

## Purpose

- Add position to statement AST nodes (except `CallStmt` because they can be expressions as well)
- Add ability to move the tokenizer to a given position
- Fix end position pointing to the exclusive upper bound not the the inclusive bound

Related to #513

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-10-11 01:00 UTC, jclark requested changes

2021-10-11 01:00 UTC, jclark commented on compiler/modules/front.syntax/token.bal
> +    function moveToPos(Position pos, Mode mode) returns err:Syntax? {
You don't seem to be using `mode`.

2021-10-11 01:00 UTC, jclark commented on compiler/modules/front.syntax/scan.bal
> +function fragCodeLength(FragCode fragCode, int fragmentIndex, readonly & string[] fragments) returns [int, int] {
Calling something *Length() when it returns a pair isn't good. I'm not separating out this function makes things clearer. Second int is always 0 or 1, which is a bit weird.

2021-10-11 01:00 UTC, jclark commented on compiler/modules/front.syntax/ast.bal
> +public type BreakStmtBody "break";
This is a bit ugly. I think I would do

```
public type BreakContinue "break"|"continue";

public type BreakContinueStmt {|
   *PositionFields;
   BreakContinue breakContinue;
|};
```

You will need to change codeGen accordingly. Have codeGenBreakContinueStmt and pass in the stmt.

2021-10-11 01:05 UTC, jclark requested changes

2021-10-11 01:05 UTC, jclark commented on compiler/modules/front.syntax/parseStmt.bal
> +            BreakStmt node = { startPos, endPos };
stmt not node.

2021-10-11 01:05 UTC, jclark commented on compiler/modules/front.syntax/parseStmt.bal
> +            Position endPos = check tok.expectLast(";");
Use expectEnd not expectLast.

2021-10-11 05:59 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/token.bal
> +    function moveToPos(Position pos, Mode mode) returns err:Syntax? {
fixed (moveToPos will now set mode correctly)

2021-10-11 05:59 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/scan.bal
> +function fragCodeLength(FragCode fragCode, int fragmentIndex, readonly & string[] fragments) returns [int, int] {
function removed. (I added this when I was using this separately for `moveToPos` no longer needed)

2021-10-11 06:01 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/ast.bal
> +public type BreakStmtBody "break";
fixed

2021-10-11 06:02 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseStmt.bal
> +            BreakStmt node = { startPos, endPos };
fixed

2021-10-11 06:02 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseStmt.bal
> +            Position endPos = check tok.expectLast(";");
fixed

2021-10-11 06:15 UTC, jclark requested changes

2021-10-11 06:15 UTC, jclark commented on compiler/modules/front/codeGen.bal
> +            if stmt.breakContinue is "break" {
Please merge codeGenBreakStmt and codeGenContinueStmt into codeGenBreakContinueStmt (there is common code), and pass in stmt as an argument (as in all the other cases).

2021-10-11 09:22 UTC, heshanpadmasiri commented on compiler/modules/front/codeGen.bal
> +            if stmt.breakContinue is "break" {
fixed

2021-10-11 09:24 UTC, jclark requested changes

2021-10-11 09:24 UTC, jclark commented on compiler/modules/front/codeGen.bal
> +    function addOnBreakContinueAssignments(int[] assignments, s:BreakContinue breakContinue) {
I don't think this merged function is good, because other methods in this class keep the break and continue cases separate.

2021-10-11 10:08 UTC, heshanpadmasiri commented on compiler/modules/front/codeGen.bal
> +    function addOnBreakContinueAssignments(int[] assignments, s:BreakContinue breakContinue) {
fixed

2021-10-11 10:12 UTC, jclark requested changes
> fixed 

Sorry I didn't make myself clear. I think it's better to continue to have separate methods for the break and continue cases in the CodeGenContext class.

2021-10-11 10:36 UTC, heshanpadmasiri commented
> > fixed
> 
> Sorry I didn't make myself clear. I think it's better to continue to have separate methods for the break and continue cases in the CodeGenContext class.

fixed

2021-10-12 00:50 UTC, jclark requested changes
Looks good.

2021-10-12 00:50 UTC, jclark commented on compiler/modules/front.syntax/parseStmt.bal
>          "break" => {
We should combine these cases i.e. `"break"|"continue" =>` You'll need to cast `cur` to work around a JBUG (include a comment).

2021-10-12 04:12 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseStmt.bal
>          "break" => {
fixed

2021-10-12 04:27 UTC, jclark approved these changes
Looks good

2021-10-12 04:27 UTC, merged