Check JBUGs in compiler/tests
ballerina-platform/nballerina pull request #559
Opened 2021-10-13 09:26 UTC by KavinduZoysa

## Purpose
Check JBUGs in compiler/tests folders
Related to #550

2021-10-13 09:28 UTC, KavinduZoysa commented on compiler/tests/testBalt.bal
>  //     dataProvider: parseBalts
@jclark, Do I need to change the dataProvider run properly after .balt files are added? Currently, dataProvider does not work with the new folder structure of testSuite.

2021-10-13 09:33 UTC, manuranga commented on compiler/tests/testBalt.bal
>  //     dataProvider: parseBalts
We'll not have `.balt`s for a while, OK to remove the whole thing.

2021-10-13 09:51 UTC, jclark commented
I would start with stuff that is not in a tests/ directory.

2021-10-14 03:49 UTC, jclark commented on compiler/tests/testBalt.bal
>  //     dataProvider: parseBalts
I don't want to do this. There are lots of conformance tests being done which we should test against soon.

2021-10-14 03:49 UTC, jclark commented
Please don't mix completely unrelated changes in one pull request.

2021-10-14 03:51 UTC, jclark requested changes

2021-10-14 03:51 UTC, jclark commented on compiler/tests/baltest.bal
> +        };
Don't need a semi-colon after the `}`

2021-10-14 05:07 UTC, KavinduZoysa commented on compiler/tests/baltest.bal
> +        };
It seems that removing semicolon causes for a compilation error. Created a new JBUG issue and add a comment accordingly.

2021-10-14 09:30 UTC, KavinduZoysa commented
> Please don't mix completely unrelated changes in one pull request.

Removed them.

2021-10-14 09:38 UTC, KavinduZoysa commented on compiler/tests/baltest.bal
> +        };
We discussed this in a language issue. Since this do-clause is a part of `checking-action` we need semi-colon. 
@jclark WDYT?

2021-10-14 09:48 UTC, manuranga commented on compiler/tests/baltest.bal
> +        };
Please link the lang issue.

2021-10-14 09:57 UTC, rdulmina commented on compiler/tests/baltest.bal
> +        };
https://github.com/ballerina-platform/ballerina-lang/issues/33227

2021-10-17 10:22 UTC, merged