Resolve JBUG in compile.bal
ballerina-platform/nballerina pull request #560
Opened 2021-10-13 14:20 UTC by KavinduZoysa

## Purpose
Resolve JBUG in compiler/compile.bal
Related to #550

2021-10-14 01:59 UTC, jclark requested changes

2021-10-14 01:59 UTC, jclark commented on compiler/compile.bal
> +        where !md.dir
Ah, this is so much nicer.

But please align let/where/select with from.

2021-10-14 03:27 UTC, KavinduZoysa commented on compiler/compile.bal
> +        where !md.dir
Changed

2021-10-14 04:49 UTC, jclark commented on compiler/compile.bal
> +                lines: check io:fileReadLines(md.absPath),
This is indented 5 spaces relative to `select`, which is not correct. Maybe it will work better if you put the `from` on a new line.

2021-10-14 05:05 UTC, KavinduZoysa commented on compiler/compile.bal
> +                lines: check io:fileReadLines(md.absPath),
Changed

2021-10-15 04:02 UTC, jclark approved these changes
Looks good.

2021-10-15 11:54 UTC, merged