Add positions to expression AST nodes
ballerina-platform/nballerina pull request #567
Opened 2021-10-15 06:11 UTC by heshanpadmasiri

## Purpose
Add positions to expression AST nodes
Related #513

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-10-15 07:23 UTC, jclark reviewed
I don't think we have an adequate testing strategy because there are several cases where there would have been test failures if this was being tested properly.

2021-10-15 07:23 UTC, jclark commented on compiler/modules/front.syntax/parseExpr.bal
> +        return { startPos, endPos,prefix, varName };
Space missing before `prefix`.

2021-10-15 07:23 UTC, jclark commented on compiler/modules/front.syntax/parseExpr.bal
>          Position pos = tok.currentStartPos();
This section needs reworking. Why do we need pos and startPos here?

2021-10-15 07:23 UTC, jclark commented on compiler/modules/front.syntax/parseExpr.bal
> +            endPos = tok.currentEndPos();
Don't think this is right. We advanced over the identifier. Isn't it just endPos saved above?

2021-10-15 07:23 UTC, jclark commented on compiler/modules/front.syntax/parseExpr.bal
> +        MemberAccessExpr accessExpr = { startPos:accessStartPos, endPos: accessEndPos, container: expr, index, pos };
Space after colon

2021-10-15 07:23 UTC, jclark commented on compiler/modules/front.syntax/parseExpr.bal
> +        Position accessStartPos = pos;
This doesn't look right. You're not using startPos. pos is getting duplicated.

2021-10-15 07:23 UTC, jclark commented on compiler/modules/front.syntax/parseStmt.bal
> +        VarRefExpr varRef = { startPos, endPos:tok.previousEndPos(), varName: identifier, prefix };
Space after colon

2021-10-15 07:23 UTC, jclark commented on compiler/modules/front.syntax/parseStmt.bal
> +        expr = check finishPrimaryExpr(tok, expr, startPos);
This isn't right. We now need to distinguish MethodCallStmt and MethodCallExpr since the former includes the semi-colon and the latter doesn't.

2021-10-15 07:23 UTC, jclark commented on compiler/modules/front.syntax/parseStmt.bal
> +        returnExpr = { startPos: tok.currentStartPos(), endPos, value: () }; // ConstValueExpr
startPos can't be right.

2021-10-15 10:52 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseExpr.bal
> +        return { startPos, endPos,prefix, varName };
fixed

2021-10-15 10:52 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseExpr.bal
>          Position pos = tok.currentStartPos();
removed pos (It was used only for error messages, now replaced with startPos)

2021-10-15 10:52 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseExpr.bal
> +            endPos = tok.currentEndPos();
fixed

2021-10-15 10:53 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseExpr.bal
> +        MemberAccessExpr accessExpr = { startPos:accessStartPos, endPos: accessEndPos, container: expr, index, pos };
fixed

2021-10-15 11:06 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseExpr.bal
> +        Position accessStartPos = pos;
fixed

2021-10-15 11:06 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseStmt.bal
> +        VarRefExpr varRef = { startPos, endPos:tok.previousEndPos(), varName: identifier, prefix };
fixed

2021-10-15 11:10 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseStmt.bal
> +        expr = check finishPrimaryExpr(tok, expr, startPos);
Currently we don't have an AST node type called MethodCallStmt (we only have MethodCallExpr) should I add a MethodCallStmt that wraps the MethodCallExpr. (Current code changed such that MethodCallExpr don't include `;`)

2021-10-15 11:14 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseStmt.bal
> +        returnExpr = { startPos: tok.currentStartPos(), endPos, value: () }; // ConstValueExpr
This is the case where the optional returnExpr in returnStmt token is empty (ie. return;). Though the returnExpr is optional in grammer it is required in the current AST implementation (it seems everywhere it is used first we check if returnExpr is ConstValueExpr and value is (), and if so ignored). May I turn it to an optional?

2021-10-15 11:29 UTC, heshanpadmasiri commented
> I don't think we have an adequate testing strategy because there are several cases where there would have been test failures if this was being tested properly.

Current testing strategy has two limitations

1. Whether we are considering the tokenizers previous end position or the current end position as the actual end position is hardcoded based on the node type for expressions. Thus if I made a error of judgement I am likely to set the position wrong both at the parser and test. Currently we are checking if this end point is white space but to fully catch such issues I think we will have to hardcode what should be the value of end token.
2. If I set the start position wrong and that wrong start position is the start position of a child node that end in the same position as the parent, if both child and parent nodes can be parsed using the same parsing function there will be no errors. (This is because pareser didn't failed and end point is correct). To fix this we have to check if the both the new node we got and original nodes are the same. For this now I have added a test that convert both nodes to string and see if they are equal. Is this there a better way to see if nodes are same?

2021-10-15 11:39 UTC, jclark commented
> Currently we don't have an AST node type called MethodCallStmt (we only have MethodCallExpr) should I add a MethodCallStmt that wraps the MethodCallExpr. (Current code changed such that MethodCallExpr don't include `;`) 

Have a look at the spec. I think it's CallStmt that can wrap function or method call.

2021-10-15 11:40 UTC, jclark commented
> This is the case where the optional returnExpr in returnStmt token is empty (ie. return;). Though the returnExpr is optional in grammer it is required in the current AST implementation (it seems everywhere it is used first we check if returnExpr is ConstValueExpr and value is (), and if so ignored). May I turn it to an optional? 

Yes. Good idea.

2021-10-16 18:12 UTC, manuranga commented on compiler/modules/front/codeGen.bal
> +        nextBlock = codeGenExpr.block;
```suggestion
        { result: operand, block: nextBlock } = check codeGenExpr(cx, startBlock, env, check cx.foldExpr(env, returnExpr, cx.returnType));
```

2021-10-17 10:06 UTC, heshanpadmasiri commented on compiler/modules/front/codeGen.bal
> +        nextBlock = codeGenExpr.block;
fixed

2021-10-17 10:06 UTC, heshanpadmasiri commented
> > This is the case where the optional returnExpr in returnStmt token is empty (ie. return;). Though the returnExpr is optional in grammer it is required in the current AST implementation (it seems everywhere it is used first we check if returnExpr is ConstValueExpr and value is (), and if so ignored). May I turn it to an optional?
> 
> Yes. Good idea.

fixed

2021-10-17 10:26 UTC, jclark reviewed
This generally looks good, but there are a lot of changes, so I need to have another look tomorrow.

2021-10-17 10:26 UTC, jclark commented on compiler/modules/front/codeGen.bal
> +        expr = { startPos, endPos, bitwiseOp: <s:BinaryBitwiseOp> op, left: lValue, right: rexpr };
Do we really need the cast here? If so, I think it's a JBUG.

2021-10-18 04:03 UTC, heshanpadmasiri commented on compiler/modules/front/codeGen.bal
> +        expr = { startPos, endPos, bitwiseOp: <s:BinaryBitwiseOp> op, left: lValue, right: rexpr };
fixed

2021-10-18 09:10 UTC, jclark requested changes
How can our testing guarantee that we don't have this sort of problem (using currentEndPos when we should have used previousEndPos). I think we have to test when we have an binary expression E with subexpressions L and R, that the only things within E (i.e. between the startPos and endPos) but not within L and not within R are the operator and whitespace/comments.

2021-10-18 09:10 UTC, jclark commented on compiler/modules/front.syntax/parseExpr.bal
> +            Position endPos = tok.currentEndPos();
This has advanced over the last token in the expression already, hasn't it? So shouldn't it be previousEndPos(). I think this applies to many other cases in this file.

2021-10-18 18:32 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseExpr.bal
> +            Position endPos = tok.currentEndPos();
fixed

2021-10-18 18:33 UTC, heshanpadmasiri commented
> How can our testing guarantee that we don't have this sort of problem (using currentEndPos when we should have used previousEndPos). I think we have to test when we have an binary expression E with subexpressions L and R, that the only things within E (i.e. between the startPos and endPos) but not within L and not within R are the operator and whitespace/comments.

Added two seperate functions one (`testValidInterExpressionRange`) generally validating the range between child nodes and one (`testValidExprEnd`) that check the endpos to check if it is something that can't be the endpos for a given expression

2021-10-20 02:34 UTC, jclark approved these changes
In the next pull request, can you please separate out the postion related code in testParserOnTestSuite into a testPos file?

2021-10-20 02:35 UTC, merged