Implement field access lvalues
ballerina-platform/nballerina pull request #569
Opened 2021-10-17 18:10 UTC by manuranga

Fixes #510

2021-10-17 18:11 UTC, manuranga commented
This PR is done on top of #556, so please merge that one first.

2021-10-18 03:23 UTC, jclark reviewed
Can you update? The diff doesn't make sense to me (e.g. 1152 of codeGen).

2021-10-18 07:32 UTC, jclark requested changes

2021-10-18 07:32 UTC, jclark commented on compiler/modules/front/codeGen.bal
> +    s:VarRefExpr mappingRef = lValue is s:FieldAccessLExpr ? (lValue.mapping) : lValue.container;
We should fix FieldAccessLExpr to use `container` rather than `mapping`, so we don't need the condition.

2021-10-18 07:32 UTC, jclark commented on compiler/modules/front/codeGen.bal
> +function codeGenMappingKey(CodeGenContext cx, bir:BasicBlock block, Environment env, s:MemberAccessLExpr|s:FieldAccessLExpr mappingLValue, t:SemType mappingType) returns CodeGenError|StringExprEffect
I would like to name this so it's clear it is dealing with lvalues. Maybe codeGenLExprMappingKey?

2021-10-18 07:32 UTC, jclark commented on docs/subset09.md
> +* Field access lvalue
I would put these two field access items as subitems under closed record types.

These two also need to be mentioned in the subset summary at the top.

2021-10-18 09:18 UTC, manuranga commented on compiler/modules/front/codeGen.bal
> +    s:VarRefExpr mappingRef = lValue is s:FieldAccessLExpr ? (lValue.mapping) : lValue.container;
Should `FieldAccessExpr` also be changed for consistency ?

2021-10-18 09:19 UTC, jclark commented on compiler/modules/front/codeGen.bal
> +    s:VarRefExpr mappingRef = lValue is s:FieldAccessLExpr ? (lValue.mapping) : lValue.container;
Yes, good idea.

2021-10-18 10:28 UTC, merged