Add positions to Type descriptor AST nodes
ballerina-platform/nballerina pull request #593
Opened 2021-10-20 07:16 UTC by heshanpadmasiri

## Purpose
Add positions to Type descriptor AST nodes
Resolves #513

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-10-20 08:27 UTC, manuranga commented on compiler/modules/front.syntax/ast.bal
> +public type BuiltinTypeDesc record {|
Why can't `BuiltinTypeDesc` be `"boolean"|"int"|"float"|"string"|"error"|"any"|"byte"|"decimal"|"handle"|"json"|"never"|"readonly"|"typedesc"|"xml"|"()"` ?

2021-10-20 10:17 UTC, jclark commented on compiler/modules/front.syntax/ast.bal
> +public type BuiltinTypeDesc record {|
Because it needs to have a position.

2021-10-20 10:25 UTC, manuranga commented on compiler/modules/front.syntax/ast.bal
> +public type BuiltinTypeDesc record {|
Ahh Ok.

2021-10-20 10:31 UTC, jclark reviewed
I haven't reviewed this fully yet.

2021-10-20 10:31 UTC, jclark commented on compiler/modules/front.syntax/ast.bal
> +public type BuiltinType "boolean"|"int"|"float"|"string"|"error"|"any"|"byte"|"decimal"|"handle"|"json"|"never"|"readonly"|"typedesc"|"xml"|"()";
I don't like `BuiltinType` here. Let's call it `BuiltinTypeName`, but change `"()"` to `"null"` (since both `null` is equivalent to `()`).

2021-10-20 10:31 UTC, jclark commented on compiler/modules/front.syntax/ast.bal
> +    BuiltinType builtinType;
Then use builtinTypeName for the field name

2021-10-20 10:31 UTC, jclark commented on compiler/modules/front.syntax/parse.bal
> +        td = { startPos: tdStartPos, endPos: tdEndPos, builtinType:t };
Space after colon

2021-10-20 10:31 UTC, jclark commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +                return { startPos, endPos:expr.endPos, value };
Space after colon

2021-10-20 10:31 UTC, jclark commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +                return { startPos, endPos:expr.endPos, value };
Space after colon

2021-10-20 10:31 UTC, jclark commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +            return { startPos, endPos:expr.endPos, value };
Space after colon

2021-10-20 10:31 UTC, jclark commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +        ret = { startPos:tok.currentStartPos(), endPos, builtinType:"()" };
Space after colon

2021-10-20 10:31 UTC, jclark commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +    return { startPos, endPos, fields, rest: rest ?: { startPos, endPos:startPos, builtinType:"never" } };
Space after colon

rest bit looks bogus. Can we make it optional in the AST?

2021-10-20 16:07 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/ast.bal
> +public type BuiltinType "boolean"|"int"|"float"|"string"|"error"|"any"|"byte"|"decimal"|"handle"|"json"|"never"|"readonly"|"typedesc"|"xml"|"()";
fixed

2021-10-20 16:07 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/ast.bal
> +    BuiltinType builtinType;
fixed

2021-10-20 16:08 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parse.bal
> +        td = { startPos: tdStartPos, endPos: tdEndPos, builtinType:t };
fixed

2021-10-20 16:08 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +                return { startPos, endPos:expr.endPos, value };
fixed

2021-10-20 16:08 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +                return { startPos, endPos:expr.endPos, value };
fixed

2021-10-20 16:09 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +            return { startPos, endPos:expr.endPos, value };
fixed

2021-10-20 16:09 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +        ret = { startPos:tok.currentStartPos(), endPos, builtinType:"()" };
fixed

2021-10-20 16:09 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +    return { startPos, endPos, fields, rest: rest ?: { startPos, endPos:startPos, builtinType:"never" } };
fixed. Made rest optional in the ast

2021-10-21 03:17 UTC, jclark requested changes
Turns out we still need a type corresponding to InlineBuiltinTypeDesc to distinguish types accepted in our subset.

2021-10-21 03:17 UTC, jclark commented on compiler/modules/front.syntax/ast.bal
>  public type LeafTypeDesc BuiltinTypeDesc;
Do we still need LeafTypeDesc?  I think I was using LeafTypeDesc more likle BuiltinTypeName rather than BuiltinTypeDesc.

2021-10-21 03:17 UTC, jclark commented on compiler/modules/front.syntax/ast.bal
> -public type InlineBuiltinTypeDesc "boolean"|"int"|"float"|"string"|"error"|"any";
Simply removing this rid of this doesn't quite work.  We are relying on this in parseConstDefinition.  The subset grammar has

```
const-defn = ["public"] "const" [builtin-type-name] identifier "=" const-expr ";"
builtin-type-name = "any" | "boolean" | "int" | "float" | "string" | "error"
```

With this pull request as is, the code will crash in resolveBuiltinTypeDesc if we use something like `json` in a const definition.


So let's fix this as follows. Keep InlineBuiltinTypeDesc but rename SubsetBuiltinTypeDesc, and add a comment that it is used for ConstDefinition.  Use it in ConstDefinition and resolveBuiltinTypeDesc.

2021-10-21 03:17 UTC, jclark commented on compiler/modules/front.syntax/parseStmt.bal
> +        var td if td is "boolean"|"int"|"float"|"string"|"error"|"any"|"byte"|
No. We need to parse the subset grammar: this would be accepting things not in the subset. Use SubsetBuiltinTypeName here.

2021-10-21 03:54 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/ast.bal
>  public type LeafTypeDesc BuiltinTypeDesc;
LeafTypeDesc removed. (replaced by BuilinTypeDesc)

2021-10-21 03:54 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/ast.bal
> -public type InlineBuiltinTypeDesc "boolean"|"int"|"float"|"string"|"error"|"any";
fixed

2021-10-21 03:55 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseStmt.bal
> +        var td if td is "boolean"|"int"|"float"|"string"|"error"|"any"|"byte"|
fixed

2021-10-21 04:19 UTC, jclark requested changes

2021-10-21 04:19 UTC, jclark commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +            BinaryTypeDesc bin =  { startPos, endPos, op: "|", left: td,
I prefer to format multi-line constructors like this:

```
BinaryTypeDesc bin =  {
    startPos,
    endPos, 
    op: "|",
    left: td,
    right: { startPos: endPos, endPos, builtinTypeName: "null"}
}; 
```

2021-10-21 04:19 UTC, jclark commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +            if td is BuiltinTypeDesc {
What's going on here? This doesn't look right.

2021-10-21 04:19 UTC, jclark commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +                return {startPos, endPos, builtinTypeName: td.builtinTypeName};
Spacing

2021-10-21 04:19 UTC, jclark commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +            return { startPos, endPos, prefix: <BuiltinTypeName>cur, typeName, pos };
Type of `prefix` is string, so better to cast to `<string>`

2021-10-21 04:55 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +            BinaryTypeDesc bin =  { startPos, endPos, op: "|", left: td,
fixed

2021-10-21 05:00 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +            if td is BuiltinTypeDesc {
This is parsing something of the form `basic-type-desc ="(" union-type-desc ")"`. So I need to set the endPos to ")". `td` get's endPoint before the ")" (at the end of `union-type-desc`) so I am updating the endPos of td here. However I have made `BuiltinTypeDesc` readonly (to make `SubsetBuiltinTypeDesc` subtype of it) so I can't update the endPos field here if I get a `BuiltinTypeDesc` as `td`. Therefore I am making a new copy of the `td` with endPos having the correct value.

2021-10-21 05:00 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +                return {startPos, endPos, builtinTypeName: td.builtinTypeName};
fixed

2021-10-21 05:00 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseTypeDesc.bal
> +            return { startPos, endPos, prefix: <BuiltinTypeName>cur, typeName, pos };
fixed

2021-10-21 05:24 UTC, jclark requested changes
> This is parsing something of the form `basic-type-desc ="(" union-type-desc ")"`. So I need to set the endPos to ")". `td` get's endPoint before the ")" (at the end of `union-type-desc`) so I am updating the endPos of td here. However I have made `BuiltinTypeDesc` readonly (to make `SubsetBuiltinTypeDesc` subtype of it) so I can't update the endPos field here if I get a `BuiltinTypeDesc` as `td`. Therefore I am making a new copy of the `td` with endPos having the correct value. 

The underlying problem here is that we are not representing parenthesized type descriptors explicitly in the AST. If we have something like `(int)` then there are two type-descriptors with distinct start/end positions: `int` and `(int)`. To deal with this cleanly, we need to introduce another kind of TypeDesc, say ParenTypeDesc. (I suspect we have a similar problem with expressions and should introduce ParenExpr also. You can deal with this in a separate follow on pull request.)

2021-10-21 05:40 UTC, heshanpadmasiri commented
> > This is parsing something of the form `basic-type-desc ="(" union-type-desc ")"`. So I need to set the endPos to ")". `td` get's endPoint before the ")" (at the end of `union-type-desc`) so I am updating the endPos of td here. However I have made `BuiltinTypeDesc` readonly (to make `SubsetBuiltinTypeDesc` subtype of it) so I can't update the endPos field here if I get a `BuiltinTypeDesc` as `td`. Therefore I am making a new copy of the `td` with endPos having the correct value.
> 
> The underlying problem here is that we are not representing parenthesized type descriptors explicitly in the AST. If we have something like `(int)` then there are two type-descriptors with distinct start/end positions: `int` and `(int)`. To deal with this cleanly, we need to introduce another kind of TypeDesc, say ParenTypeDesc. (I suspect we have a similar problem with expressions and should introduce ParenExpr also. You can deal with this in a separate follow on pull request.)

Removed extending start and end pos to cover parenthesis. Yes we have the same issue with expressions as well

2021-10-21 06:23 UTC, jclark commented
So you're going to do ParenTypeDesc as well as ParenExpr in a separate pull request?

2021-10-21 06:23 UTC, merged

2021-10-21 06:30 UTC, heshanpadmasiri commented
> So you're going to do ParenTypeDesc as well as ParenExpr in a separate pull request?

Yes