Add operator position to binary and unary AST expressions
ballerina-platform/nballerina pull request #621
Opened 2021-10-22 09:46 UTC by heshanpadmasiri

## Purpose
Add operator position to binary and unary expressions AST expressions
Add operator position to corresponding BIR instructions 
Related to #604, #605

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-10-28 04:25 UTC, jclark requested changes

2021-10-28 04:25 UTC, jclark commented on compiler/modules/bir/bir.bal
> +    Position opPos;
For instructions, the field can continue to be called `pos`: we are only having one position per insn.

2021-10-28 04:25 UTC, jclark commented on compiler/modules/front.syntax/ast.bal
>      Position pos;
Why do we need `pos` in addition to opPos, startPos and endPos?

2021-10-28 07:30 UTC, heshanpadmasiri commented on compiler/modules/bir/bir.bal
> +    Position opPos;
fixed

2021-10-28 07:31 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/ast.bal
>      Position pos;
removed `pos` (replaced with opPos)

2021-10-28 07:45 UTC, jclark requested changes

2021-10-28 07:45 UTC, jclark commented on compiler/modules/bir/verify.bal
> +        return vc.err(`operand of ${insn.op} at ${insn.pos} does not match order type`);
pos should be passed as a parameter

2021-10-28 07:45 UTC, jclark commented on compiler/modules/bir/verify.bal
> +                    return vc.err(`at least one operand of an == or !=  at ${insn.pos} expression must be a subtype of anydata`);
pos should be passed as a parameter

2021-10-28 07:45 UTC, jclark commented on compiler/modules/bir/verify.bal
> +    return vc.err(`intersection of operands of operator ${insn.op} at ${insn.pos} is empty`);
pos should be passed as a parameter

2021-10-28 07:45 UTC, jclark commented on compiler/modules/front/codeGen.bal
> +function codeGenArithmeticBinaryExpr(CodeGenContext cx, bir:BasicBlock bb, bir:ArithmeticBinaryOp op, bir:Position opPos, bir:Operand lhs, bir:Operand rhs) returns CodeGenError|ExprEffect {
Call the parameter `pos`.

2021-10-28 07:45 UTC, jclark commented on compiler/modules/front/codeGen.bal
> +function codeGenBitwiseBinaryExpr(CodeGenContext cx, bir:BasicBlock bb, s:BinaryBitwiseOp op, err:Position opPos, bir:IntOperand lhs, bir:IntOperand rhs) returns CodeGenError|ExprEffect {
Call the parameter `pos`

2021-10-28 07:45 UTC, jclark commented on compiler/modules/front/codeGen.bal
> +function codeGenEquality(CodeGenContext cx, bir:BasicBlock bb, Environment env, s:BinaryEqualityOp op, err:Position opPos, s:Expr left, s:Expr right) returns CodeGenError|ExprEffect {
Call the parameter `pos`

2021-10-28 07:45 UTC, jclark commented on compiler/modules/front/codeGen.bal
> +function codeGenCompoundableBinaryExpr(CodeGenContext cx, bir:BasicBlock bb, Environment env, s:BinaryArithmeticOp|s:BinaryBitwiseOp op, bir:Position opPos, bir:Register member, s:Expr rexpr) returns
Call the parameter `pos`

2021-10-28 07:45 UTC, jclark commented on compiler/modules/front/codeGen.bal
> +                                              err:Position opPos) returns CodeGenError|StmtEffect {
Call the parameter `pos`

2021-10-28 07:45 UTC, jclark commented on compiler/modules/front/codeGen.bal
> +                                           err:Position opPos) returns CodeGenError|StmtEffect {
Call the parameter `pos`.

2021-10-28 07:45 UTC, jclark commented on compiler/modules/front/codeGen.bal
> +    var { lValue, expr, op, opPos } = stmt;
I would do `pos: opPos` i.e. call the parameter `pos`.

2021-10-28 08:22 UTC, heshanpadmasiri commented on compiler/modules/front/codeGen.bal
> +    var { lValue, expr, op, opPos } = stmt;
fixed

2021-10-28 08:22 UTC, heshanpadmasiri commented on compiler/modules/front/codeGen.bal
> +                                           err:Position opPos) returns CodeGenError|StmtEffect {
fixed

2021-10-28 08:22 UTC, heshanpadmasiri commented on compiler/modules/front/codeGen.bal
> +                                              err:Position opPos) returns CodeGenError|StmtEffect {
fixed

2021-10-28 08:22 UTC, heshanpadmasiri commented on compiler/modules/front/codeGen.bal
> +function codeGenCompoundableBinaryExpr(CodeGenContext cx, bir:BasicBlock bb, Environment env, s:BinaryArithmeticOp|s:BinaryBitwiseOp op, bir:Position opPos, bir:Register member, s:Expr rexpr) returns
fixed

2021-10-28 08:22 UTC, heshanpadmasiri commented on compiler/modules/front/codeGen.bal
> +function codeGenEquality(CodeGenContext cx, bir:BasicBlock bb, Environment env, s:BinaryEqualityOp op, err:Position opPos, s:Expr left, s:Expr right) returns CodeGenError|ExprEffect {
fixed

2021-10-28 08:23 UTC, heshanpadmasiri commented on compiler/modules/front/codeGen.bal
> +function codeGenBitwiseBinaryExpr(CodeGenContext cx, bir:BasicBlock bb, s:BinaryBitwiseOp op, err:Position opPos, bir:IntOperand lhs, bir:IntOperand rhs) returns CodeGenError|ExprEffect {
fixed

2021-10-28 08:23 UTC, heshanpadmasiri commented on compiler/modules/front/codeGen.bal
> +function codeGenArithmeticBinaryExpr(CodeGenContext cx, bir:BasicBlock bb, bir:ArithmeticBinaryOp op, bir:Position opPos, bir:Operand lhs, bir:Operand rhs) returns CodeGenError|ExprEffect {
fixed

2021-10-28 08:23 UTC, heshanpadmasiri commented on compiler/modules/bir/verify.bal
> +    return vc.err(`intersection of operands of operator ${insn.op} at ${insn.pos} is empty`);
fixed

2021-10-28 08:28 UTC, heshanpadmasiri commented on compiler/modules/bir/verify.bal
> +                    return vc.err(`at least one operand of an == or !=  at ${insn.pos} expression must be a subtype of anydata`);
fixed

2021-10-28 08:28 UTC, heshanpadmasiri commented on compiler/modules/bir/verify.bal
> +        return vc.err(`operand of ${insn.op} at ${insn.pos} does not match order type`);
fixed

2021-10-29 02:41 UTC, jclark requested changes

2021-10-29 02:41 UTC, jclark commented on compiler/modules/front/codeGen.bal
> +    bir:CompareInsn compare = { op: "<", pos: stmt.range.upper.startPos, orderType: t:UT_INT, operands: [loopVar, upper], result: condition };
On reflection, I think it's better to make this position be the position of `..<`.

2021-10-29 02:41 UTC, jclark commented on compiler/modules/front.syntax/parseStmt.bal
> +function parseCompoundAssignStmt(Tokenizer tok, LExpr lValue, CompoundAssignOp op, Position opPos, Position startPos) returns CompoundAssignStmt|err:Syntax {
startPos argument after opPos seems a weird ordering to me, given that opPos is after startPos.

2021-10-29 02:41 UTC, jclark commented on compiler/modules/front.syntax/ast.bal
>      Stmt[] block;
We should have startPos and endPos here also.

2021-10-29 04:13 UTC, heshanpadmasiri commented on compiler/modules/front/codeGen.bal
> +    bir:CompareInsn compare = { op: "<", pos: stmt.range.upper.startPos, orderType: t:UT_INT, operands: [loopVar, upper], result: condition };
fixed

2021-10-29 04:13 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/parseStmt.bal
> +function parseCompoundAssignStmt(Tokenizer tok, LExpr lValue, CompoundAssignOp op, Position opPos, Position startPos) returns CompoundAssignStmt|err:Syntax {
fixed

2021-10-29 04:14 UTC, heshanpadmasiri commented on compiler/modules/front.syntax/ast.bal
>      Stmt[] block;
fixed

2021-11-01 00:45 UTC, jclark approved these changes

2021-11-01 00:45 UTC, merged