Move list construction logic to C
ballerina-platform/nballerina pull request #624
Opened 2021-10-23 11:33 UTC by manuranga

Fixes  #609, #203

2021-10-23 14:05 UTC, jclark commented on compiler/modules/nback/structure.bal
> +        _ = builder.call(scaffold.getRuntimeFunctionDecl(listInitMemberFunction),
I don't see why it's an improvement to do this with a function call.

2021-10-23 14:05 UTC, jclark commented on runtime/container.h
> +static void initArray(GC GenericArray *ap, int64_t capacity, int shift) {
Why can't this be inline and go in balrt.h (with a suitable name)?

2021-10-26 07:01 UTC, jclark requested changes

2021-10-26 07:01 UTC, jclark commented on runtime/balrt.h
> +static inline void initMemberArray(GC GenericArray *ap, int64_t capacity, int shift) {
Better to call this initGenericArray (since the type is GenericArray)

2021-10-26 07:01 UTC, jclark commented on compiler/modules/nback/structure.bal
> +    llvm:PointerValue struct = <llvm:PointerValue>builder.call(scaffold.getRuntimeFunctionDecl(listConstructFunction),
listConstruct is or'ing in flags which you then immediately remove with the ptrmask.  Better for listConstruct to return a ListPtr and then use buildTaggedPtr at the end, as before.

2021-10-26 17:31 UTC, manuranga commented on compiler/modules/nback/structure.bal
> +    builder.store(buildTaggedPtr(builder, builder.bitCast(struct, LLVM_TAGGED_PTR), TAG_LIST_RW|FLAG_EXACT), scaffold.address(insn.result));
It would have been slightly better to do

```suggestion
    builder.store(builder.bitCast(buildTaggedPtr(builder, struct, TAG_LIST_RW|FLAG_EXACT), LLVM_TAGGED_PTR), scaffold.address(insn.result));
```

but that gives the wrong result. I think this is because `buildTaggedPtr` uses `getElementPtr` to do pointer calculation and it only works when it is a `i8*`.

2021-10-27 06:01 UTC, jclark approved these changes

2021-10-27 06:01 UTC, merged