Resolve some JBUGs in scan.bal
ballerina-platform/nballerina pull request #625
Opened 2021-10-23 15:08 UTC by KavinduZoysa

## Purpose
Related to #550

2021-10-23 15:09 UTC, KavinduZoysa commented
New issues:
https://github.com/ballerina-platform/ballerina-lang/issues/33355
https://github.com/ballerina-platform/ballerina-lang/issues/33346

2021-10-25 07:08 UTC, manuranga commented on compiler/modules/front.syntax/scan.bal
> +            endFragment(<FragCode>FCP, i + 1, result);
We should avoid this cast by changing the type of `FCP`. (might end up being a JBUG)

2021-10-25 07:41 UTC, KavinduZoysa commented on compiler/modules/front.syntax/scan.bal
> +            endFragment(<FragCode>FCP, i + 1, result);
Fixed

2021-10-25 12:17 UTC, jclark commented on compiler/modules/front.syntax/scan.bal
> +    //JBUG #33355 shouldn't clone, query syntax should produce readonly arrays
This is a spec issue: please open a PR in the ballerina-spec repo.

2021-10-25 12:17 UTC, jclark commented on compiler/modules/front.syntax/scan.bal
> +                endFragment(<FragCode>cp, i, result);
Why do we need this cast?

2021-10-25 15:58 UTC, KavinduZoysa commented on compiler/modules/front.syntax/scan.bal
> +                endFragment(<FragCode>cp, i, result);
Because cp is an element of array returned from `toCodePointInts`, its' return type is `int[]`

2021-10-25 15:58 UTC, KavinduZoysa commented on compiler/modules/front.syntax/scan.bal
> +    //JBUG #33355 shouldn't clone, query syntax should produce readonly arrays
Isn't this https://github.com/ballerina-platform/ballerina-spec/issues/865 the spec issue? I have mentioned this spec issue in #33355

2021-10-27 03:40 UTC, jclark commented on compiler/modules/front.syntax/scan.bal
> +    //JBUG #33355 shouldn't clone, query syntax should produce readonly arrays
Ok

2021-10-27 03:44 UTC, jclark commented on compiler/modules/front.syntax/scan.bal
> +                endFragment(<FragCode>cp, i, result);
It is a JBUG. From the match, we know cp belongs to byte.

2021-10-27 03:46 UTC, jclark requested changes
Cast is a JBUG

2021-10-27 07:44 UTC, KavinduZoysa commented on compiler/modules/front.syntax/scan.bal
> +                endFragment(<FragCode>cp, i, result);
Created an issue https://github.com/ballerina-platform/ballerina-lang/issues/33446

2021-10-27 08:57 UTC, merged