Resolve JBUGs related to template string in testParser.bal
ballerina-platform/nballerina pull request #630
Opened 2021-10-26 05:28 UTC by KavinduZoysa

## Purpose
Related to #550

2021-10-26 05:29 UTC, KavinduZoysa commented
Create new issue:
https://github.com/ballerina-platform/ballerina-lang/issues/33390

2021-10-26 06:45 UTC, jclark requested changes

2021-10-26 06:45 UTC, jclark commented on compiler/modules/front.syntax/tests/testParser.bal
> +        // JBUG #33390
Please say what the bug is

2021-10-26 07:11 UTC, KavinduZoysa commented on compiler/modules/front.syntax/tests/testParser.bal
> +        // JBUG #33390
Edited

2021-10-27 03:38 UTC, jclark approved these changes

2021-10-27 03:38 UTC, merged

2021-10-28 17:39 UTC, manuranga commented on compiler/modules/front.syntax/tests/testParser.bal
> +        ["E", string`"\r"`],
This is meant to say strings with new lines are invalid, current translation is wrong.