Optimize tagged value eq when immediate
ballerina-platform/nballerina pull request #902
Opened 2022-02-07 12:46 UTC by manuranga

Part of #893

Not addressed in this pr:
- When one side is const
- ===

2022-02-07 12:54 UTC, manuranga commented
```ballerina
public function f(1|"one"|2|"two"|boolean x, 2|"two"|3|"three"|boolean y) returns boolean {
    return x == y;
}
```
gets optimized to
```llvm
define i1 @_B04rootf(i8 addrspace(1)* readnone %0, i8 addrspace(1)* readnone %1) local_unnamed_addr !dbg !11 {
  %3 = alloca i8, align 1
  %4 = load i8*, i8** @_bal_stack_guard, align 8
  %5 = icmp ult i8* %3, %4
  br i1 %5, label %8, label %6

6:                                                ; preds = %2
  %7 = icmp eq i8 addrspace(1)* %0, %1
  ret i1 %7

8:                                                ; preds = %2
  %9 = call i8 addrspace(1)* @_bal_panic_construct(i64 2308), !dbg !26
  call void @_bal_panic(i8 addrspace(1)* %9)
  unreachable
}
```

2022-02-08 06:02 UTC, jclark requested changes

2022-02-08 06:02 UTC, jclark commented on compiler/modules/nback/equal.bal
> +    if t:isSubtypeSimple(ty, t:NIL|t:BOOLEAN) {
Don't see the need for this.

2022-02-08 06:02 UTC, jclark commented on compiler/modules/nback/equal.bal
> +    t:IntSubtype|boolean intSubtype = t:intSubtype(ty);
```
record {|
  int? min;
  int? max;
  boolean contiguous;
|};
```

2022-02-21 07:24 UTC, manuranga commented
Close in favor of #912.

2022-02-21 07:24 UTC, closed without merging