Add support for the windows build
ballerina-platform/nballerina pull request #93
Opened 2021-02-11 18:58 UTC by KavinduZoysa

## Purpose
$subject
Resolves #66.

In this PR we only expect to build nballerina executable.

## Test environment
> windows 10

2021-02-12 07:37 UTC, ruvi-d requested changes
I think we should include the LLVM src as a submodule as discussed in #53. We only need to init and build it under Windows. 

Doing this will make our CMake script simpler because we know the relative path to LLVM and it will also make it easier to setup CI/CD for windows.

2021-02-12 13:11 UTC, ruvi-d requested changes
Noted some issues and also some suggestions for improvements.

2021-02-12 13:11 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +    p = strcpy(newName, "anon-");
You can't replace `stpcpy` with `strcpy`. One returns a pointer to the start, the other returns a pointer to the end.

2021-02-12 13:11 UTC, ruvi-d commented on compiler/llvmTypeCastInsn.cpp
> +#endif
As mentioned previously. Let's use `volatile` instead.

2021-02-12 13:11 UTC, ruvi-d commented on README.md
> +        cmake -DCMAKE_BUILD_TYPE="Release" -Thost=x64 -G "Visual Studio 16 2019" -A x64 -DLLVM_USE_CRT_RELEASE=MT ../
Better to set the `-DCMAKE_INSTALL_PREFIX="<path>"` flag too

2021-02-12 13:11 UTC, ruvi-d commented on README.md
> +  * Install Visual Studio 2019. Please make sure that **Desktop development with C++** should be installed with **C++ CMake tools for Windows** and **C++ ATL for latest v142 build tools (x86 & x64)**
No need to install Visual Studio 2019 IDE. The build tools alone is sufficient since we are build on the command line. https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019

2021-02-12 13:34 UTC, ruvi-d requested changes
Suggested change to the CMake's Windows logic

2021-02-12 13:34 UTC, ruvi-d commented on CMakeLists.txt
> +endif()
We can make this better as :
```
llvm_map_components_to_libnames(llvm_libs codegen)
if (NOT UNIX)
    set_property(TARGET nballerinacc PROPERTY
                MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
endif()
target_link_libraries(codegen_test PRIVATE ${llvm_libs})
```

2021-02-12 14:13 UTC, ruvi-d commented on CMakeLists.txt
> +endif()
^ this will then statically link LLVM libs for both Unix and Windows targets.

2021-02-12 15:28 UTC, ruvi-d commented on CMakeLists.txt
>  target_compile_options(nballerinacc PUBLIC "$<$<CONFIG:RELEASE>:${RELEASE_OPTIONS}>")
`-Wall` is not valid for MSVC. Need to check and add compiler specific flags as shown here: https://alandefreitas.github.io/moderncpp/cmake-functions/target-options/

2021-02-13 19:37 UTC, KavinduZoysa commented on CMakeLists.txt
>  target_compile_options(nballerinacc PUBLIC "$<$<CONFIG:RELEASE>:${RELEASE_OPTIONS}>")
Changed

2021-02-13 19:37 UTC, KavinduZoysa commented on CMakeLists.txt
> +endif()
Changed

2021-02-13 19:37 UTC, KavinduZoysa commented on README.md
> +  * Install Visual Studio 2019. Please make sure that **Desktop development with C++** should be installed with **C++ CMake tools for Windows** and **C++ ATL for latest v142 build tools (x86 & x64)**
Fixed

2021-02-13 19:38 UTC, KavinduZoysa commented on README.md
> +        cmake -DCMAKE_BUILD_TYPE="Release" -Thost=x64 -G "Visual Studio 16 2019" -A x64 -DLLVM_USE_CRT_RELEASE=MT ../
Mentioned that.

2021-02-13 19:38 UTC, KavinduZoysa commented on compiler/BIRReader.cpp
> +    #define random() rand()
Fixed

2021-02-13 19:38 UTC, KavinduZoysa commented on compiler/BIRReader.cpp
> +    p = strcpy(newName, "anon-");
@ruvi-d could you please suggest an option here?

2021-02-14 04:03 UTC, KavinduZoysa commented on compiler/BIRReader.cpp
> +    #define __attribute__(unused)
Could you please explain the relationship between `__attribute__(unused)` and `volatile`? 

Are you suggesting to use `volatile`, to turn off the compiler optimizations for a particular variable?

2021-02-14 04:03 UTC, KavinduZoysa commented on CMakeLists.txt
> +endif()
Are you suggesting here to change the version?

2021-02-14 04:53 UTC, ayonam commented on compiler/BIRReader.cpp
> +    #define __attribute__(unused)
Use of volatile is not a good idea.  The attribute is the better one as it states the true nature of the variable, i.e., unused.  Volatile indicates that there is a use of this variable that may or may not be obvious to the compiler from the plain parsing of the code.  While this attribute tells that the variable is indeed unused.  It is just that Windoze compilers don't understand what most industry standard compilers do; they have to be different in order to assert their technological relevance in the face of obscurity.  So we define this attribute as an empty string on Windoze.

2021-02-14 10:29 UTC, ruvi-d commented on CMakeLists.txt
> +endif()
yes :-)

2021-02-14 10:51 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +    #define __attribute__(unused)
@ayonam but if we define attribute as empty string, wouldn't the MSVC compiler optimize away the "dead load" (because it's unused from the compiler perspective). In the past I have have used the volatile keyword to prevent these kinds of "dead loads" and "dead stores" getting optimized away when accessing controller chip registers.
Correct me if otherwise, but isn't the `__attribute__(unused)` also serving the same purpose here? Preventing the "dead load" of reading the next bytes of the BIR, from getting optimized away?

2021-02-14 10:57 UTC, ruvi-d commented on README.md
> +        cmake -DCMAKE_BUILD_TYPE="Release" -Thost=x64 -G "Visual Studio 16 2019" -A x64 -DLLVM_USE_CRT_RELEASE=MT ../
Let make it a MUST to include this flag. A folder called `install` in the llvm-src dir might be good. Otherwise it looks like it installs to the include folder in your case. That would be a bad idea.

2021-02-14 11:05 UTC, ruvi-d commented on compiler/BIRReader.cpp
> +    p = strcpy(newName, "anon-");
is `stpcpy` not available in MSVCP? If you must use `strcpy` I suppose you could add the length of the "anon-" literal to 'p' to get the same pointer as  `stpcpy`

2021-02-14 13:46 UTC, ayonam commented on compiler/BIRReader.cpp
> +    #define __attribute__(unused)
@ruvi-d Actually, here we only want to suppress the warning.  What you did in the embedded domain, is the standard practice there because there are situations in an embedded processor where a register may be required to be read without the data being used for any purpose.  E.g., reading a piece of data from an I/O Port, where the data being read is not of importance but the succeeding data might be of importance.  But the I/O ports being serial in nature, you cannot read the next data until you have read and discarded the current one.  So in order to force the read operation, the variables are declared as volatile.  Here, our read operations will happen regardless since they are read using a function call.  What we need is a suppression of the warnings and that is best done with the attribute.  This attribute does not control the optimization.

2021-02-15 14:31 UTC, KavinduZoysa commented on README.md
> +        cmake -DCMAKE_BUILD_TYPE="Release" -Thost=x64 -G "Visual Studio 16 2019" -A x64 -DLLVM_USE_CRT_RELEASE=MT ../
@Ruvi, I have set the `-DCMAKE_INSTALL_PREFIX="../install"`. But my `install` folder is empty. If I am wrong could you please provide me the correct way to mention the path with folder structure?

2021-02-15 15:46 UTC, KavinduZoysa commented on CMakeLists.txt
> +endif()
Fixed.

2021-02-15 15:46 UTC, KavinduZoysa commented on README.md
> +        cmake -DCMAKE_BUILD_TYPE="Release" -Thost=x64 -G "Visual Studio 16 2019" -A x64 -DLLVM_USE_CRT_RELEASE=MT ../
Solved it and updated.

2021-02-16 08:58 UTC, uthaiyashankar commented
@KavinduZoysa There are some conflicts due to recent PR merge. Can you fix them too please?

2021-02-16 11:30 UTC, KavinduZoysa commented on compiler/BIRReader.cpp
> +    p = strcpy(newName, "anon-");
Fixed.

2021-02-16 11:33 UTC, KavinduZoysa commented
> @KavinduZoysa There are some conflicts due to recent PR merge. Can you fix them too please?

Fixed.

2021-02-16 14:46 UTC, uthaiyashankar approved these changes

2021-02-16 14:47 UTC, merged