Add TypeBranchInsn
ballerina-platform/nballerina pull request #952
Opened 2022-03-03 04:32 UTC by manuranga

Part of #883

2022-03-25 11:38 UTC, manuranga commented
I ran into a bit of an issue.
let's consider the following case:
```ballerina
public function main() {
    int|string x = 1;
    boolean|float y = true;
    int|float z = 0.2;
    if x is int && y is float && z is int {
        int _ = x;
        float _ = y;
        int _ = z;
    }
}
``` 
In the current draft PR I am generating code as follows:
![before](https://user-images.githubusercontent.com/1686124/160111825-0af86226-8e56-426e-a8f4-d2f9286c7992.svg)

I tried to get rid of the extra BBs to get following code:
![after](https://user-images.githubusercontent.com/1686124/160111847-bd8adf58-f4ce-4d0b-b4c9-71de3cc63e1c.svg)

I am able to generate the above but it has backward branches.

2022-03-29 04:08 UTC, manuranga commented
Just for the record above was a misunderstanding, the backwards-ness is determined by the semantics (what needs to be removed to form DAG?) not by the BB label order.

2022-03-29 04:18 UTC, manuranga commented
I found another issue. Consider
```ballerina
public function main() {
    int|string|boolean|float|decimal x = 1;
    if x is int|string|boolean && x is int|string && x is int {
        int _ = x;
        return;
    }
    string|boolean|float|decimal _ = x;
}
```
I currently create:

<img src="https://user-images.githubusercontent.com/1686124/160531492-44f70a1c-9b8d-40ff-b90a-c30ac093cd1d.svg" width="500">

In order to get the correct result, I ought to generate a single merge per `if`, instead of generating pair-wise. Functionality is not affected.

2022-03-29 04:24 UTC, jclark commented
What is the graph you should produce?

2022-03-29 04:26 UTC, manuranga commented
Same graph, but with a single type merge.
`x.5 = type_merge [bb0 %x.2] [bb1 %x.4] [bb3 %x.7]`

2022-04-21 05:09 UTC, jclark requested changes

2022-04-21 05:09 UTC, jclark commented on compiler/modules/bir/bir.bal
>      INSN_TYPE_TEST,
Need to remove COND_NARROW

2022-04-21 05:09 UTC, jclark commented on compiler/modules/bir/bir.bal
> +    Label[] predecessors;
Need to say predecessors.length() == operands.length()

2022-04-21 05:09 UTC, jclark commented on compiler/modules/front/stmt.bal
> +type TypeMergeSrc record {|
TypeMergeOrigin

2022-04-21 05:09 UTC, jclark commented on compiler/modules/front/stmt.bal
> +function codeGenScope(StmtContext cx, bir:BasicBlock bb, Environment initialEnv, s:StmtBlock|s:IfElseStmt scope, Binding? initialBinding = ()) returns CodeGenError|StmtEffect {
Say what a scope is

2022-04-21 05:09 UTC, jclark commented on compiler/modules/front/stmt.bal
> +    if initialBinding != () {
This looks weird

2022-04-21 05:09 UTC, jclark commented on compiler/modules/front/stmt.bal
>  function applyEffect(Environment env, StmtEffect effect) {
applyStmtEffect

2022-05-02 02:27 UTC, jclark requested changes
I will look again after this is rebased with BindingChain change.

2022-05-02 02:27 UTC, jclark commented on compiler/modules/front/stmt.bal
> +type CondTarget record {|
TypeMerger

2022-05-02 02:27 UTC, jclark commented on compiler/modules/front/expr.bal
> +function assignAndJoin(ExprContext cx, boolean value, bir:BasicBlock block, bir:AssignTmpRegister result, bir:Label contBlock, Position pos) {
Name of this is not OK. Name needs to make it clear that it is mutating `block`.

`block` should be before `value`.

It's creating an assign and a branch insn. The fact that you are using it for joins is not part of the semantic of the function. So something like addAssignAndBranch.

2022-05-11 03:43 UTC, merged

2022-06-09 07:41 UTC, manuranga commented on compiler/modules/nback/scaffold.bal
> +            }
This should be `unnarrow(register).name`