Introduce property-based semtype testing
ballerina-platform/nballerina pull request #997
Opened 2022-04-24 07:03 UTC by rdhananjaya

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2022-05-11 03:56 UTC, jclark requested changes

2022-05-11 03:56 UTC, jclark commented on compiler/tests/random.bal
> +isolated class Random {
I suggest you put this in the comm.lib module.

2022-05-11 03:56 UTC, jclark commented on compiler/modules/front/resolveTypes.bal
> +    s:ModuleLevelDefn? defn = mod.defns[name];
This isn't doing what resolveTypes is doing...

I suggest you have a `resolveDefn(ModuleLevelDefn function)` which `resolveTypes` calls.

2022-05-11 03:56 UTC, jclark commented on compiler/tests/prepositionGenerator.bal
> +    final Limits 'limit;
Better to avoid the reserved word.

2022-05-11 03:56 UTC, jclark commented on compiler/tests/prepositionGenerator.bal
> +class Context {
These names are module-scoped, so I think we need a more specific name, such as GeneratorContext. Some other names here have the same problem.

2022-05-26 03:08 UTC, jclark commented
What tests get run automatically at the moment? Is it possible to do a longer run by hand when desired?

2022-05-26 03:49 UTC, rdhananjaya commented
> What tests get run automatically at the moment? Is it possible to do a longer run by hand when desired?

Subtype proposition tests and Non-empty proposition tests are running automatically at the moment. Due to resource constraints in the VMs and https://github.com/ballerina-platform/ballerina-lang/issues/35923, they cannot be completed within the time limit (of 360m).

2022-05-26 03:55 UTC, jclark commented
> they cannot be completed within the time limit

What does "they" refer to?

I don't want our normal `make test` (as run automatically by github action) to become significantly slower.

We should have some other way to run longer tests (which should be documented somewhere), which we can manually do locally when we make significant changes to semtype implementation.

2022-05-26 04:12 UTC, rdhananjaya commented
> > they cannot be completed within the time limit
> 
> What does "they" refer to?
> 
> I don't want our normal `make test` (as run automatically by github action) to become significantly slower.
> 
> We should have some other way to run longer tests (which should be documented somewhere), which we can manually do locally when we make significant changes to semtype implementation.

"they" meant property-based tests.
Let me find a way to run those property-based tests manually without running them automatically.

2022-05-27 01:50 UTC, jclark requested changes

2022-05-27 01:50 UTC, jclark commented on compiler/Makefile
> +BAL_TEST_FLAGS ?= --disable-groups longRunning
I often do `make test` in the `compiler` directory. So I suggest in `compiler/Makefile` do

```
BAL_TEST_FLAGS ?= $(BAL_BUILD_FLAGS) --disable-groups longRunning

test:
        $(BAL) test $(BAL_TEST_FLAGS)
```

Then people can run all tests with `bal test`.

2022-06-02 05:08 UTC, merged